'use client'

/**
 * ThemeAnglesSection
 *
 * Renders a theme as 24 Korean prose paragraphs (8 angles ×
 * Lifetime/Yearly/Monthly), with a tab toggle so the reader can flip
 * the same chart through three time scales without paying again.
 *
 * Each (theme × period) is generated by Claude Opus 4.7 from the engine
 * signal pool — when the API is available, the prose weaves real saju
 * and astrology evidence (hanja, planet aspects with orb, signal IDs)
 * instead of mad-libs templates. When the API is unavailable, the
 * server falls back to the deterministic templates; the component
 * simply renders whatever the API returns.
 */

import { useEffect, useState } from 'react'
import { Clock, Sparkles, AlertTriangle, TrendingUp, Users, Coins, Heart, Target } from 'lucide-react'
import type { RenderedAngle } from '@/lib/matrix/ai-report/themeAngles'
import type { ReportPeriodScope } from '@/lib/matrix/ai-report/periodSignalContext'
import type { NormalizedSignal } from '@/lib/matrix/ai-report/signalSynthesizer'
import type { TimingData } from '@/lib/matrix/ai-report/types'
import type { ActiveTransit } from '@/lib/matrix/interpreter/types'

type ThemeKey = 'career' | 'love' | 'wealth' | 'health' | 'family' | 'move'

const THEME_LABEL: Record<ThemeKey, string> = {
  career: '커리어',
  love: '연애',
  wealth: '재정',
  health: '건강',
  family: '가족',
  move: '이동',
}

const ANGLE_ICONS: Record<string, typeof Sparkles> = {
  essence: Sparkles,
  strength: TrendingUp,
  weakness: AlertTriangle,
  timing: Clock,
  people: Users,
  moneyVsMeaning: Coins,
  recovery: Heart,
  nextAction: Target,
}

const PERIOD_LABELS: Record<ReportPeriodScope, { label: string; sub: string }> = {
  lifetime: { label: '평생', sub: '본명 기반 — 평생 변하지 않는 결' },
  yearly: { label: '올해', sub: '세운 + 대운 — 1년 흐름' },
  monthly: { label: '이번 달', sub: '월운 + 일진 — 30일 정밀' },
}

const POLARITY_BADGE: Record<string, { label: string; color: string }> = {
  strength: { label: '강점', color: 'text-emerald-300 bg-emerald-500/10 border-emerald-500/30' },
  caution: { label: '주의', color: 'text-rose-300 bg-rose-500/10 border-rose-500/30' },
  balance: { label: '균형', color: 'text-cyan-200 bg-cyan-500/10 border-cyan-500/30' },
}

interface ThemeAnglesSectionProps {
  /** Engine signal pool from the report payload (signalSynthesis.normalizedSignals). */
  signals: NormalizedSignal[]
  /** Per-pillar timing context (TimingData). */
  timing?: TimingData
  /** Currently flagged transit cycles for the target date. */
  activeTransits?: ActiveTransit[]
  /** Birth year to bound the daeun age window properly. */
  birthYear?: number
  /** Date the report is rendered against (defaults to today). */
  targetDate?: string
  /** Theme key — selects which angle pack to render. */
  theme?: ThemeKey
  /** Per-domain × per-timeframe saju↔astro agreement matrix. */
  crossAgreementMatrix?: Array<{
    domain: string
    leadLag?: number
    timescales?: Record<string, { agreement?: number; contradiction?: number; leadLag?: number }>
  }>
}

interface FetchState {
  angles: RenderedAngle[]
  source: 'ai' | 'deterministic'
  loading: boolean
  /** Set when generation is temporarily unavailable. Null on success / initial. */
  unavailable: { message: string } | null
}

export function ThemeAnglesSection({
  signals,
  timing,
  activeTransits,
  birthYear,
  targetDate,
  theme = 'career',
  crossAgreementMatrix,
}: ThemeAnglesSectionProps) {
  const [period, setPeriod] = useState<ReportPeriodScope>('lifetime')
  const [retryToken, setRetryToken] = useState(0)
  const [state, setState] = useState<FetchState>({
    angles: [],
    source: 'ai',
    loading: false,
    unavailable: null,
  })
  const date = targetDate || new Date().toISOString().slice(0, 10)

  useEffect(() => {
    if (!signals || signals.length === 0) {
      setState({ angles: [], source: 'ai', loading: false, unavailable: null })
      return
    }
    const controller = new AbortController()
    setState((prev) => ({ ...prev, loading: true, unavailable: null }))
    fetch('/api/matrix/theme-angles', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        theme,
        period,
        signals,
        timing,
        activeTransits,
        birthYear,
        targetDate: date,
        crossAgreementMatrix,
      }),
      signal: controller.signal,
    })
      .then(async (res) => {
        if (res.status === 503) {
          // Generation is temporarily unavailable — show graceful retry,
          // never expose deterministic fallback prose to the user.
          setState({
            angles: [],
            source: 'ai',
            loading: false,
            unavailable: {
              message:
                '본문 생성이 잠시 지연되고 있어요. 보통 30초 안에 풀려요 — 다시 시도해주세요.',
            },
          })
          return
        }
        if (!res.ok) throw new Error(`HTTP ${res.status}`)
        const data = (await res.json()) as {
          source: 'ai' | 'deterministic'
          angles: RenderedAngle[]
        }
        // Defensive: if the server ever returns deterministic source to
        // the public client (it shouldn't), treat it as unavailable —
        // never render template prose as if it were the paid product.
        if (data.source !== 'ai') {
          setState({
            angles: [],
            source: 'ai',
            loading: false,
            unavailable: {
              message:
                '본문 생성이 잠시 지연되고 있어요. 보통 30초 안에 풀려요 — 다시 시도해주세요.',
            },
          })
          return
        }
        setState({
          angles: data.angles || [],
          source: 'ai',
          loading: false,
          unavailable: null,
        })
      })
      .catch((err: unknown) => {
        if ((err as { name?: string })?.name === 'AbortError') return
        setState({
          angles: [],
          source: 'ai',
          loading: false,
          unavailable: {
            message: '본문을 불러오지 못했어요. 잠시 후 다시 시도해주세요.',
          },
        })
      })
    return () => controller.abort()
  }, [
    signals,
    period,
    date,
    timing,
    activeTransits,
    birthYear,
    theme,
    crossAgreementMatrix,
    retryToken,
  ])

  const angles = state.angles
  if (!state.loading && angles.length === 0 && !state.unavailable) {
    return null
  }

  return (
    <section className="mx-auto mt-6 max-w-4xl px-4">
      <div className="rounded-[28px] border border-cyan-300/15 bg-gradient-to-br from-slate-900/85 to-slate-950/70 p-6 shadow-[0_20px_60px_rgba(8,145,178,0.12)] backdrop-blur-xl">
        <header className="mb-5 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between">
          <div>
            <p className="text-[11px] font-semibold uppercase tracking-[0.32em] text-cyan-200/80">
              Multi-period reading
            </p>
            <h2 className="mt-1 flex items-center gap-2 text-2xl font-semibold text-white">
              {THEME_LABEL[theme || 'career']} — 8가지 각도로 다시 읽기
              {state.source === 'ai' && (
                <span
                  className="rounded-full border border-violet-300/30 bg-violet-500/15 px-2 py-0.5 text-[10px] font-medium uppercase tracking-[0.18em] text-violet-200"
                  title="Claude Opus 4.7 — 신호 풀에서 직접 짜낸 본문"
                >
                  AI
                </span>
              )}
            </h2>
            <p className="mt-1 text-sm text-slate-400">
              같은 사주를 시기별로 다른 렌즈로 다시 봄. 시점만 바꿔도 본문이 바뀜.
            </p>
          </div>
          <div
            className="inline-flex rounded-full border border-white/10 bg-slate-950/60 p-1"
            role="tablist"
            aria-label="시기 선택"
          >
            {(Object.keys(PERIOD_LABELS) as ReportPeriodScope[]).map((p) => {
              const meta = PERIOD_LABELS[p]
              const selected = period === p
              return (
                <button
                  key={p}
                  type="button"
                  role="tab"
                  aria-selected={selected}
                  onClick={() => setPeriod(p)}
                  className={`rounded-full px-4 py-1.5 text-sm font-medium transition-colors ${
                    selected
                      ? 'bg-white/10 text-white shadow-[0_2px_10px_rgba(99,210,255,0.18)]'
                      : 'text-slate-400 hover:text-slate-200'
                  }`}
                >
                  {meta.label}
                </button>
              )
            })}
          </div>
        </header>

        <p className="mb-5 text-[13px] text-cyan-100/70">{PERIOD_LABELS[period].sub}</p>

        {state.unavailable && !state.loading && (
          <div className="rounded-[22px] border border-amber-300/25 bg-gradient-to-br from-amber-500/[0.07] to-slate-900/60 p-6 text-center">
            <div className="mx-auto mb-3 flex h-10 w-10 items-center justify-center rounded-full border border-amber-300/30 bg-amber-400/10">
              <Clock className="h-4 w-4 text-amber-200" strokeWidth={1.6} aria-hidden="true" />
            </div>
            <p className="text-[15px] font-medium text-slate-100">
              {state.unavailable.message}
            </p>
            <p className="mt-1 text-[13px] text-slate-400">
              결제는 그대로 유효해요. 본문은 다시 받아볼 수 있어요.
            </p>
            <button
              type="button"
              onClick={() => setRetryToken((n) => n + 1)}
              className="mt-4 inline-flex items-center gap-2 rounded-full border border-amber-300/40 bg-amber-400/15 px-5 py-2 text-[13px] font-medium text-amber-100 transition-colors hover:bg-amber-400/25"
            >
              다시 시도
            </button>
          </div>
        )}

        {state.loading && angles.length === 0 && (
          <div className="grid gap-4 lg:grid-cols-2">
            {Array.from({ length: 8 }).map((_, i) => (
              <div
                key={`skeleton-${i}`}
                className="h-44 rounded-[22px] border border-white/10 bg-[#090f1b]/60 p-5"
              >
                <div className="h-3 w-24 animate-pulse rounded bg-white/10" />
                <div className="mt-4 space-y-2">
                  <div className="h-3 w-full animate-pulse rounded bg-white/10" />
                  <div className="h-3 w-11/12 animate-pulse rounded bg-white/10" />
                  <div className="h-3 w-9/12 animate-pulse rounded bg-white/10" />
                  <div className="h-3 w-10/12 animate-pulse rounded bg-white/10" />
                </div>
              </div>
            ))}
          </div>
        )}

        <div
          className={`grid gap-4 lg:grid-cols-2 ${state.loading && angles.length > 0 ? 'opacity-60' : ''}`}
        >
          {angles.map((angle, idx) => {
            const Icon = ANGLE_ICONS[angle.angle] || Sparkles
            return (
              <article
                key={angle.angle}
                className="rounded-[22px] border border-white/10 bg-[#090f1b]/80 p-5 transition-colors hover:border-white/20"
              >
                <div className="flex items-center gap-2.5 text-cyan-200/90">
                  <Icon className="h-4 w-4" strokeWidth={1.6} aria-hidden="true" />
                  <span className="text-[10px] font-semibold uppercase tracking-[0.22em]">
                    {String(idx + 1).padStart(2, '0')} · {angle.label}
                  </span>
                </div>
                <p
                  className="mt-3 text-[15px] leading-[1.75] text-slate-100"
                  style={{ wordBreak: 'keep-all' }}
                >
                  {angle.prose}
                </p>
                {angle.evidence.length > 0 && (
                  <div className="mt-4 space-y-1.5 border-t border-white/5 pt-3">
                    {angle.evidence.map((ev) => {
                      const badge = ev.polarity ? POLARITY_BADGE[ev.polarity] : null
                      return (
                        <div
                          key={ev.id}
                          className="flex flex-wrap items-center gap-2 text-[12px] text-slate-400"
                        >
                          {badge && (
                            <span
                              className={`rounded-full border px-2 py-0.5 text-[10px] font-medium ${badge.color}`}
                            >
                              {badge.label}
                            </span>
                          )}
                          <span className="font-medium text-slate-300">{ev.keyword}</span>
                          {(ev.sajuBasis || ev.astroBasis) && (
                            <span className="text-slate-500">
                              · {[ev.sajuBasis, ev.astroBasis].filter(Boolean).join(' / ')}
                            </span>
                          )}
                        </div>
                      )
                    })}
                  </div>
                )}
              </article>
            )
          })}
        </div>

        {state.source === 'ai' && angles.length > 0 && (() => {
          // Parse layer info out of signal IDs ("L5:samhap:trine" → 5,
          // "COV:L3:planet-house..." → 3) and aggregate across all rendered
          // angles. This is a transparency / trust signal — shows the user
          // *how many* engine layers actually got cited, not just one.
          const layerSet = new Set<number>()
          let citedSignals = 0
          for (const angle of angles) {
            for (const ev of angle.evidence) {
              citedSignals++
              const match = ev.id.match(/L(\d+):/)
              if (match) layerSet.add(Number(match[1]))
            }
          }
          if (citedSignals === 0 || layerSet.size === 0) return null
          const sortedLayers = Array.from(layerSet).sort((a, b) => a - b)
          const FUSION_LAYERS = new Set([4, 5, 8])
          const fusionCount = sortedLayers.filter((l) => FUSION_LAYERS.has(l)).length
          return (
            <div className="mt-6 rounded-2xl border border-cyan-300/15 bg-slate-950/50 px-5 py-4">
              <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
                <div>
                  <p className="text-[11px] font-semibold uppercase tracking-[0.22em] text-cyan-200/70">
                    Engine transparency
                  </p>
                  <p className="mt-1 text-[14px] leading-relaxed text-slate-200">
                    이 본문은 사주·점성 엔진의{' '}
                    <span className="font-semibold text-white">{layerSet.size}개 layer</span>
                    에서 추출한{' '}
                    <span className="font-semibold text-white">{citedSignals}개 신호</span>를
                    교차해 짰어요.
                    {fusionCount > 0 && (
                      <>
                        {' '}그 중{' '}
                        <span className="font-semibold text-violet-200">
                          {fusionCount}개는 fusion 신호
                        </span>
                        {' '}— 사주와 점성이 같은 의미를 가리키는 자리예요.
                      </>
                    )}
                  </p>
                </div>
                <div className="flex flex-wrap gap-1.5">
                  {sortedLayers.map((layer) => {
                    const isFusion = FUSION_LAYERS.has(layer)
                    return (
                      <span
                        key={layer}
                        className={`rounded-full border px-2.5 py-0.5 text-[11px] font-medium ${
                          isFusion
                            ? 'border-violet-300/40 bg-violet-500/15 text-violet-100'
                            : 'border-white/15 bg-white/5 text-slate-300'
                        }`}
                        title={
                          layer === 4
                            ? 'Layer 4 — 사주 시기 × 점성 cycle 융합'
                            : layer === 5
                              ? 'Layer 5 — 형충회합 × 각도 융합'
                              : layer === 8
                                ? 'Layer 8 — 신살 × 행성 융합'
                                : `Layer ${layer}`
                        }
                      >
                        L{layer}
                      </span>
                    )
                  })}
                </div>
              </div>
            </div>
          )
        })()}
      </div>
    </section>
  )
}
