// src/components/astrology/constants.ts
// Constants and labels for ResultDisplay component


// 행성 이미지 매핑
export const PLANET_IMAGES: Record<string, string> = {
  Sun: '/images/planets/sun.png',
  Moon: '/images/planets/moon.png',
  Mercury: '/images/planets/mercury.png',
  Venus: '/images/planets/venus.png',
  Mars: '/images/planets/mars.png',
  Jupiter: '/images/planets/jupiter.png',
  Saturn: '/images/planets/saturn.png',
  Uranus: '/images/planets/uranus.png',
  Neptune: '/images/planets/neptune.png',
  Pluto: '/images/planets/pluto.png',
  'True Node': '/images/planets/node.png',
  Chiron: '/images/planets/node.png',
  'Lilith(True)': '/images/planets/pluto.png',
  'Lilith(Mean)': '/images/planets/pluto.png',
  Fortune: '/images/planets/node.png',
};

export const LABELS = {
  en: {
    title: 'Natal Chart Summary',
    asc: 'Ascendant',
    mc: 'MC',
    planetPositions: 'Planet Positions',
    notice: 'Note: This interpretation is automatically generated.',
    planet: 'Planet',
    position: 'Position',
    house: 'House',
    speed: 'Speed',
    ascendant: 'Ascendant (ASC)',
    details: 'Details',
    aspect: 'Aspect',
    from: 'From',
    to: 'To',
    retrograde: 'Retrograde',
    advanced: 'Advanced details',
    engine: 'Engine',
    se: 'Swiss Ephemeris',
    nodeType: 'Node type',
    houseSystem: 'House system',
    theme: 'Theme',
    includeMinor: 'Include minor aspects',
    enable: 'Enable',
    chiron: 'Chiron',
    lilith: 'Lilith',
    pof: 'Part of Fortune',
    extraOnly: 'Points (Extra only)',
    noData: 'No data available.',
  },
  ko: {
    title: '기본 천궁도 요약',
    asc: '상승점',
    mc: '중천',
    planetPositions: '행성 위치',
    notice: '주의: 이 해석은 자동 생성된 요약입니다.',
    planet: '행성',
    position: '위치',
    house: '하우스',
    speed: '속도',
    ascendant: '상승점(ASC)',
    details: '자세히 보기',
    aspect: '위상',
    from: '시작',
    to: '도착',
    retrograde: '역행',
    advanced: '고급 정보',
    engine: '엔진',
    se: 'Swiss Ephemeris',
    nodeType: '노드 타입',
    houseSystem: '하우스 시스템',
    theme: '테마',
    includeMinor: '마이너 위상 포함',
    enable: '추가 포인트',
    chiron: '키론',
    lilith: '리릴리스',
    pof: '행운점',
    extraOnly: '추가 포인트만',
    noData: '데이터가 없습니다.',
  },
  zh: {
    title: '本命盘摘要',
    asc: '上升点',
    mc: '天顶点',
    planetPositions: '行星位置',
    notice: '注意：此解读为自动生成。',
    planet: '行星',
    position: '位置',
    house: '宫位',
    speed: '速度',
    ascendant: '上升点 (ASC)',
    details: '更多详情',
    aspect: '相位',
    from: '起点',
    to: '终点',
    retrograde: '逆行',
    advanced: '高级详情',
    engine: '引擎',
    se: 'Swiss Ephemeris',
    nodeType: '交点类型',
    houseSystem: '宫位系统',
    theme: '主题',
    includeMinor: '包含次要相位',
    enable: '启用',
    chiron: '凯龙星',
    lilith: '莉莉丝',
    pof: '福点',
    extraOnly: '仅显示额外点',
    noData: '暂无数据。',
  },
  ar: {
    title: 'ملخص الخريطة الفلكية',
    asc: 'الطالع',
    mc: 'MC',
    planetPositions: 'مواضع الكواكب',
    notice: 'ملاحظة: هذا التفسير تم إنشاؤه تلقائيًا.',
    planet: 'الكوكب',
    position: 'الموضع',
    house: 'البيت',
    speed: 'السرعة',
    ascendant: 'الطالع (ASC)',
    details: 'تفاصيل',
    aspect: 'زاوية',
    from: 'من',
    to: 'إلى',
    retrograde: 'تراجع',
    advanced: 'تفاصيل متقدمة',
    engine: 'المحرك',
    se: 'Swiss Ephemeris',
    nodeType: 'نوع العقدة',
    houseSystem: 'نظام البيوت',
    theme: 'السيماء',
    includeMinor: 'تضمين الزوايا الثانوية',
    enable: 'تفعيل',
    chiron: 'شيرون',
    lilith: 'ليليث',
    pof: 'نقطة الحظ',
    extraOnly: 'النقاط الإضافية فقط',
    noData: 'لا توجد بيانات.',
  },
  es: {
    title: 'Resumen de Carta Natal',
    asc: 'Ascendente',
    mc: 'MC',
    planetPositions: 'Posiciones de los Planetas',
    notice: 'Aviso: Esta interpretación es generada automáticamente.',
    planet: 'Planeta',
    position: 'Posición',
    house: 'Casa',
    speed: 'Velocidad',
    ascendant: 'Ascendente (ASC)',
    details: 'Ver detalles',
    aspect: 'Aspecto',
    from: 'Desde',
    to: 'Hacia',
    retrograde: 'Retrógrado',
    advanced: 'Detalles avanzados',
    engine: 'Motor',
    se: 'Swiss Ephemeris',
    nodeType: 'Tipo de nodo',
    houseSystem: 'Sistema de casas',
    theme: 'Tema',
    includeMinor: 'Incluir aspectos menores',
    enable: 'Activar',
    chiron: 'Quirón',
    lilith: 'Lilith',
    pof: 'Parte de la Fortuna',
    extraOnly: 'Puntos (solo extra)',
    noData: 'No hay datos.',
  },
} as const;

export const SIGNS = {
  en: ['Aries','Taurus','Gemini','Cancer','Leo','Virgo','Libra','Scorpio','Sagittarius','Capricorn','Aquarius','Pisces'],
  ko: ['양자리','황소자리','쌍둥이자리','게자리','사자자리','처녀자리','천칭자리','전갈자리','사수자리','염소자리','물병자리','물고기자리'],
  zh: ['白羊座','金牛座','双子座','巨蟹座','狮子座','处女座','天秤座','天蝎座','射手座','摩羯座','水瓶座','双鱼座'],
  ar: ['الحمل','الثور','الجوزاء','السرطان','الأسد','العذراء','الميزان','العقرب','القوس','الجدي','الدلو','الحوت'],
  es: ['Aries','Tauro','Géminis','Cáncer','Leo','Virgo','Libra','Escorpio','Sagitario','Capricornio','Acuario','Piscis'],
} as const;

export const PLANET_LABELS = {
  en: { Sun:'Sun', Moon:'Moon', Mercury:'Mercury', Venus:'Venus', Mars:'Mars', Jupiter:'Jupiter', Saturn:'Saturn', Uranus:'Uranus', Neptune:'Neptune', Pluto:'Pluto', 'True Node':'True Node', Chiron:'Chiron', 'Lilith(True)':'Lilith(True)', 'Lilith(Mean)':'Lilith(Mean)', Fortune:'Fortune' },
  ko: { Sun:'태양', Moon:'달', Mercury:'수성', Venus:'금성', Mars:'화성', Jupiter:'목성', Saturn:'토성', Uranus:'천왕성', Neptune:'해왕성', Pluto:'명왕성', 'True Node':'진월교점', Chiron:'키론', 'Lilith(True)':'리릴리스(진)', 'Lilith(Mean)':'리릴리스(평균)', Fortune:'행운점' },
  zh: { Sun:'太阳', Moon:'月亮', Mercury:'水星', Venus:'金星', Mars:'火星', Jupiter:'木星', Saturn:'土星', Uranus:'天王星', Neptune:'海王星', Pluto:'冥王星', 'True Node':'真北交点', Chiron:'凯龙星', 'Lilith(True)':'莉莉丝(真)', 'Lilith(Mean)':'莉莉丝(平)', Fortune:'福点' },
  ar: { Sun:'الشمس', Moon:'القمر', Mercury:'عطارد', Venus:'الزهرة', Mars:'المريخ', Jupiter:'المشتري', Saturn:'زحل', Uranus:'أورانوس', Neptune:'نبتون', Pluto:'بلوتو', 'True Node':'العقدة الشمالية', Chiron:'شيرون', 'Lilith(True)':'ليليث(حقيقي)', 'Lilith(Mean)':'ليليث(متوسط)', Fortune:'نقطة الحظ' },
  es: { Sun:'Sol', Moon:'Luna', Mercury:'Mercurio', Venus:'Venus', Mars:'Marte', Jupiter:'Júpiter', Saturn:'Saturno', Uranus:'Urano', Neptune:'Neptuno', Pluto:'Plutón', 'True Node':'Nodo Norte', Chiron:'Quirón', 'Lilith(True)':'Lilith(Verdad)', 'Lilith(Mean)':'Lilith(Media)', Fortune:'Parte de la Fortuna' },
} as const;

export const ASPECT_LABELS = {
  en: { conjunction:'conjunction', opposition:'opposition', square:'square', trine:'trine', sextile:'sextile', quincunx:'quincunx', semisextile:'semisextile', quintile:'quintile' },
  ko: { conjunction:'합', opposition:'대립', square:'사각', trine:'삼합', sextile:'육분', quincunx:'퀸컨크스', semisextile:'반육분', quintile:'퀸타일' },
  zh: { conjunction:'合相', opposition:'对冲', square:'四分相', trine:'拱相', sextile:'六合', quincunx:'梅花相', semisextile:'半六合', quintile:'五分相' },
  ar: { conjunction:'اقتران', opposition:'تعارض', square:'تربيع', trine:'تثليث', sextile:'تسديس', quincunx:'كوينكونكس', semisextile:'نصف تسديس', quintile:'كوينتايل' },
  es: { conjunction:'conjunción', opposition:'oposición', square:'cuadratura', trine:'trígono', sextile:'sextil', quincunx:'quincuncio', semisextile:'semisextil', quintile:'quintil' },
} as const;

export const PAYWALL_LABELS = {
  en: {
    loginRequired: 'Login Required',
    loginDesc: 'Sign in to view detailed chart analysis',
    loginBtn: 'Sign In',
    premiumRequired: 'Premium Feature',
    premiumDesc: 'Upgrade to Premium to unlock detailed planetary positions, houses, and aspect analysis',
    premiumBtn: 'Upgrade to Premium',
    advancedPremiumDesc: 'Get advanced analysis including extra celestial points, engine details, and in-depth interpretations',
  },
  ko: {
    loginRequired: '로그인이 필요합니다',
    loginDesc: '상세 차트 분석을 보려면 로그인하세요',
    loginBtn: '로그인',
    premiumRequired: '프리미엄 전용',
    premiumDesc: '행성 위치, 하우스, 위상 분석을 확인하려면 프리미엄으로 업그레이드하세요',
    premiumBtn: '프리미엄 업그레이드',
    advancedPremiumDesc: '추가 천체 포인트, 엔진 상세 정보, 심층 해석을 확인하세요',
  },
  zh: {
    loginRequired: '需要登录',
    loginDesc: '登录以查看详细星盘分析',
    loginBtn: '登录',
    premiumRequired: '高级功能',
    premiumDesc: '升级到高级版以解锁行星位置、宫位和相位分析',
    premiumBtn: '升级到高级版',
    advancedPremiumDesc: '获取高级分析，包括额外天体点、引擎详情和深度解读',
  },
  ar: {
    loginRequired: 'تسجيل الدخول مطلوب',
    loginDesc: 'سجّل الدخول لعرض تحليل الخريطة المفصل',
    loginBtn: 'تسجيل الدخول',
    premiumRequired: 'ميزة مميزة',
    premiumDesc: 'قم بالترقية إلى Premium لفتح مواضع الكواكب والبيوت وتحليل الزوايا',
    premiumBtn: 'الترقية إلى Premium',
    advancedPremiumDesc: 'احصل على تحليل متقدم يشمل نقاط سماوية إضافية وتفاصيل المحرك والتفسيرات المعمقة',
  },
  es: {
    loginRequired: 'Inicio de sesión requerido',
    loginDesc: 'Inicia sesión para ver el análisis detallado de la carta',
    loginBtn: 'Iniciar sesión',
    premiumRequired: 'Función Premium',
    premiumDesc: 'Actualiza a Premium para desbloquear posiciones planetarias, casas y análisis de aspectos',
    premiumBtn: 'Actualizar a Premium',
    advancedPremiumDesc: 'Obtén análisis avanzado incluyendo puntos celestes adicionales, detalles del motor e interpretaciones en profundidad',
  },
} as const;

// Extra point names for filtering
export const EXTRA_NAMES = new Set([
  'Chiron','키론','Lilith','리릴리스','Lilith(True)','Lilith(Mean)','Black Moon Lilith',
  'Part of Fortune','Fortune','행운점','True Node','Mean Node','North Node','South Node','진월교점',
]);

// Chat I18N
export type ChatLangKey = "en" | "ko" | "ja" | "zh" | "es" | "fr" | "de" | "pt" | "ru";

export type ChatCopy = {
  placeholder: string;
  send: string;
  thinking: string;
  empty: string;
  error: string;
  fallbackNote: string;
  noResponse: string;
  recording: string;
  stopRecording: string;
  crisisTitle: string;
  crisisMessage: string;
  crisisHotline: string;
  crisisHotlineNumber: string;
  crisisClose: string;
  welcomeBack: string;
};

export const CHAT_I18N: Record<ChatLangKey, ChatCopy> = {
  en: {
    placeholder: "Ask about your birth chart (planets, houses, transits)",
    send: "Send",
    thinking: "Reading the celestial energies...",
    empty: "Ask about your astrology chart for personalized guidance.",
    error: "An error occurred. Please try again.",
    fallbackNote: "Using backup response (AI temporarily unavailable).",
    noResponse: "No response received. Try again later.",
    recording: "Recording...",
    stopRecording: "Stop",
    crisisTitle: "We're Here For You",
    crisisMessage: "It sounds like you're going through a really difficult time. Please know that support is available.",
    crisisHotline: "Crisis Hotline",
    crisisHotlineNumber: "988 (US) / 116 123 (UK)",
    crisisClose: "I understand",
    welcomeBack: "Welcome back! Let's continue exploring your stars.",
  },
  ko: {
    placeholder: "별자리 차트에 대해 질문해 주세요 (행성, 하우스, 트랜짓)",
    send: "보내기",
    thinking: "별들의 에너지를 읽고 있습니다...",
    empty: "점성술 차트에 대해 질문하시면 맞춤 상담을 받으실 수 있습니다.",
    error: "오류가 발생했습니다. 다시 시도해 주세요.",
    fallbackNote: "백업 응답으로 대신합니다 (AI 일시 불가).",
    noResponse: "응답을 받을 수 없습니다. 잠시 후 다시 시도해 주세요.",
    recording: "녹음 중...",
    stopRecording: "중지",
    crisisTitle: "당신 곁에 있어요",
    crisisMessage: "지금 많이 힘드시죠. 혼자가 아니에요. 전문 상담 도움을 받으실 수 있어요.",
    crisisHotline: "위기상담전화",
    crisisHotlineNumber: "자살예방 1393 / 정신건강 1577-0199",
    crisisClose: "확인했어요",
    welcomeBack: "다시 오셨네요! 별자리 상담을 이어갈까요?",
  },
  ja: {
    placeholder: "出生チャートについて質問してください",
    send: "送信",
    thinking: "天体のエネルギーを読み取っています...",
    empty: "占星術チャートについてお聞きください。",
    error: "エラーが発生しました。もう一度お試しください。",
    fallbackNote: "バックアップの応答を返しました。",
    noResponse: "応答がありません。しばらくしてからお試しください。",
    recording: "録音中...",
    stopRecording: "停止",
    crisisTitle: "あなたのそばにいます",
    crisisMessage: "今、とても辛い時期を過ごしていますね。専門のサポートがあります。",
    crisisHotline: "相談窓口",
    crisisHotlineNumber: "いのちの電話 0570-783-556",
    crisisClose: "確認しました",
    welcomeBack: "お帰りなさい！占星術の相談を続けましょう。",
  },
  zh: {
    placeholder: "请询问您的星盘",
    send: "发送",
    thinking: "正在读取天体能量...",
    empty: "请询问您的星盘以获得个性化指导。",
    error: "发生错误，请稍后重试。",
    fallbackNote: "返回了备用回答。",
    noResponse: "暂无回复，请稍后再试。",
    recording: "录音中...",
    stopRecording: "停止",
    crisisTitle: "我们在您身边",
    crisisMessage: "您现在正经历困难时期。您并不孤单。",
    crisisHotline: "心理援助热线",
    crisisHotlineNumber: "全国心理援助 400-161-9995",
    crisisClose: "我了解了",
    welcomeBack: "欢迎回来！让我们继续星盘咨询。",
  },
  es: {
    placeholder: "Pregunta sobre tu carta natal",
    send: "Enviar",
    thinking: "Leyendo las energías celestiales...",
    empty: "Pregunta sobre tu carta astral para orientacion personalizada.",
    error: "Ocurrio un error. Intentalo de nuevo.",
    fallbackNote: "Respuesta de respaldo.",
    noResponse: "Sin respuesta. Intentalo mas tarde.",
    recording: "Grabando...",
    stopRecording: "Detener",
    crisisTitle: "Estamos contigo",
    crisisMessage: "Parece que estás pasando por un momento difícil.",
    crisisHotline: "Línea de crisis",
    crisisHotlineNumber: "Teléfono de la Esperanza 717 003 717",
    crisisClose: "Entendido",
    welcomeBack: "¡Bienvenido! Continuemos con tu astrología.",
  },
  fr: {
    placeholder: "Posez une question sur votre thème astral",
    send: "Envoyer",
    thinking: "Lecture des énergies célestes...",
    empty: "Posez une question sur votre thème natal.",
    error: "Une erreur s'est produite.",
    fallbackNote: "Réponse de secours.",
    noResponse: "Pas de réponse.",
    recording: "Enregistrement...",
    stopRecording: "Arrêter",
    crisisTitle: "Nous sommes là pour vous",
    crisisMessage: "Vous traversez une période difficile.",
    crisisHotline: "Ligne de crise",
    crisisHotlineNumber: "SOS Amitié 09 72 39 40 50",
    crisisClose: "J'ai compris",
    welcomeBack: "Bon retour ! Continuons votre astrologie.",
  },
  de: {
    placeholder: "Fragen Sie nach Ihrem Geburtshoroskop",
    send: "Senden",
    thinking: "Lese die himmlischen Energien...",
    empty: "Fragen Sie nach Ihrem Horoskop.",
    error: "Ein Fehler ist aufgetreten.",
    fallbackNote: "Backup-Antwort.",
    noResponse: "Keine Antwort.",
    recording: "Aufnahme...",
    stopRecording: "Stoppen",
    crisisTitle: "Wir sind für Sie da",
    crisisMessage: "Sie durchleben gerade eine schwierige Zeit.",
    crisisHotline: "Krisenhotline",
    crisisHotlineNumber: "Telefonseelsorge 0800 111 0 111",
    crisisClose: "Verstanden",
    welcomeBack: "Willkommen zurück! Lassen Sie uns Ihre Astrologie fortsetzen.",
  },
  pt: {
    placeholder: "Pergunte sobre seu mapa astral",
    send: "Enviar",
    thinking: "Lendo as energias celestiais...",
    empty: "Pergunte sobre seu mapa astral.",
    error: "Ocorreu um erro.",
    fallbackNote: "Resposta de backup.",
    noResponse: "Nenhuma resposta.",
    recording: "Gravando...",
    stopRecording: "Parar",
    crisisTitle: "Estamos com você",
    crisisMessage: "Você está passando por um momento difícil.",
    crisisHotline: "Linha de crise",
    crisisHotlineNumber: "CVV 188",
    crisisClose: "Entendi",
    welcomeBack: "Bem-vindo de volta! Vamos continuar sua astrologia.",
  },
  ru: {
    placeholder: "Спросите о вашей натальной карте",
    send: "Отправить",
    thinking: "Читаем небесные энергии...",
    empty: "Спросите о вашей карте рождения.",
    error: "Произошла ошибка.",
    fallbackNote: "Резервный ответ.",
    noResponse: "Нет ответа.",
    recording: "Запись...",
    stopRecording: "Стоп",
    crisisTitle: "Мы рядом с вами",
    crisisMessage: "Похоже, вы переживаете трудное время.",
    crisisHotline: "Линия помощи",
    crisisHotlineNumber: "8-800-2000-122",
    crisisClose: "Понятно",
    welcomeBack: "С возвращением! Продолжим астрологическую консультацию.",
  },
};

// Follow-up questions for astrology chat
export const ASTROLOGY_FOLLOWUPS = {
  ko: [
    "제 태양 별자리의 특성을 알려주세요",
    "달 별자리가 감정에 어떤 영향을 주나요?",
    "현재 행성 트랜짓은 어떤가요?",
    "상승궁이 뭔가요? 제 성격에 어떤 영향이 있나요?",
    "금성의 위치가 연애운에 어떤 영향을 주나요?",
    "토성 리턴이 뭔가요?",
    "수성 역행 기간에 주의할 점은?",
    "제 7하우스에 대해 알려주세요",
    "목성이 어느 하우스에 있나요?",
    "올해 주요 트랜짓은 무엇인가요?",
  ],
  en: [
    "Tell me about my Sun sign characteristics",
    "How does my Moon sign affect my emotions?",
    "What are the current planetary transits?",
    "What is my rising sign and how does it affect me?",
    "How does Venus placement affect my love life?",
    "What is Saturn return?",
    "What to watch during Mercury retrograde?",
    "Tell me about my 7th house",
    "Which house is Jupiter in my chart?",
    "What are the major transits this year?",
  ],
} as const;
