// src/components/astrology/constants.ts
// Constants and labels for ResultDisplay component

export const LABELS = {
  en: {
    title: 'Natal Chart Summary',
    asc: 'Ascendant',
    mc: 'MC',
    planetPositions: 'Planet Positions',
    notice: 'Note: This interpretation is automatically generated.',
    planet: 'Planet',
    position: 'Position',
    house: 'House',
    speed: 'Speed',
    ascendant: 'Ascendant (ASC)',
    details: 'Details',
    aspect: 'Aspect',
    from: 'From',
    to: 'To',
    retrograde: 'Retrograde',
    advanced: 'Advanced details',
    engine: 'Engine',
    se: 'Swiss Ephemeris',
    nodeType: 'Node type',
    houseSystem: 'House system',
    theme: 'Theme',
    includeMinor: 'Include minor aspects',
    enable: 'Enable',
    chiron: 'Chiron',
    lilith: 'Lilith',
    pof: 'Part of Fortune',
    extraOnly: 'Points (Extra only)',
    noData: 'No data available.',
  },
  ko: {
    title: '기본 천궁도 요약',
    asc: '상승점',
    mc: '중천',
    planetPositions: '행성 위치',
    notice: '주의: 이 해석은 자동 생성된 요약입니다.',
    planet: '행성',
    position: '위치',
    house: '하우스',
    speed: '속도',
    ascendant: '상승점(ASC)',
    details: '자세히 보기',
    aspect: '위상',
    from: '시작',
    to: '도착',
    retrograde: '역행',
    advanced: '고급 정보',
    engine: '엔진',
    se: 'Swiss Ephemeris',
    nodeType: '노드 타입',
    houseSystem: '하우스 시스템',
    theme: '테마',
    includeMinor: '마이너 위상 포함',
    enable: '추가 포인트',
    chiron: '키론',
    lilith: '리릴리스',
    pof: '행운점',
    extraOnly: '추가 포인트만',
    noData: '데이터가 없습니다.',
  },
  zh: {
    title: '本命盘摘要',
    asc: '上升点',
    mc: '天顶点',
    planetPositions: '行星位置',
    notice: '注意：此解读为自动生成。',
    planet: '行星',
    position: '位置',
    house: '宫位',
    speed: '速度',
    ascendant: '上升点 (ASC)',
    details: '更多详情',
    aspect: '相位',
    from: '起点',
    to: '终点',
    retrograde: '逆行',
    advanced: '高级详情',
    engine: '引擎',
    se: 'Swiss Ephemeris',
    nodeType: '交点类型',
    houseSystem: '宫位系统',
    theme: '主题',
    includeMinor: '包含次要相位',
    enable: '启用',
    chiron: '凯龙星',
    lilith: '莉莉丝',
    pof: '福点',
    extraOnly: '仅显示额外点',
    noData: '暂无数据。',
  },
  ar: {
    title: 'ملخص الخريطة الفلكية',
    asc: 'الطالع',
    mc: 'MC',
    planetPositions: 'مواضع الكواكب',
    notice: 'ملاحظة: هذا التفسير تم إنشاؤه تلقائيًا.',
    planet: 'الكوكب',
    position: 'الموضع',
    house: 'البيت',
    speed: 'السرعة',
    ascendant: 'الطالع (ASC)',
    details: 'تفاصيل',
    aspect: 'زاوية',
    from: 'من',
    to: 'إلى',
    retrograde: 'تراجع',
    advanced: 'تفاصيل متقدمة',
    engine: 'المحرك',
    se: 'Swiss Ephemeris',
    nodeType: 'نوع العقدة',
    houseSystem: 'نظام البيوت',
    theme: 'السيماء',
    includeMinor: 'تضمين الزوايا الثانوية',
    enable: 'تفعيل',
    chiron: 'شيرون',
    lilith: 'ليليث',
    pof: 'نقطة الحظ',
    extraOnly: 'النقاط الإضافية فقط',
    noData: 'لا توجد بيانات.',
  },
  es: {
    title: 'Resumen de Carta Natal',
    asc: 'Ascendente',
    mc: 'MC',
    planetPositions: 'Posiciones de los Planetas',
    notice: 'Aviso: Esta interpretación es generada automáticamente.',
    planet: 'Planeta',
    position: 'Posición',
    house: 'Casa',
    speed: 'Velocidad',
    ascendant: 'Ascendente (ASC)',
    details: 'Ver detalles',
    aspect: 'Aspecto',
    from: 'Desde',
    to: 'Hacia',
    retrograde: 'Retrógrado',
    advanced: 'Detalles avanzados',
    engine: 'Motor',
    se: 'Swiss Ephemeris',
    nodeType: 'Tipo de nodo',
    houseSystem: 'Sistema de casas',
    theme: 'Tema',
    includeMinor: 'Incluir aspectos menores',
    enable: 'Activar',
    chiron: 'Quirón',
    lilith: 'Lilith',
    pof: 'Parte de la Fortuna',
    extraOnly: 'Puntos (solo extra)',
    noData: 'No hay datos.',
  },
} as const;

export const SIGNS = {
  en: ['Aries','Taurus','Gemini','Cancer','Leo','Virgo','Libra','Scorpio','Sagittarius','Capricorn','Aquarius','Pisces'],
  ko: ['양자리','황소자리','쌍둥이자리','게자리','사자자리','처녀자리','천칭자리','전갈자리','사수자리','염소자리','물병자리','물고기자리'],
  zh: ['白羊座','金牛座','双子座','巨蟹座','狮子座','处女座','天秤座','天蝎座','射手座','摩羯座','水瓶座','双鱼座'],
  ar: ['الحمل','الثور','الجوزاء','السرطان','الأسد','العذراء','الميزان','العقرب','القوس','الجدي','الدلو','الحوت'],
  es: ['Aries','Tauro','Géminis','Cáncer','Leo','Virgo','Libra','Escorpio','Sagitario','Capricornio','Acuario','Piscis'],
} as const;

export const PLANET_LABELS = {
  en: { Sun:'Sun', Moon:'Moon', Mercury:'Mercury', Venus:'Venus', Mars:'Mars', Jupiter:'Jupiter', Saturn:'Saturn', Uranus:'Uranus', Neptune:'Neptune', Pluto:'Pluto', 'True Node':'True Node', Chiron:'Chiron', 'Lilith(True)':'Lilith(True)', 'Lilith(Mean)':'Lilith(Mean)', Fortune:'Fortune' },
  ko: { Sun:'태양', Moon:'달', Mercury:'수성', Venus:'금성', Mars:'화성', Jupiter:'목성', Saturn:'토성', Uranus:'천왕성', Neptune:'해왕성', Pluto:'명왕성', 'True Node':'진월교점', Chiron:'키론', 'Lilith(True)':'리릴리스(진)', 'Lilith(Mean)':'리릴리스(평균)', Fortune:'행운점' },
  zh: { Sun:'太阳', Moon:'月亮', Mercury:'水星', Venus:'金星', Mars:'火星', Jupiter:'木星', Saturn:'土星', Uranus:'天王星', Neptune:'海王星', Pluto:'冥王星', 'True Node':'真北交点', Chiron:'凯龙星', 'Lilith(True)':'莉莉丝(真)', 'Lilith(Mean)':'莉莉丝(平)', Fortune:'福点' },
  ar: { Sun:'الشمس', Moon:'القمر', Mercury:'عطارد', Venus:'الزهرة', Mars:'المريخ', Jupiter:'المشتري', Saturn:'زحل', Uranus:'أورانوس', Neptune:'نبتون', Pluto:'بلوتو', 'True Node':'العقدة الشمالية', Chiron:'شيرون', 'Lilith(True)':'ليليث(حقيقي)', 'Lilith(Mean)':'ليليث(متوسط)', Fortune:'نقطة الحظ' },
  es: { Sun:'Sol', Moon:'Luna', Mercury:'Mercurio', Venus:'Venus', Mars:'Marte', Jupiter:'Júpiter', Saturn:'Saturno', Uranus:'Urano', Neptune:'Neptuno', Pluto:'Plutón', 'True Node':'Nodo Norte', Chiron:'Quirón', 'Lilith(True)':'Lilith(Verdad)', 'Lilith(Mean)':'Lilith(Media)', Fortune:'Parte de la Fortuna' },
} as const;

