// src/components/astrology/constants.ts
// Constants and labels for ResultDisplay component

export const LABELS = {
  en: {
    title: 'Natal Chart Summary',
    asc: 'Ascendant',
    mc: 'MC',
    planetPositions: 'Planet Positions',
    notice: 'Note: This interpretation is automatically generated.',
    planet: 'Planet',
    position: 'Position',
    house: 'House',
    speed: 'Speed',
    ascendant: 'Ascendant (ASC)',
    details: 'Details',
    aspect: 'Aspect',
    from: 'From',
    to: 'To',
    retrograde: 'Retrograde',
    advanced: 'Advanced details',
    engine: 'Engine',
    se: 'Swiss Ephemeris',
    nodeType: 'Node type',
    houseSystem: 'House system',
    theme: 'Theme',
    includeMinor: 'Include minor aspects',
    enable: 'Enable',
    chiron: 'Chiron',
    lilith: 'Lilith',
    pof: 'Part of Fortune',
    extraOnly: 'Points (Extra only)',
    noData: 'No data available.',
  },
  ko: {
    title: '기본 천궁도 요약',
    asc: '상승점',
    mc: '중천점',
    planetPositions: '행성 위치',
    notice: '주의: 이 해석은 자동 생성된 요약입니다.',
    planet: '행성',
    position: '위치',
    house: '하우스',
    speed: '속도',
    ascendant: '상승점(ASC)',
    details: '자세히 보기',
    aspect: '위상',
    from: '시작',
    to: '도착',
    retrograde: '역행',
    advanced: '고급 정보',
    engine: '엔진',
    se: 'Swiss Ephemeris',
    nodeType: '노드 타입',
    houseSystem: '하우스 시스템',
    theme: '테마',
    includeMinor: '마이너 위상 포함',
    enable: '추가 포인트',
    chiron: '키론',
    lilith: '리릴리스',
    pof: '행운점',
    extraOnly: '추가 포인트만',
    noData: '데이터가 없습니다.',
  },
} as const

export const SIGNS = {
  en: [
    'Aries',
    'Taurus',
    'Gemini',
    'Cancer',
    'Leo',
    'Virgo',
    'Libra',
    'Scorpio',
    'Sagittarius',
    'Capricorn',
    'Aquarius',
    'Pisces',
  ],
  ko: [
    '양자리',
    '황소자리',
    '쌍둥이자리',
    '게자리',
    '사자자리',
    '처녀자리',
    '천칭자리',
    '전갈자리',
    '사수자리',
    '염소자리',
    '물병자리',
    '물고기자리',
  ],
} as const

export const PLANET_LABELS = {
  en: {
    Sun: 'Sun',
    Moon: 'Moon',
    Mercury: 'Mercury',
    Venus: 'Venus',
    Mars: 'Mars',
    Jupiter: 'Jupiter',
    Saturn: 'Saturn',
    Uranus: 'Uranus',
    Neptune: 'Neptune',
    Pluto: 'Pluto',
    'True Node': 'True Node',
    Chiron: 'Chiron',
    'Lilith(True)': 'Lilith(True)',
    'Lilith(Mean)': 'Lilith(Mean)',
    Fortune: 'Fortune',
  },
  ko: {
    Sun: '태양',
    Moon: '달',
    Mercury: '수성',
    Venus: '금성',
    Mars: '화성',
    Jupiter: '목성',
    Saturn: '토성',
    Uranus: '천왕성',
    Neptune: '해왕성',
    Pluto: '명왕성',
    'True Node': '진월교점',
    Chiron: '키론',
    'Lilith(True)': '리릴리스(진)',
    'Lilith(Mean)': '리릴리스(평균)',
    Fortune: '행운점',
  },
} as const
