import { describe, expect, it } from 'vitest'

import { buildCalendarPresentationView } from '@/app/api/calendar/lib/presentationAdapter'
import type { FormattedDate } from '@/app/api/calendar/lib/types'

const dates: FormattedDate[] = [
  {
    date: '2026-04-03',
    grade: 1,
    displayGrade: 1,
    score: 86,
    displayScore: 86,
    categories: ['career'],
    title: 'Career window',
    description: 'Career window',
    summary: 'Use the day for focused execution.',
    actionSummary: 'Close one clear application.',
    timingSignals: ['Career timing is opening.'],
    bestTimes: ['09:00-11:00'],
    sajuFactors: ['Saju support'],
    astroFactors: ['Astro support'],
    recommendations: ['Submit one strong application'],
    warnings: ['Avoid rushed commitments'],
    evidence: {
      confidence: 84,
      crossAgreementPercent: 76,
      matrix: { domain: 'career' },
    } as any,
  },
]

describe('calendar presentation adapter', () => {
  it('surfaces single-subject action, timing, and branch information first', () => {
    const view = buildCalendarPresentationView({
      allDates: dates,
      locale: 'en',
      timeZone: 'Asia/Hong_Kong',
      canonicalCore: {
        focusDomain: 'career',
        actionFocusDomain: 'career',
        phase: 'activation',
        phaseLabel: 'Activation',
        thesis: 'Career execution is supported.',
        gradeReason: 'Career alignment is high.',
        riskAxisLabel: 'health',
        confidence: 0.82,
        crossAgreement: 0.74,
        topDecisionLabel: 'Submit two targeted applications',
        primaryAction: 'Submit two targeted applications',
        primaryCaution: 'Do not overextend.',
        judgmentPolicy: {
          mode: 'execute',
          allowedActions: ['apply'],
          allowedActionLabels: ['Submit applications'],
          blockedActions: [],
          blockedActionLabels: [],
          hardStops: [],
          hardStopLabels: [],
          softChecks: ['Check role scope'],
          softCheckLabels: ['Check role scope'],
          rationale: 'Act with verification.',
        },
        advisories: [],
        topTimingWindow: {
          domain: 'career',
          window: '1-3m',
          confidence: 0.8,
          timingRelevance: 0.8,
          timingGranularity: 'month',
          precisionReason: 'Signals converge.',
          timingConflictMode: 'aligned',
          timingConflictNarrative: 'Readiness and trigger move together.',
          readinessScore: 0.8,
          triggerScore: 0.8,
          convergenceScore: 0.8,
          whyNow: 'The job-entry window is opening now.',
          entryConditions: ['Role scope is clear'],
          abortConditions: ['Cash pressure spikes'],
          evidenceIds: [],
          provenance: {
            sourceFields: [],
            sourceSignalIds: [],
            sourceRuleIds: [],
            sourceSetIds: [],
          },
        },
        domainTimingWindows: [],
        domainVerdicts: [],
        manifestations: [],
        coherenceAudit: {
          verificationBias: false,
          gatedDecision: false,
          domainConflictCount: 0,
          contradictionFlags: [],
          notes: [],
        },
        arbitrationBrief: {
          focusWinnerDomain: 'career',
          focusWinnerReason: 'Career leads.',
          focusRunnerUpDomain: null,
          actionWinnerDomain: 'career',
          actionWinnerReason: 'Career acts first.',
          actionRunnerUpDomain: null,
          conflictReasons: [],
          focusNarrative: 'Career leads.',
          actionNarrative: 'Career acts first.',
          suppressionNarratives: [],
        },
        latentTopAxes: [],
        projections: {
          structure: {
            headline: 'Structure',
            summary: 'Career structure is dominant.',
            reasons: [],
            detailLines: ['Career structure is dominant.'],
            drivers: [],
            counterweights: [],
            nextMoves: [],
          },
          timing: {
            headline: 'Timing',
            summary: 'The window is opening.',
            reasons: [],
            detailLines: ['The window is opening.'],
            drivers: [],
            counterweights: [],
            nextMoves: [],
          },
          conflict: {
            headline: 'Conflict',
            summary: 'Keep verification on.',
            reasons: [],
            detailLines: ['Keep verification on.'],
            drivers: [],
            counterweights: [],
            nextMoves: [],
          },
          action: {
            headline: 'Action',
            summary: 'Submit the applications.',
            reasons: [],
            detailLines: ['Submit the applications.'],
            drivers: [],
            counterweights: [],
            nextMoves: ['Submit two targeted applications'],
          },
          risk: {
            headline: 'Risk',
            summary: 'Do not overextend.',
            reasons: [],
            detailLines: ['Do not overextend.'],
            drivers: [],
            counterweights: [],
            nextMoves: [],
          },
          evidence: {
            headline: 'Evidence',
            summary: 'Signals agree.',
            reasons: [],
            detailLines: ['Signals agree.'],
            drivers: [],
            counterweights: [],
            nextMoves: [],
          },
          branches: {
            headline: 'Branches',
            summary: 'Structured roles open first.',
            reasons: [],
            detailLines: ['Structured roles open first.'],
            drivers: [],
            counterweights: [],
            nextMoves: ['Shortlist two roles first.'],
          },
        },
        singleSubjectView: {
          directAnswer: 'This is a career-entry phase.',
          structureAxis: {
            domain: 'career',
            label: 'Career',
            thesis: 'Career is the lead axis.',
            topAxes: ['career pressure'],
          },
          actionAxis: {
            domain: 'career',
            label: 'Career',
            nowAction: 'Submit two targeted applications',
            whyThisFirst: 'Action is clearer than more preparation.',
          },
          riskAxis: {
            domain: 'health',
            label: 'Health',
            warning: 'Lower overwork risk first.',
            hardStops: ['Sleep collapse'],
          },
          timingState: {
            bestWindow: '1-3m',
            whyNow: 'The job-entry window is opening now.',
            whyNotYet: 'Do not force vague roles.',
            confidence: 0.8,
            windows: [],
          },
          competingPressures: [],
          branches: [
            {
              label: 'A-track',
              summary: 'Structured roles open first.',
              entryConditions: ['Role scope is clear'],
              abortConditions: ['Cash pressure spikes'],
              nextMove: 'Shortlist two roles first.',
            },
          ],
          entryConditions: ['Role scope is clear'],
          abortConditions: ['Cash pressure spikes'],
          nextMove: 'Submit two targeted applications',
          confidence: 0.8,
          reliability: { contradictionFlags: [], notes: [] },
        },
        personModel: {
          overview: 'Career structure is moving first.',
          structuralCore: {
            focusDomain: 'career',
            actionFocusDomain: 'career',
            riskAxisDomain: 'health',
            gradeLabel: 'strong',
            phaseLabel: 'Activation',
            overview: 'Career structure is moving first.',
            latentAxes: [],
          },
          formationProfile: {
            summary: '',
            repeatedPatternFamilies: [],
            dominantLatentGroups: [],
            pressureHabits: [],
            supportHabits: [],
          },
          timeProfile: {
            timingNarrative: '',
            confidence: 0.8,
            windows: [],
            activationSources: [],
          },
          layers: [],
          dimensions: [],
          domainStateGraph: [
            {
              domain: 'career',
              label: 'Career',
              currentState: 'expansion',
              currentWindow: '1-3m',
              thesis: 'Career is the domain to convert into visible moves now.',
              supportSignals: [],
              pressureSignals: [],
              alignedWith: [],
              conflictingWith: [],
              nextShift: 'Execution stabilizes after shortlisting.',
              firstMove: 'Submit two targeted applications',
              holdMove: 'Avoid vague roles.',
              timescales: [],
            },
          ],
          domainPortraits: [],
          states: [],
          appliedProfile: {
            foodProfile: {
              summary: '',
              thermalBias: '',
              digestionStyle: '',
              helpfulFoods: [],
              cautionFoods: [],
              rhythmGuidance: [],
            },
            lifeRhythmProfile: {
              summary: 'Keep recovery fixed before evening decisions.',
              peakWindows: [],
              recoveryWindows: [],
              stressBehaviors: [],
              regulationMoves: [],
            },
            relationshipStyleProfile: {
              summary: '',
              attractionPatterns: [],
              stabilizers: [],
              ruptureTriggers: [],
              repairMoves: [],
            },
            workStyleProfile: {
              summary: 'You work best with explicit scope and ownership.',
              bestRoles: [],
              bestConditions: [],
              fatigueTriggers: [],
              leverageMoves: [],
            },
            moneyStyleProfile: {
              summary: '',
              earningPattern: [],
              savingPattern: [],
              leakageRisks: [],
              controlRules: [],
            },
            environmentProfile: {
              summary: '',
              preferredSettings: [],
              drainSignals: [],
              resetActions: [],
            },
          },
          relationshipProfile: {
            summary: '',
            partnerArchetypes: [],
            inflowPaths: [],
            commitmentConditions: [],
            breakPatterns: [],
          },
          careerProfile: {
            summary: '',
            suitableLanes: [],
            executionStyle: [],
            hiringTriggers: [],
            blockers: [],
          },
          futureBranches: [],
          eventOutlook: [
            {
              key: 'careerEntry',
              label: 'Career Entry',
              domain: 'career',
              status: 'open',
              readiness: 78,
              bestWindow: '1-3m',
              summary: 'Entry is open if the role is clearly defined.',
              entryConditions: ['Role scope is clear'],
              abortConditions: ['Cash pressure spikes'],
              nextMove: 'Shortlist two roles first.',
            },
          ],
          uncertaintyEnvelope: {
            summary: '',
            reliableAreas: [],
            conditionalAreas: [],
            unresolvedAreas: [],
          },
          evidenceLedger: {
            topClaimIds: [],
            topSignalIds: [],
            topPatternIds: [],
            topScenarioIds: [],
            topDecisionId: null,
            topDecisionLabel: null,
            coherenceNotes: [],
            contradictionFlags: [],
          },
        },
      } as any,
    })

    expect(view.surfaceCards.find((card) => card.key === 'action')?.summary).toContain(
      'Submit two targeted applications'
    )
    expect(view.surfaceCards.find((card) => card.key === 'risk')?.summary).toContain(
      'Lower overwork risk first'
    )
    expect(view.surfaceCards.find((card) => card.key === 'branch')?.summary).toContain(
      'Structured roles open first'
    )
    expect(view.daySummary.summary).toContain('This is a career-entry phase')
    expect(view.recommendedActions.join(' ')).toContain('Submit two targeted applications')
  })
})
