import type { InterpretationRule } from '../types'

export const RULES_TODAY: InterpretationRule[] = [
  // ═══════════════════════════════════════════════════════════
  // 일진(오늘) — scope:'daily'. 짧고 액션 중심 (모바일 "오늘 어때?").
  // section 'today' (cap 4). 일진 십신은 매일 1개라 baseline, 그날 신살/충은
  // 있을 때만 더 얹힘. signalLayer:['daily'] 로 그날 신호만 매칭.
  // ═══════════════════════════════════════════════════════════
  {
    id: 'today-siksang',
    scope: 'daily',
    section: 'today',
    priority: 56,
    conditions: { signalSource: 'saju', signalLayer: ['daily'], sibsin: ['식신', '상관'] },
    template: `오늘은 **표현·실행**의 결 — 만든 걸 내보내고, 말·콘텐츠·영업이 잘 먹혀요.`,
    templateEn: `Today leans toward **expression & doing** — ship what you made; talking, content, and sales land well.`,
    themes: ['growth', 'career'],
  },
  {
    id: 'today-jae',
    scope: 'daily',
    section: 'today',
    priority: 57,
    conditions: { signalSource: 'saju', signalLayer: ['daily'], sibsin: ['정재', '편재'] },
    template: `오늘은 **돈·실리 감각**이 좋은 결 — 거래·정산·실속 챙기는 일에 ㄱ.`,
    templateEn: `Today your **money & practicality sense** is sharp — good for deals, settling accounts, securing value.`,
    themes: ['money'],
  },
  {
    id: 'today-gwan',
    scope: 'daily',
    section: 'today',
    priority: 56,
    conditions: { signalSource: 'saju', signalLayer: ['daily'], sibsin: ['정관'] },
    template: `오늘은 **책임·공식 일**에 집중 좋은 결 — 보고·결재·약속 처리에 ㄱ.`,
    templateEn: `Today suits **responsibility & official matters** — reports, approvals, keeping commitments.`,
    themes: ['career'],
  },
  {
    // 편관(칠살)은 정관과 강도가 달라 분리 — 추진력 ↔ 압박·충돌의 양면.
    id: 'today-pyeongwan',
    scope: 'daily',
    section: 'today',
    priority: 58,
    conditions: { signalSource: 'saju', signalLayer: ['daily'], sibsin: ['편관'] },
    template: `오늘은 **압박·도전의 결** — 마감·강한 일엔 추진력이 붙지만, 충돌·과부하·욱하는 결정은 한 박자 점검.`,
    templateEn: `Today brings **pressure & challenge** — drive for deadlines and hard tasks, but check clashes, overload, and snap decisions.`,
    themes: ['career', 'health'],
  },
  {
    id: 'today-in',
    scope: 'daily',
    section: 'today',
    priority: 55,
    conditions: { signalSource: 'saju', signalLayer: ['daily'], sibsin: ['정인', '편인'] },
    template: `오늘은 **배우고 받아들이는** 결 — 무리한 추진보다 공부·정리·재충전이 맞아요.`,
    templateEn: `Today is for **learning & taking in** — study, organising, and recharging fit better than pushing hard.`,
    themes: ['growth', 'health'],
  },
  {
    id: 'today-bigyeop',
    scope: 'daily',
    section: 'today',
    priority: 55,
    conditions: { signalSource: 'saju', signalLayer: ['daily'], sibsin: ['비견', '겁재'] },
    template: `오늘은 **추진력·자기주장**이 올라오는 결 — 밀어붙이기 좋되 고집·지출은 한 박자 점검.`,
    templateEn: `Today **drive & self-assertion** rise — good to push, but check stubbornness and spending a beat.`,
    themes: ['growth'],
  },
  {
    id: 'today-cheoneul',
    scope: 'daily',
    section: 'today',
    priority: 68,
    conditions: { signalSource: 'saju', signalLayer: ['daily'], shinsalName: ['천을귀인'] },
    template: `오늘은 **귀인의 날** — 부탁·면담·중요한 연락에 우호적. 미뤘던 사람에게 먼저 ㄱ.`,
    templateEn: `Today is a **"helper" day** — favourable for asking, meetings, key messages. Reach out first to someone you'd put off.`,
    themes: ['career', 'health'],
  },
  {
    id: 'today-dohwa',
    scope: 'daily',
    section: 'today',
    priority: 66,
    conditions: { signalSource: 'saju', signalLayer: ['daily'], shinsalName: ['도화', '홍염살'] },
    template: `오늘은 **매력·인연의 날** — 만남·소개 자리·연락 시도에 좋은 결.`,
    templateEn: `Today is a **charm & connection day** — good for meetups, introductions, reaching out.`,
    themes: ['love'],
  },
  {
    id: 'today-yeokma',
    scope: 'daily',
    section: 'today',
    priority: 64,
    conditions: { signalSource: 'saju', signalLayer: ['daily'], shinsalName: ['역마', '지살'] },
    template: `오늘은 **이동·변화의 날** — 출장·여행·새 시도·자리 옮기기에 우호적.`,
    templateEn: `Today is a **movement & change day** — good for travel, trips, new attempts, switching things up.`,
    themes: ['growth', 'career'],
  },
  {
    id: 'today-hwagae',
    scope: 'daily',
    section: 'today',
    priority: 62,
    conditions: { signalSource: 'saju', signalLayer: ['daily'], shinsalName: ['화개', '천문성'] },
    template: `오늘은 **사색·창작·혼자 시간**에 좋은 결 — 깊이 파고드는 작업이 잘 돼요.`,
    templateEn: `Today suits **reflection, creativity, and solo time** — deep, focused work flows.`,
    themes: ['growth'],
  },
  {
    id: 'today-chung',
    scope: 'daily',
    section: 'today',
    priority: 67,
    conditions: { signalSource: 'saju', signalKinds: ['hyeongchung'], maxPolarity: -1 },
    template: `오늘은 **부딪힘 주의** — 큰 결정·충돌·무리한 강행은 피하고 한 박자 쉬어가기.`,
    templateEn: `Today, **watch for friction** — avoid big decisions, clashes, and forcing things; take a beat.`,
    themes: ['health'],
  },
  // ── 일진 그리드 보강: 도메인 × (주의/전환/상승) ──
  // 트리거는 scripts/probe 로 daily 레이어에 실재함을 확인한 신살/충합만 사용
  // (죽은 룰 방지). section 'today'(cap 4) — 그날 뜬 신호 중 우선순위 상위 4개
  // 노출. 기존 sibsin(에너지)·길신(긍정)·충(주의)에 도메인별 주의/전환/상승을 채움.
  {
    id: 'today-geopsal',
    scope: 'daily',
    section: 'today',
    priority: 63,
    conditions: { signalSource: 'saju', signalLayer: ['daily'], shinsalName: ['겁살'] },
    template: `오늘은 **재물·도난 주의** — 큰 지출·투자·보증·빌려주기는 한 박자 미루고 지갑·계정 단속.`,
    templateEn: `Today, **guard money** — postpone big spending, investing, guarantees, and lending; mind wallet and accounts.`,
    themes: ['money'],
  },
  {
    id: 'today-mangsin',
    scope: 'daily',
    section: 'today',
    priority: 62,
    conditions: {
      signalSource: 'saju',
      signalLayer: ['daily'],
      shinsalName: ['망신', '재살', '천살'],
    },
    template: `오늘은 **구설·관재 주의** — 말실수·서류·법적인 일은 두 번 확인하고, 무리한 노출은 자제.`,
    templateEn: `Today, **watch for gossip & legal/admin snags** — double-check words, documents, contracts; avoid overexposure.`,
    themes: ['career'],
  },
  {
    id: 'today-wonjin',
    scope: 'daily',
    section: 'today',
    priority: 62,
    conditions: { signalSource: 'saju', signalLayer: ['daily'], shinsalName: ['원진'] },
    template: `오늘은 **가까운 사이 신경전 주의** — 사소한 말이 오해로 번지기 쉬워요. 예민한 대화는 내일로.`,
    templateEn: `Today, **friction with close ones** — small words spark misunderstanding; save touchy talks for tomorrow.`,
    themes: ['love'],
  },
  {
    id: 'today-yangin',
    scope: 'daily',
    section: 'today',
    priority: 64,
    conditions: {
      signalSource: 'saju',
      signalLayer: ['daily'],
      shinsalName: ['양인', '현침', '괴강'],
    },
    template: `오늘은 **몸·안전 조심** — 날붙이·운전·과격한 운동·과로 주의. 속도 낮추고 무리 금물.`,
    templateEn: `Today, **mind body & safety** — careful with blades, driving, intense exercise, overwork; slow down.`,
    themes: ['health'],
  },
  {
    id: 'today-gwimun',
    scope: 'daily',
    section: 'today',
    priority: 60,
    conditions: { signalSource: 'saju', signalLayer: ['daily'], shinsalName: ['귀문관'] },
    template: `오늘은 **마음이 예민한 결** — 불안·잡생각·수면 흔들림. 자극 줄이고 가벼운 산책·정리로 가라앉히기.`,
    templateEn: `Today feels **mentally sensitive** — anxiety, racing thoughts, restless sleep; cut stimulation, walk it off.`,
    themes: ['health', 'growth'],
  },
  {
    id: 'today-yukhae',
    scope: 'daily',
    section: 'today',
    priority: 60,
    conditions: { signalSource: 'saju', signalLayer: ['daily'], shinsalName: ['육해', '월살'] },
    template: `오늘은 **막힘·지연이 끼는 결** — 한 번에 안 풀릴 수 있어요. 새로 벌이기보다 점검·마무리에 ㄱ.`,
    templateEn: `Today, **friction & delays** — things may stall; favour checking and wrapping up over starting new.`,
    themes: ['career', 'growth'],
  },
  {
    id: 'today-gongmang',
    scope: 'daily',
    section: 'today',
    priority: 61,
    conditions: { signalSource: 'saju', signalLayer: ['daily'], shinsalName: ['공망'] },
    template: `오늘은 **비움·정리의 결** — 새 계약·시작은 한 박자 미루고, 버리기·청소·리셋에 더 맞아요.`,
    templateEn: `Today is for **emptying & resetting** — postpone new deals/launches; better for clearing, cleaning, a reset.`,
    themes: ['growth'],
  },
  {
    id: 'today-geumyeo',
    scope: 'daily',
    section: 'today',
    priority: 62,
    conditions: { signalSource: 'saju', signalLayer: ['daily'], shinsalName: ['금여성', '반안'] },
    template: `오늘은 **안정·재물 운이 받쳐주는 결** — 자산 정리·큰 거래·자리 잡는 일에 우호적.`,
    templateEn: `Today, **stability & wealth back you** — good for organising assets, big deals, settling into place.`,
    themes: ['money'],
  },
  {
    id: 'today-taegeuk',
    scope: 'daily',
    section: 'today',
    priority: 65,
    conditions: {
      signalSource: 'saju',
      signalLayer: ['daily'],
      shinsalName: ['태극귀인', '천덕귀인', '월덕귀인', '천주귀인'],
    },
    template: `오늘은 **하늘이 돕는 결** — 공식 일·시험·평가·중요한 부탁에 보이지 않는 백업이 들어와요.`,
    templateEn: `Today **fortune backs you** — official matters, exams, evaluations, and key requests get unseen support.`,
    themes: ['career'],
  },
  {
    id: 'today-hakdang',
    scope: 'daily',
    section: 'today',
    priority: 63,
    conditions: {
      signalSource: 'saju',
      signalLayer: ['daily'],
      shinsalName: ['학당귀인', '문창', '문곡'],
    },
    template: `오늘은 **머리가 맑은 결** — 공부·시험·자격·집필·기획이 잘 풀려요. 인풋·아웃풋 둘 다 ㄱ.`,
    templateEn: `Today your **mind is sharp** — study, exams, certifications, writing, planning flow; input and output both.`,
    themes: ['growth'],
  },
  {
    id: 'today-cheonui',
    scope: 'daily',
    section: 'today',
    priority: 61,
    conditions: { signalSource: 'saju', signalLayer: ['daily'], shinsalName: ['천의성'] },
    template: `오늘은 **몸 돌보기 좋은 결** — 검진·치료·상담·약 챙기기·루틴 정비에 우호적.`,
    templateEn: `Today suits **caring for your body** — checkups, treatment, counselling, meds, fixing routines.`,
    themes: ['health'],
  },
  {
    id: 'today-wangji',
    scope: 'daily',
    section: 'today',
    priority: 60,
    conditions: {
      signalSource: 'saju',
      signalLayer: ['daily'],
      shinsalName: ['건록', '제왕', '장성'],
    },
    template: `오늘은 **기세가 오르는 결** — 주도권 잡고 밀어붙이기 좋아요. 발표·승부·자기 어필에 ㄱ.`,
    templateEn: `Today your **momentum rises** — good to lead and push; presentations, contests, self-promotion.`,
    themes: ['career', 'growth'],
  },
  {
    id: 'astro-solar-return',
    scope: 'monthly',
    section: 'transit',
    priority: 72,
    conditions: { signalSource: 'astro', signalKinds: ['solar-return'] },
    template:
      `**Solar Return** (태양 회귀) — 새 1년 사이클 시작. ` +
      `이 차트의 ASC·MC sign이 한 해 전체 톤을 만들어요.`,
    templateEn:
      `**Solar Return** — a new yearly cycle begins. ` +
      `The ASC and MC signs of this chart set the tone for the whole year.`,
    themes: ['growth'],
  },
  {
    id: 'astro-lunar-return',
    scope: 'monthly',
    section: 'transit',
    priority: 60,
    conditions: { signalSource: 'astro', signalKinds: ['lunar-return'] },
    template:
      `**Lunar Return** (달 회귀) — 한 달 정서 사이클 시작. ` +
      `이번 달 정서·관계·일상 톤이 이 차트에 담겨요.`,
    templateEn:
      `**Lunar Return** — a one-month emotional cycle begins. ` +
      `The tone of this month's feelings, relationships, and daily life is carried in this chart.`,
    themes: ['love', 'growth'],
  },
  {
    id: 'astro-progressed-moon',
    scope: 'monthly',
    section: 'transit',
    priority: 70,
    conditions: { signalSource: 'astro', signalKinds: ['progressed-moon'] },
    template:
      `**진행 달 흐름의 결** — 28년 정서 사이클에서 당신에게 ` +
      `걸리는 시기. 정서·내면 변화가 자연스럽게 일어나요.`,
    templateEn:
      `**Progressed Moon phase** — a stretch of the 28-year emotional cycle ` +
      `that lands on your chart. Emotional and inner shifts happen naturally.`,
    themes: ['love', 'growth'],
  },

]
