/**
 * Korean translations for major cities
 */
export const CITY_NAME_KR: Record<string, string> = {
  // South Korea
  Seoul: '서울',
  Busan: '부산',
  Incheon: '인천',
  Daegu: '대구',
  Daejeon: '대전',
  Gwangju: '광주',
  Ulsan: '울산',
  Suwon: '수원',
  Changwon: '창원',
  Goyang: '고양',
  Yongin: '용인',
  Seongnam: '성남',
  Cheongju: '청주',
  Jeonju: '전주',
  Ansan: '안산',
  Cheonan: '천안',
  Namyangju: '남양주',
  Pohang: '포항',
  Jeju: '제주',
  Gimhae: '김해',
  Jinju: '진주',
  Iksan: '익산',
  Pyeongtaek: '평택',
  Uijeongbu: '의정부',
  Siheung: '시흥',
  Paju: '파주',
  Gimpo: '김포',
  Bucheon: '부천',
  Anyang: '안양',
  Hwaseong: '화성',
  Gwangmyeong: '광명',
  Hanam: '하남',
  Osan: '오산',
  Yangju: '양주',
  Icheon: '이천',
  Gunpo: '군포',
  Uiwang: '의왕',
  Yangsan: '양산',
  Gumi: '구미',
  Mokpo: '목포',
  Wonju: '원주',
  Chuncheon: '춘천',
  Gangneung: '강릉',
  Gyeongju: '경주',
  Andong: '안동',
  Gimcheon: '김천',
  Geoje: '거제',
  Tongyeong: '통영',
  Sacheon: '사천',
  Yeosu: '여수',
  Suncheon: '순천',
  Gwangyang: '광양',
  Naju: '나주',
  Gongju: '공주',
  Seosan: '서산',
  Asan: '아산',
  Nonsan: '논산',
  Boryeong: '보령',
  Sejong: '세종',

  // Japan
  Tokyo: '도쿄',
  Osaka: '오사카',
  Kyoto: '교토',
  Yokohama: '요코하마',
  Nagoya: '나고야',
  Sapporo: '삿포로',
  Fukuoka: '후쿠오카',
  Kobe: '고베',
  Hiroshima: '히로시마',
  Sendai: '센다이',
  Nara: '나라',
  Kawasaki: '가와사키',
  Saitama: '사이타마',
  Chiba: '치바',
  Kitakyushu: '기타큐슈',
  Kumamoto: '구마모토',
  Okayama: '오카야마',
  Niigata: '니가타',
  Hamamatsu: '하마마쓰',
  Shizuoka: '시즈오카',
  Kagoshima: '가고시마',

  // China
  Beijing: '베이징',
  Shanghai: '상하이',
  Guangzhou: '광저우',
  Shenzhen: '선전',
  Chengdu: '청두',
  Chongqing: '충칭',
  Tianjin: '톈진',
  Wuhan: '우한',
  Hangzhou: '항저우',
  "Xi'an": '시안',
  Nanjing: '난징',
  Qingdao: '칭다오',
  Dalian: '다롄',
  Harbin: '하얼빈',
  Suzhou: '쑤저우',
  Dongguan: '둥관',
  Changsha: '창사',
  Shenyang: '선양',
  Zhengzhou: '정저우',
  Xiamen: '샤먼',
  Jinan: '지난',
  Changchun: '창춘',
  Shijiazhuang: '스자좡',
  Hefei: '허페이',
  Kunming: '쿤밍',
  Fuzhou: '푸저우',
  Nanchang: '난창',
  Guiyang: '구이양',
  Taiyuan: '타이위안',
  Lanzhou: '란저우',
  Urumqi: '우루무치',

  // Taiwan
  Taipei: '타이페이',
  Kaohsiung: '가오슝',
  Taichung: '타이중',
  Tainan: '타이난',

  // Hong Kong & Macau
  'Hong Kong': '홍콩',
  Macau: '마카오',

  // Southeast Asia
  Singapore: '싱가포르',
  Bangkok: '방콕',
  Manila: '마닐라',
  Hanoi: '하노이',
  'Ho Chi Minh City': '호치민',
  Jakarta: '자카르타',
  'Kuala Lumpur': '쿠알라룸푸르',
  Yangon: '양곤',
  'Phnom Penh': '프놈펜',
  Vientiane: '비엔티안',
  Phuket: '푸켓',
  Pattaya: '파타야',
  'Chiang Mai': '치앙마이',
  Penang: '페낭',
  'Johor Bahru': '조호르바루',
  Cebu: '세부',
  Davao: '다바오',
  Bali: '발리',
  Surabaya: '수라바야',
  Bandung: '반둥',
  Medan: '메단',

  // United States
  'New York': '뉴욕',
  'Los Angeles': '로스앤젤레스',
  Chicago: '시카고',
  Houston: '휴스턴',
  Phoenix: '피닉스',
  Philadelphia: '필라델피아',
  'San Antonio': '샌안토니오',
  'San Diego': '샌디에이고',
  Dallas: '댈러스',
  'San Jose': '산호세',
  Austin: '오스틴',
  Jacksonville: '잭슨빌',
  'San Francisco': '샌프란시스코',
  Seattle: '시애틀',
  Denver: '덴버',
  Washington: '워싱턴',
  Boston: '보스턴',
  'Las Vegas': '라스베이거스',
  Miami: '마이애미',
  Atlanta: '애틀랜타',
  Portland: '포틀랜드',
  Nashville: '내슈빌',
  Detroit: '디트로이트',
  Minneapolis: '미니애폴리스',
  Tampa: '탬파',
  Orlando: '올랜도',
  Cleveland: '클리블랜드',
  Pittsburgh: '피츠버그',
  Cincinnati: '신시내티',
  'Kansas City': '캔자스시티',
  Indianapolis: '인디애나폴리스',
  Columbus: '콜럼버스',
  Charlotte: '샬럿',
  Raleigh: '롤리',
  'Salt Lake City': '솔트레이크시티',
  'New Orleans': '뉴올리언스',
  Milwaukee: '밀워키',
  Albuquerque: '앨버커키',
  Tucson: '투손',
  Fresno: '프레즈노',
  Sacramento: '새크라멘토',
  'Long Beach': '롱비치',
  Oakland: '오클랜드',
  Omaha: '오마하',

  // Canada
  Toronto: '토론토',
  Montreal: '몬트리올',
  Vancouver: '밴쿠버',
  Calgary: '캘거리',
  Edmonton: '에드먼턴',
  Ottawa: '오타와',
  Quebec: '퀘벡',

  // United Kingdom
  London: '런던',
  Manchester: '맨체스터',
  Birmingham: '버밍엄',
  Liverpool: '리버풀',
  Edinburgh: '에든버러',
  Glasgow: '글래스고',
  Bristol: '브리스톨',
  Leeds: '리즈',
  Sheffield: '셰필드',
  Newcastle: '뉴캐슬',
  Nottingham: '노팅엄',
  Southampton: '사우샘프턴',
  Leicester: '레스터',
  Cambridge: '케임브리지',
  Oxford: '옥스퍼드',
  Brighton: '브라이튼',

  // Europe
  Paris: '파리',
  Berlin: '베를린',
  Madrid: '마드리드',
  Rome: '로마',
  Amsterdam: '암스테르담',
  Vienna: '빈',
  Brussels: '브뤼셀',
  Barcelona: '바르셀로나',
  Munich: '뮌헨',
  Milan: '밀라노',
  Prague: '프라하',
  Budapest: '부다페스트',
  Warsaw: '바르샤바',
  Copenhagen: '코펜하겐',
  Stockholm: '스톡홀름',
  Oslo: '오슬로',
  Helsinki: '헬싱키',
  Athens: '아테네',
  Lisbon: '리스본',
  Dublin: '더블린',
  Zurich: '취리히',
  Geneva: '제네바',
  Marseille: '마르세유',
  Lyon: '리옹',
  Toulouse: '툴루즈',
  Nice: '니스',
  Bordeaux: '보르도',
  Hamburg: '함부르크',
  Frankfurt: '프랑크푸르트',
  Cologne: '쾰른',
  Stuttgart: '슈투트가르트',
  Düsseldorf: '뒤셀도르프',
  Dortmund: '도르트문트',
  Essen: '에센',
  Leipzig: '라이프치히',
  Dresden: '드레스덴',
  Hanover: '하노버',
  Nuremberg: '뉘른베르크',
  Naples: '나폴리',
  Turin: '토리노',
  Palermo: '팔레르모',
  Genoa: '제노바',
  Bologna: '볼로냐',
  Florence: '피렌체',
  Venice: '베니스',
  Verona: '베로나',
  Valencia: '발렌시아',
  Seville: '세비야',
  Zaragoza: '사라고사',
  Malaga: '말라가',
  Bilbao: '빌바오',
  Rotterdam: '로테르담',
  'The Hague': '헤이그',
  Utrecht: '위트레흐트',
  Eindhoven: '아인트호번',
  Antwerp: '앤트워프',
  Ghent: '겐트',
  Bruges: '브뤼헤',
  Krakow: '크라쿠프',
  Wroclaw: '브로츠와프',
  Gdansk: '그단스크',
  Bratislava: '브라티슬라바',
  Bucharest: '부쿠레슈티',
  Sofia: '소피아',
  Belgrade: '베오그라드',
  Zagreb: '자그레브',
  Ljubljana: '류블랴나',
  Vilnius: '빌뉴스',
  Riga: '리가',
  Tallinn: '탈린',
  Reykjavik: '레이캬비크',
  Luxembourg: '룩셈부르크',
  Monaco: '모나코',

  // Australia & New Zealand
  Sydney: '시드니',
  Melbourne: '멜버른',
  Brisbane: '브리즈번',
  Perth: '퍼스',
  Adelaide: '애들레이드',
  Auckland: '오클랜드',
  Wellington: '웰링턴',

  // Middle East
  Dubai: '두바이',
  'Abu Dhabi': '아부다비',
  Riyadh: '리야드',
  Jeddah: '제다',
  'Tel Aviv': '텔아비브',
  Jerusalem: '예루살렘',
  Istanbul: '이스탄불',
  Ankara: '앙카라',
  Izmir: '이즈미르',
  Antalya: '안탈리아',
  Bursa: '부르사',
  Doha: '도하',
  'Kuwait City': '쿠웨이트시티',
  Manama: '마나마',
  Muscat: '무스카트',
  Amman: '암만',
  Beirut: '베이루트',
  Damascus: '다마스쿠스',
  Baghdad: '바그다드',
  Tehran: '테헤란',

  // South Asia
  Mumbai: '뭄바이',
  Delhi: '델리',
  Bangalore: '방갈로르',
  Kolkata: '콜카타',
  Chennai: '첸나이',
  Hyderabad: '하이데라바드',
  Karachi: '카라치',
  Lahore: '라호르',
  Islamabad: '이슬라마바드',
  Dhaka: '다카',
  Pune: '푸네',
  Ahmedabad: '아마다바드',
  Jaipur: '자이푸르',
  Lucknow: '러크나우',
  Kanpur: '칸푸르',
  Nagpur: '나그푸르',
  Indore: '인도르',
  Colombo: '콜롬보',
  Kathmandu: '카트만두',

  // South America
  'São Paulo': '상파울루',
  'Rio de Janeiro': '리우데자네이루',
  'Buenos Aires': '부에노스아이레스',
  Lima: '리마',
  Bogotá: '보고타',
  Santiago: '산티아고',
  Caracas: '카라카스',
  Medellín: '메데인',
  Cali: '칼리',
  Barranquilla: '바랑키야',
  Quito: '키토',
  Guayaquil: '과야킬',
  Montevideo: '몬테비데오',
  Asunción: '아순시온',
  'La Paz': '라파스',
  'Santa Cruz': '산타크루스',
  Brasília: '브라질리아',
  Salvador: '살바도르',
  Fortaleza: '포르탈레자',
  'Belo Horizonte': '벨루오리존치',
  Manaus: '마나우스',
  Curitiba: '쿠리치바',
  Recife: '헤시페',
  'Porto Alegre': '포르투알레그리',

  // Africa
  Cairo: '카이로',
  Lagos: '라고스',
  Johannesburg: '요하네스버그',
  'Cape Town': '케이프타운',
  Nairobi: '나이로비',
  Casablanca: '카사블랑카',
  Durban: '더반',
  Pretoria: '프리토리아',
  Alexandria: '알렉산드리아',
  Giza: '기자',
  Luxor: '룩소르',
  'Addis Ababa': '아디스아바바',
  Accra: '아크라',
  Dakar: '다카르',
  Abidjan: '아비장',
  Kinshasa: '킨샤사',
  Luanda: '루안다',
  'Dar es Salaam': '다르에스살람',
  Khartoum: '하르툼',
  Algiers: '알제',
  Tunis: '튀니스',
  Rabat: '라바트',
  Marrakech: '마라케시',
  Tripoli: '트리폴리',

  // Russia
  Moscow: '모스크바',
  'Saint Petersburg': '상트페테르부르크',
  Novosibirsk: '노보시비르스크',
  Vladivostok: '블라디보스토크',
  Yekaterinburg: '예카테린부르크',
  Kazan: '카잔',
  'Nizhny Novgorod': '니즈니노브고로드',
  Chelyabinsk: '첼랴빈스크',
  Samara: '사마라',
  Omsk: '옴스크',
  'Rostov-on-Don': '로스토프나도누',
  Ufa: '우파',
  Krasnoyarsk: '크라스노야르스크',
  Perm: '페름',
  Volgograd: '볼고그라드',
  Voronezh: '보로네시',
  Irkutsk: '이르쿠츠크',
  Khabarovsk: '하바롭스크',

  // Mexico
  'Mexico City': '멕시코시티',
  Guadalajara: '과달라하라',
  Monterrey: '몬테레이',
  Cancún: '칸쿤',
  Puebla: '푸에블라',
  Tijuana: '티후아나',
  León: '레온',
  Juárez: '후아레스',
  Mérida: '메리다',
  Acapulco: '아카풀코',

  // Caribbean
  Havana: '아바나',
  Kingston: '킹스턴',
  'Santo Domingo': '산토도밍고',
  'San Juan': '산후안',
  'Port-au-Prince': '포르토프랭스',
  Nassau: '나소',

  // More South Korea cities
  Sokcho: '속초',
  Donghae: '동해',
  Samcheok: '삼척',
  Taebaek: '태백',
  Hongcheon: '홍천',
  Hoengseong: '횡성',
  Yeongwol: '영월',
  Pyeongchang: '평창',
  Jeongseon: '정선',
  Cheorwon: '철원',
  Hwacheon: '화천',
  Yanggu: '양구',
  Inje: '인제',
  Goseong: '고성',
  Yangyang: '양양',
  Chungju: '충주',
  Jecheon: '제천',
  Danyang: '단양',
  Yesan: '예산',
  Hongseong: '홍성',
  Buyeo: '부여',
  Seocheon: '서천',
  Geumsan: '금산',
  Okcheon: '옥천',
  Yeongdong: '영동',
  Boeun: '보은',
  Goesan: '괴산',
  Eumseong: '음성',
  Jincheon: '진천',
  Jeungpyeong: '증평',
  Gunsan: '군산',
  Gimje: '김제',
  Namwon: '남원',
  Jeongeup: '정읍',
  Buan: '부안',
  Gochang: '고창',
  Muju: '무주',
  'Jinan-gun': '진안',
  Imsil: '임실',
  Sunchang: '순창',
  Wanju: '완주',
  Jangsu: '장수',
  Damyang: '담양',
  Gokseong: '곡성',
  Gurye: '구례',
  Goheung: '고흥',
  Boseong: '보성',
  Hwasun: '화순',
  Jangheung: '장흥',
  Gangjin: '강진',
  Haenam: '해남',
  Yeongam: '영암',
  Muan: '무안',
  Hampyeong: '함평',
  Yeonggwang: '영광',
  Jangseong: '장성',
  Wando: '완도',
  Jindo: '진도',
  Sinan: '신안',
  Sangju: '상주',
  Mungyeong: '문경',
  Yeongju: '영주',
  Yeongcheon: '영천',
  Sangam: '상암',
  Cheongdo: '청도',
  Goryeong: '고령',
  Seongju: '성주',
  Chilgok: '칠곡',
  Yecheon: '예천',
  Bonghwa: '봉화',
  Uljin: '울진',
  Yeongdeok: '영덕',
  Cheongsong: '청송',
  Uiseong: '의성',
  Gunwi: '군위',
  Miryang: '밀양',
  Uiryeong: '의령',
  Haman: '함안',
  Changnyeong: '창녕',
  Namhae: '남해',
  Hadong: '하동',
  Sancheong: '산청',
  Hamyang: '함양',
  Geochang: '거창',
  Hapcheon: '합천',

  // More Japan cities
  Okinawa: '오키나와',
  Naha: '나하',
  Nagasaki: '나가사키',
  Matsuyama: '마쓰야마',
  Kanazawa: '가나자와',
  Nagano: '나가노',
  Utsunomiya: '우쓰노미야',
  Mito: '미토',
  Maebashi: '마에바시',
  Toyama: '도야마',
  Fukui: '후쿠이',
  Kofu: '고후',
  Gifu: '기후',
  Tsu: '쓰',
  Otsu: '오쓰',
  Wakayama: '와카야마',
  Tottori: '돗토리',
  Matsue: '마쓰에',
  Yamaguchi: '야마구치',
  Tokushima: '도쿠시마',
  Takamatsu: '다카마쓰',
  Kochi: '고치',
  Saga: '사가',
  Oita: '오이타',
  Miyazaki: '미야자키',
  Aomori: '아오모리',
  Morioka: '모리오카',
  Akita: '아키타',
  Yamagata: '야마가타',
  Fukushima: '후쿠시마',
  Asahikawa: '아사히카와',
  Hakodate: '하코다테',
  Obihiro: '오비히로',
  Kushiro: '구시로',
  Yokosuka: '요코스카',
  Fujisawa: '후지사와',
  Machida: '마치다',
  Hachioji: '하치오지',
  Kawaguchi: '가와구치',
  Funabashi: '후나바시',
  Ichikawa: '이치카와',
  Kashiwa: '가시와',
  Matsudo: '마쓰도',
  Ichihara: '이치하라',
  Toyohashi: '도요하시',
  Okazaki: '오카자키',
  Toyota: '도요타',
  Ichinomiya: '이치노미야',
  Kasugai: '가스가이',
  Sakai: '사카이',
  Higashiosaka: '히가시오사카',
  Toyonaka: '도요나카',
  Hirakata: '히라카타',
  Takatsuki: '다카쓰키',
  Suita: '스이타',
  Nishinomiya: '니시노미야',
  Amagasaki: '아마가사키',
  Himeji: '히메지',
  Akashi: '아카시',
  Kakogawa: '가코가와',
  Takarazuka: '다카라즈카',
  Kawanishi: '가와니시',
  Itami: '이타미',
  Kurashiki: '구라시키',
  Tsuyama: '쓰야마',
  Fukuyama: '후쿠야마',
  Onomichi: '오노미치',
  Kure: '구레',
  Iwakuni: '이와쿠니',
  Shimonoseki: '시모노세키',
  Ube: '우베',

  // More China cities
  Ningbo: '닝보',
  Wenzhou: '원저우',
  Wuxi: '우시',
  Changzhou: '창저우',
  Nantong: '난통',
  Xuzhou: '쉬저우',
  Yangzhou: '양저우',
  Zhenjiang: '전장',
  Taizhou: '타이저우',
  Yancheng: '옌청',
  Huainan: '화이난',
  Lianyungang: '롄윈강',
  Zibo: '쯔보',
  Yantai: '옌타이',
  Weifang: '웨이팡',
  Jining: '지닝',
  Taian: '타이안',
  Weihai: '웨이하이',
  Rizhao: '르자오',
  Linyi: '린이',
  Dezhou: '더저우',
  Liaocheng: '랴오청',
  Binzhou: '빈저우',
  Heze: '허쩌',
  Zhangjiajie: '장자제',
  Guilin: '구이린',
  Liuzhou: '류저우',
  Nanning: '난닝',
  Beihai: '베이하이',
  Sanya: '싼야',
  Haikou: '하이커우',
  Zhuhai: '주하이',
  Foshan: '포산',
  Zhongshan: '중산',
  Huizhou: '후이저우',
  Jiangmen: '장먼',
  Shantou: '산터우',
  Zhanjiang: '잔장',
  Maoming: '마오밍',
  Zhaoqing: '자오칭',
  Qingyuan: '칭위안',
  Shaoguan: '샤오관',
  Meizhou: '메이저우',
  Chaozhou: '차오저우',
  Jieyang: '제양',
  Yangjiang: '양장',
  Yunfu: '윈푸',
  Heyuan: '허위안',
  Shanwei: '산웨이',
  Baoding: '바오딩',
  Tangshan: '탕산',
  Qinhuangdao: '친황다오',
  Handan: '한단',
  Xingtai: '싱타이',
  Zhangjiakou: '장자커우',
  Chengde: '청더',
  Cangzhou: '창저우',
  Langfang: '랑팡',
  Hengshui: '헝수이',
  Anshan: '안산',
  Fushun: '푸순',
  Benxi: '번시',
  Dandong: '단둥',
  Jinzhou: '진저우',
  Yingkou: '잉커우',
  Fuxin: '푸신',
  Liaoyang: '랴오양',
  Panjin: '판진',
  Tieling: '톄링',
  Chaoyang: '차오양',
  Huludao: '후루다오',
  Jilin: '지린',
  Siping: '쓰핑',
  Liaoyuan: '랴오위안',
  Tonghua: '통화',
  Baishan: '바이산',
  Songyuan: '송위안',
  Baicheng: '바이청',
  Yanbian: '연변',
  Qiqihar: '치치하얼',
  Jixi: '지시',
  Hegang: '허강',
  Shuangyashan: '솽야산',
  Daqing: '다칭',
  Yichun: '이춘',
  Jiamusi: '자무쓰',
  Qitaihe: '치타이허',
  Mudanjiang: '무단장',
  Heihe: '헤이허',
  Suihua: '쑤이화',
  Daxinganling: '다싱안링',

  // More Southeast Asia cities
  'Siem Reap': '시엠립',
  'Luang Prabang': '루앙프라방',
  'Nha Trang': '나트랑',
  'Da Nang': '다낭',
  Hue: '후에',
  Halong: '하롱',
  'Hai Phong': '하이퐁',
  'Can Tho': '껀터',
  'Buon Ma Thuot': '부온마투옷',
  Krabi: '끄라비',
  'Koh Samui': '코사무이',
  'Hua Hin': '후아힌',
  Ayutthaya: '아유타야',
  Sukhothai: '수코타이',
  'Chiang Rai': '치앙라이',
  Pai: '빠이',
  Kanchanaburi: '깐짜나부리',
  'Udon Thani': '우돈타니',
  'Khon Kaen': '콘깬',
  'Nakhon Ratchasima': '나콘라차시마',
  'Hat Yai': '핫야이',
  Songkhla: '송클라',
  'Surat Thani': '수랏타니',
  'Phra Nakhon Si Ayutthaya': '아유타야',
  Melaka: '말라카',
  'George Town': '조지타운',
  Ipoh: '이포',
  'Shah Alam': '샤알람',
  'Petaling Jaya': '프탈링자야',
  'Kota Kinabalu': '코타키나발루',
  Kuching: '쿠칭',
  Langkawi: '랑카위',
  'Cameron Highlands': '카메론하이랜드',
  'Genting Highlands': '겐팅하이랜드',
  Batam: '바탐',
  Bintan: '빈탄',
  Yogyakarta: '욕야카르타',
  Semarang: '스마랑',
  Malang: '말랑',
  Solo: '솔로',
  Makassar: '마카사르',
  Denpasar: '덴파사르',
  Ubud: '우붓',
  Seminyak: '스미냑',
  Kuta: '쿠타',
  Sanur: '사누르',
  Lombok: '롬복',
  'Gili Islands': '길리아일랜드',
  'Labuan Bajo': '라부안바조',
  Boracay: '보라카이',
  Palawan: '팔라완',
  'El Nido': '엘니도',
  Coron: '코론',
  'Puerto Princesa': '푸에르토프린세사',
  Baguio: '바기오',
  Vigan: '비간',
  Iloilo: '일로일로',
  Bacolod: '바콜로드',
  Dumaguete: '두마게테',
  Tagaytay: '따가이따이',
  Subic: '수빅',
  Clark: '클락',
  Angeles: '앙헬레스',

  // More Europe cities
  Salzburg: '잘츠부르크',
  Innsbruck: '인스브루크',
  Graz: '그라츠',
  Linz: '린츠',
  Bern: '베른',
  Basel: '바젤',
  Lausanne: '로잔',
  Lucerne: '루체른',
  Interlaken: '인터라켄',
  Zermatt: '체르마트',
  'St. Moritz': '생모리츠',
  Davos: '다보스',
  Montreux: '몽트뢰',
  Grindelwald: '그린델발트',
  Strasbourg: '스트라스부르',
  Lille: '릴',
  Nantes: '낭트',
  Montpellier: '몽펠리에',
  Cannes: '칸',
  Avignon: '아비뇽',
  'Aix-en-Provence': '엑상프로방스',
  Dijon: '디종',
  Rennes: '렌',
  Reims: '랭스',
  Rouen: '루앙',
  Tours: '투르',
  Grenoble: '그르노블',
  'Saint-Tropez': '생트로페',
  Chamonix: '샤모니',
  Colmar: '콜마르',
  Annecy: '안시',
  Porto: '포르투',
  Faro: '파루',
  Sintra: '신트라',
  Cascais: '카스카이스',
  Coimbra: '코임브라',
  Braga: '브라가',
  Funchal: '푼샬',
  Granada: '그라나다',
  Cordoba: '코르도바',
  Toledo: '톨레도',
  Salamanca: '살라망카',
  'San Sebastian': '산세바스티안',
  Pamplona: '팜플로나',
  Santander: '산탄데르',
  Segovia: '세고비아',
  Alicante: '알리칸테',
  Murcia: '무르시아',
  'Palma de Mallorca': '팔마데마요르카',
  Ibiza: '이비자',
  Menorca: '메노르카',
  Tenerife: '테네리페',
  'Gran Canaria': '그란카나리아',
  Lanzarote: '란사로테',
  Fuerteventura: '푸에르테벤투라',
  Pisa: '피사',
  Siena: '시에나',
  Amalfi: '아말피',
  Positano: '포시타노',
  Sorrento: '소렌토',
  Capri: '카프리',
  Ravello: '라벨로',
  'Cinque Terre': '친퀘테레',
  Portofino: '포르토피노',
  'San Remo': '산레모',
  Como: '코모',
  Bergamo: '베르가모',
  Padua: '파도바',
  Trieste: '트리에스테',
  Ravenna: '라벤나',
  Parma: '파르마',
  Modena: '모데나',
  Rimini: '리미니',
  Perugia: '페루자',
  Assisi: '아시시',
  Orvieto: '오르비에토',
  Matera: '마테라',
  Bari: '바리',
  Lecce: '레체',
  Alberobello: '알베로벨로',
  Taormina: '타오르미나',
  Syracuse: '시라쿠사',
  Catania: '카타니아',
  Agrigento: '아그리젠토',
  Cagliari: '칼리아리',
  Alghero: '알게로',
  Olbia: '올비아',
  Santorini: '산토리니',
  Mykonos: '미코노스',
  Crete: '크레타',
  Rhodes: '로도스',
  Corfu: '코르푸',
  Thessaloniki: '테살로니키',
  Delphi: '델피',
  Meteora: '메테오라',
  Olympia: '올림피아',
  Nafplio: '나플리오',
  Dubrovnik: '두브로브니크',
  Split: '스플리트',
  Zadar: '자다르',
  Pula: '풀라',
  Rovinj: '로빈',
  Plitvice: '플리트비체',
  Hvar: '흐바르',
  Kotor: '코토르',
  Budva: '부드바',
  Mostar: '모스타르',
  Sarajevo: '사라예보',
  Skopje: '스코페',
  Ohrid: '오흐리드',
  Tirana: '티라나',
  Plovdiv: '플로브디프',
  'Veliko Tarnovo': '벨리코타르노보',
  Varna: '바르나',
  Burgas: '부르가스',
  Sibiu: '시비우',
  Brasov: '브라쇼프',
  'Cluj-Napoca': '클루지나포카',
  Timisoara: '티미쇼아라',
  Constanta: '콘스탄타',
  Bran: '브란',
  Sinaia: '시나이아',
  Kyiv: '키이우',
  Lviv: '리비우',
  Odesa: '오데사',
  Minsk: '민스크',
  Tbilisi: '트빌리시',
  Batumi: '바투미',
  Yerevan: '예레반',
  Baku: '바쿠',

  // More Australia & Oceania cities
  'Gold Coast': '골드코스트',
  Cairns: '케언즈',
  Darwin: '다윈',
  Hobart: '호바트',
  Canberra: '캔버라',
  Wollongong: '울릉공',
  Geelong: '질롱',
  Townsville: '타운즈빌',
  'Sunshine Coast': '선샤인코스트',
  'Alice Springs': '앨리스스프링스',
  Uluru: '울루루',
  Christchurch: '크라이스트처치',
  Queenstown: '퀸스타운',
  Rotorua: '로토루아',
  Taupo: '타우포',
  Napier: '네이피어',
  Nelson: '넬슨',
  Dunedin: '더니든',
  Hamilton: '해밀턴',
  'Palmerston North': '파머스턴노스',
  Whangarei: '황가레이',
  Tauranga: '타우랑가',
  'New Plymouth': '뉴플리머스',
  Invercargill: '인버카길',
  'Milford Sound': '밀포드사운드',
  'Franz Josef': '프란츠요제프',
  Fiji: '피지',
  Suva: '수바',
  Nadi: '나디',
  'Port Vila': '포트빌라',
  Noumea: '누메아',
  Apia: '아피아',
  Papeete: '파페에테',
  'Bora Bora': '보라보라',
  Moorea: '모레아',
  Tahiti: '타히티',

  // More Middle East cities
  Sharjah: '샤르자',
  Ajman: '아지만',
  'Ras Al Khaimah': '라스알카이마',
  Fujairah: '푸자이라',
  Mecca: '메카',
  Medina: '메디나',
  Dammam: '담맘',
  Khobar: '코바르',
  Haifa: '하이파',
  Eilat: '에일라트',
  Nazareth: '나사렛',
  Bethlehem: '베들레헴',
  Petra: '페트라',
  Aqaba: '아카바',
  'Wadi Rum': '와디럼',
  'Dead Sea': '사해',
  Bodrum: '보드룸',
  Fethiye: '페티예',
  Marmaris: '마르마리스',
  Kas: '카슈',
  Cappadocia: '카파도키아',
  Pamukkale: '파묵칼레',
  Ephesus: '에페소스',
  Konya: '코니아',
  Gaziantep: '가지안테프',
  Adana: '아다나',
  Trabzon: '트라브존',
  Esfahan: '이스파한',
  Shiraz: '시라즈',
  Tabriz: '타브리즈',
  Mashhad: '마슈하드',
  Yazd: '야즈드',
  Kerman: '케르만',
  Musandam: '무산담',
  Salalah: '살랄라',
  Sur: '수르',

  // More Africa cities
  'Sharm El Sheikh': '샤름엘셰이크',
  Hurghada: '후르가다',
  Aswan: '아스완',
  Dahab: '다합',
  Fez: '페스',
  Tangier: '탕헤르',
  Chefchaouen: '셰프샤우엔',
  Essaouira: '에사우이라',
  Agadir: '아가디르',
  Ouarzazate: '와르자자트',
  Merzouga: '메르주가',
  'Victoria Falls': '빅토리아폭포',
  Livingstone: '리빙스턴',
  Zanzibar: '잔지바르',
  Serengeti: '세렝게티',
  Ngorongoro: '응고롱고로',
  'Masai Mara': '마사이마라',
  Amboseli: '암보셀리',
  Mombasa: '몸바사',
  Diani: '디아니',
  Lamu: '라무',
  Kruger: '크루거',
  'Sun City': '선시티',
  Stellenbosch: '스텔렌보스',
  Franschhoek: '프란슈훅',
  'Garden Route': '가든루트',
  Knysna: '나이즈나',
  'Plettenberg Bay': '플레텐버그베이',
  Hermanus: '허마누스',
  'Port Elizabeth': '포트엘리자베스',
  Windhoek: '빈트후크',
  Swakopmund: '스바코프문트',
  Sossusvlei: '소수스블레이',
  Etosha: '에토샤',
  Victoria: '빅토리아',
  Mahe: '마헤',
  Praslin: '프라슬린',
  'La Digue': '라디게',
  'Port Louis': '포트루이스',
  Antananarivo: '안타나나리보',
  'Nosy Be': '노시베',

  // More US cities
  Honolulu: '호놀룰루',
  Maui: '마우이',
  Kauai: '카우아이',
  Waikiki: '와이키키',
  Hilo: '힐로',
  Kona: '코나',
  Anchorage: '앵커리지',
  Fairbanks: '페어뱅크스',
  Juneau: '주노',
  Baltimore: '볼티모어',
  Richmond: '리치먼드',
  'Virginia Beach': '버지니아비치',
  Norfolk: '노폭',
  Providence: '프로비던스',
  Hartford: '하트퍼드',
  'New Haven': '뉴헤이븐',
  Albany: '올버니',
  Buffalo: '버팔로',
  Rochester: '로체스터',
  'Syracuse, NY': '시라큐스',
  'Jersey City': '저지시티',
  Newark: '뉴어크',
  Trenton: '트렌턴',
  'Atlantic City': '애틀랜틱시티',
  Wilmington: '윌밍턴',
  Charleston: '찰스턴',
  Savannah: '사바나',
  'St. Augustine': '세인트오거스틴',
  'Key West': '키웨스트',
  'Fort Lauderdale': '포트로더데일',
  'West Palm Beach': '웨스트팜비치',
  'Naples, FL': '네이플스',
  Clearwater: '클리어워터',
  'St. Petersburg': '세인트피터즈버그',
  Sarasota: '사라소타',
  Pensacola: '펜사콜라',
  Tallahassee: '탤러해시',
  Gainesville: '게인즈빌',
  'Daytona Beach': '데이토나비치',
  'Birmingham, AL': '버밍엄',
  Montgomery: '몽고메리',
  Mobile: '모빌',
  Jackson: '잭슨',
  Biloxi: '빌럭시',
  'Baton Rouge': '배턴루지',
  Lafayette: '라파예트',
  Shreveport: '슈리브포트',
  'Little Rock': '리틀록',
  Memphis: '멤피스',
  Knoxville: '녹스빌',
  Chattanooga: '채터누가',
  Lexington: '렉싱턴',
  Louisville: '루이빌',
  Reno: '리노',
  Boise: '보이시',
  Spokane: '스포캔',
  Tacoma: '타코마',
  Eugene: '유진',
  Salem: '세일럼',
  Bend: '벤드',
  'Santa Fe': '샌타페',
  Taos: '타오스',
  Sedona: '세도나',
  Flagstaff: '플래그스태프',
  Scottsdale: '스코츠데일',
  Mesa: '메사',
  Tempe: '템피',
  'El Paso': '엘파소',
  'Fort Worth': '포트워스',
  Arlington: '알링턴',
  Plano: '플레이노',
  Irving: '어빙',
  'Corpus Christi': '코퍼스크리스티',
  Amarillo: '아마릴로',
  Lubbock: '러벅',
  Waco: '웨이코',
  'Colorado Springs': '콜로라도스프링스',
  Boulder: '볼더',
  'Fort Collins': '포트콜린스',
  Aspen: '아스펜',
  Vail: '베일',
  Telluride: '텔루라이드',
  Breckenridge: '브레켄리지',
  'Park City': '파크시티',
  Moab: '모압',
  'St. George': '세인트조지',

  // More Canada cities
  Winnipeg: '위니펙',
  Halifax: '핼리팩스',
  Saskatoon: '새스커툰',
  Regina: '리자이나',
  'St. Johns': '세인트존스',
  Whistler: '휘슬러',
  Banff: '밴프',
  Jasper: '재스퍼',
  'Lake Louise': '레이크루이스',
  'Niagara Falls': '나이아가라폭포',
  Muskoka: '머스코카',
  'Prince Edward Island': '프린스에드워드아일랜드',
  Charlottetown: '샬럿타운',
  Kelowna: '켈로나',
  Kamloops: '캄룹스',
  Nanaimo: '나나이모',
  Tofino: '토피노',
}

/**
 * Korean translations for country codes
 */
export const COUNTRY_NAME_KR: Record<string, string> = {
  // East Asia
  KR: '한국',
  JP: '일본',
  CN: '중국',
  TW: '대만',
  HK: '홍콩',
  MO: '마카오',
  MN: '몽골',

  // Southeast Asia
  SG: '싱가포르',
  TH: '태국',
  VN: '베트남',
  PH: '필리핀',
  MY: '말레이시아',
  ID: '인도네시아',
  MM: '미얀마',
  KH: '캄보디아',
  LA: '라오스',
  BN: '브루나이',
  TL: '동티모르',

  // South Asia
  IN: '인도',
  PK: '파키스탄',
  BD: '방글라데시',
  LK: '스리랑카',
  NP: '네팔',
  BT: '부탄',
  MV: '몰디브',

  // Central Asia
  KZ: '카자흐스탄',
  UZ: '우즈베키스탄',
  TM: '투르크메니스탄',
  KG: '키르기스스탄',
  TJ: '타지키스탄',

  // Middle East
  AE: '아랍에미리트',
  SA: '사우디아라비아',
  IL: '이스라엘',
  TR: '터키',
  IR: '이란',
  IQ: '이라크',
  SY: '시리아',
  JO: '요르단',
  LB: '레바논',
  KW: '쿠웨이트',
  QA: '카타르',
  BH: '바레인',
  OM: '오만',
  YE: '예멘',
  AF: '아프가니스탄',

  // North America
  US: '미국',
  CA: '캐나다',
  MX: '멕시코',

  // Central America & Caribbean
  GT: '과테말라',
  BZ: '벨리즈',
  HN: '온두라스',
  SV: '엘살바도르',
  NI: '니카라과',
  CR: '코스타리카',
  PA: '파나마',
  CU: '쿠바',
  JM: '자메이카',
  HT: '아이티',
  DO: '도미니카공화국',
  PR: '푸에르토리코',
  BS: '바하마',
  TT: '트리니다드토바고',

  // South America
  BR: '브라질',
  AR: '아르헨티나',
  CL: '칠레',
  PE: '페루',
  CO: '콜롬비아',
  VE: '베네수엘라',
  EC: '에콰도르',
  BO: '볼리비아',
  PY: '파라과이',
  UY: '우루과이',
  GY: '가이아나',
  SR: '수리남',

  // Western Europe
  GB: '영국',
  FR: '프랑스',
  DE: '독일',
  IT: '이탈리아',
  ES: '스페인',
  PT: '포르투갈',
  NL: '네덜란드',
  BE: '벨기에',
  LU: '룩셈부르크',
  CH: '스위스',
  AT: '오스트리아',
  IE: '아일랜드',
  MC: '모나코',
  AD: '안도라',
  LI: '리히텐슈타인',
  SM: '산마리노',
  VA: '바티칸',
  MT: '몰타',

  // Northern Europe
  SE: '스웨덴',
  NO: '노르웨이',
  DK: '덴마크',
  FI: '핀란드',
  IS: '아이슬란드',

  // Eastern Europe
  RU: '러시아',
  PL: '폴란드',
  UA: '우크라이나',
  CZ: '체코',
  HU: '헝가리',
  RO: '루마니아',
  BG: '불가리아',
  SK: '슬로바키아',
  BY: '벨라루스',
  MD: '몰도바',

  // Balkans & Southern Europe
  GR: '그리스',
  RS: '세르비아',
  HR: '크로아티아',
  SI: '슬로베니아',
  BA: '보스니아헤르체고비나',
  MK: '북마케도니아',
  ME: '몬테네그로',
  AL: '알바니아',
  XK: '코소보',
  CY: '키프로스',

  // Baltic States
  EE: '에스토니아',
  LV: '라트비아',
  LT: '리투아니아',

  // Caucasus
  GE: '조지아',
  AM: '아르메니아',
  AZ: '아제르바이잔',

  // Africa
  EG: '이집트',
  ZA: '남아프리카공화국',
  NG: '나이지리아',
  KE: '케냐',
  MA: '모로코',
  DZ: '알제리',
  TN: '튀니지',
  LY: '리비아',
  GH: '가나',
  ET: '에티오피아',
  TZ: '탄자니아',
  UG: '우간다',
  RW: '르완다',
  SN: '세네갈',
  CI: '코트디부아르',
  CM: '카메룬',
  AO: '앙골라',
  ZW: '짐바브웨',
  ZM: '잠비아',
  MW: '말라위',
  MZ: '모잠비크',
  BW: '보츠와나',
  NA: '나미비아',
  MU: '모리셔스',
  MG: '마다가스카르',

  // Oceania
  AU: '호주',
  NZ: '뉴질랜드',
  FJ: '피지',
  PG: '파푸아뉴기니',
  WS: '사모아',
  TO: '통가',
  VU: '바누아투',
  NC: '뉴칼레도니아',
  GU: '괌',
  PF: '프랑스령폴리네시아',
}

/**
 * Full country names for better display
 */
const countryFullNameFallbacks: Record<string, string> = {
  KR: 'South Korea',
  US: 'United States',
  JP: 'Japan',
  CN: 'China',
  GB: 'United Kingdom',
  FR: 'France',
}

const countryDisplayNames =
  typeof Intl !== 'undefined' && 'DisplayNames' in Intl
    ? new Intl.DisplayNames(['en'], { type: 'region' })
    : null

export const COUNTRY_FULL_NAME: Record<string, string> = Object.fromEntries(
  Object.keys(COUNTRY_NAME_KR).map((code) => [
    code,
    countryFullNameFallbacks[code] ?? countryDisplayNames?.of(code) ?? code,
  ])
)
