// Element Mapping Utilities
// Converts between Saju (Five Elements) and Western (Four Elements) systems

import { SIGN_TO_ELEMENT } from '@/lib/destiny-matrix/data/layer1-element-core';
import type { WesternElement } from '@/lib/destiny-matrix/types';
import type { FiveElement } from '@/lib/Saju/types';

/**
 * Maps Saju Five Element to Western Four Element
 * 목/금 → air, 화 → fire, 토 → earth, 수 → water
 */
export function mapSajuElementToWestern(element: string): 'fire' | 'earth' | 'air' | 'water' {
  const mapping: Record<string, 'fire' | 'earth' | 'air' | 'water'> = {
    '목': 'air',    // Wood → Air (growth, expansion)
    '화': 'fire',   // Fire → Fire
    '토': 'earth',  // Earth → Earth
    '금': 'air',    // Metal → Air (sharpness, decisiveness)
    '수': 'water',  // Water → Water
    'wood': 'air',
    'fire': 'fire',
    'earth': 'earth',
    'metal': 'air',
    'water': 'water',
  };
  return mapping[element] || 'earth';
}

/**
 * Maps English element names to Korean (Saju system)
 */
export function mapSajuElementToKo(el: string): FiveElement {
  const map: Record<string, FiveElement> = {
    wood: '목',
    fire: '화',
    earth: '토',
    metal: '금',
    water: '수',
  };
  return map[el] || '토';
}

/**
 * Gets Western element from zodiac sign
 */
export function getWestElementFromSign(sign: string): WesternElement {
  const normalized = sign?.charAt(0).toUpperCase() + sign?.slice(1).toLowerCase();
  return SIGN_TO_ELEMENT[normalized] || 'earth';
}

/**
 * Five Element names in Korean
 */
export const elementNameKo: Record<string, string> = {
  '목': '나무',
  '화': '불',
  '토': '흙',
  '금': '쇠',
  '수': '물',
};

/**
 * Western element names in Korean
 */
export const westElementNameKo: Record<string, string> = {
  'fire': '불',
  'earth': '흙',
  'air': '바람',
  'water': '물',
};

/**
 * Five Element Relationship Functions
 * Used for health analysis and element interactions
 */

/** Gets the element generated by this element (생 관계) */
export function getGeneratedElement(el: FiveElement): FiveElement {
  const cycle: Record<FiveElement, FiveElement> = {
    '목': '화',
    '화': '토',
    '토': '금',
    '금': '수',
    '수': '목',
  };
  return cycle[el] || '토';
}

/** Gets the element controlled/克 by this element (극 관계) */
export function getControlledElement(el: FiveElement): FiveElement {
  const cycle: Record<FiveElement, FiveElement> = {
    '목': '토',
    '화': '금',
    '토': '수',
    '금': '목',
    '수': '화',
  };
  return cycle[el] || '토';
}

/** Gets the element that controls this element (역극 관계) */
export function getControllerElement(el: FiveElement): FiveElement {
  const cycle: Record<FiveElement, FiveElement> = {
    '목': '금',
    '화': '수',
    '토': '목',
    '금': '화',
    '수': '토',
  };
  return cycle[el] || '토';
}

/** Gets the element that generates this element (역생 관계) */
export function getGeneratorElement(el: FiveElement): FiveElement {
  const cycle: Record<FiveElement, FiveElement> = {
    '목': '수',
    '화': '목',
    '토': '화',
    '금': '토',
    '수': '금',
  };
  return cycle[el] || '토';
}
