// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/about" | "/ai-report" | "/api-docs" | "/astrology" | "/blog" | "/calendar" | "/community" | "/compatibility" | "/contact" | "/destiny-counselor" | "/destiny-map" | "/destiny-match" | "/destiny-matrix" | "/destiny-pal" | "/dream" | "/faq" | "/iching" | "/icp" | "/life-prediction" | "/myjourney" | "/notifications" | "/numerology" | "/offline" | "/past-life" | "/personality" | "/premium-reports" | "/pricing" | "/profile" | "/report" | "/saju" | "/success" | "/tarot" | "/test-credit-modal"
type PageRoutes = never
type LayoutRoutes = "/" | "/about" | "/admin" | "/api-docs" | "/astrology" | "/auth" | "/compatibility" | "/contact" | "/destiny-map" | "/destiny-match" | "/dream" | "/faq" | "/iching" | "/icp" | "/life-prediction" | "/myjourney" | "/notifications" | "/numerology" | "/offline" | "/past-life" | "/personality" | "/premium-reports" | "/pricing" | "/profile" | "/saju" | "/success" | "/tarot" | "/test-credit-modal"
type RedirectRoutes = "/[[...path]]" | "/ai-report" | "/blog/numerology-[slug]" | "/blog/numerology-life-path-numbers-explained" | "/premium-reports/result"
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/[[...path]]": { "path"?: string[]; }
  "/about": {}
  "/admin": {}
  "/ai-report": {}
  "/api-docs": {}
  "/astrology": {}
  "/auth": {}
  "/blog": {}
  "/blog/numerology-[slug]": {}
  "/blog/numerology-life-path-numbers-explained": {}
  "/calendar": {}
  "/community": {}
  "/compatibility": {}
  "/contact": {}
  "/destiny-counselor": {}
  "/destiny-map": {}
  "/destiny-match": {}
  "/destiny-matrix": {}
  "/destiny-pal": {}
  "/dream": {}
  "/faq": {}
  "/iching": {}
  "/icp": {}
  "/life-prediction": {}
  "/myjourney": {}
  "/notifications": {}
  "/numerology": {}
  "/offline": {}
  "/past-life": {}
  "/personality": {}
  "/premium-reports": {}
  "/premium-reports/result": {}
  "/pricing": {}
  "/profile": {}
  "/report": {}
  "/saju": {}
  "/success": {}
  "/tarot": {}
  "/test-credit-modal": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/about": never
  "/admin": never
  "/api-docs": never
  "/astrology": never
  "/auth": never
  "/compatibility": never
  "/contact": never
  "/destiny-map": never
  "/destiny-match": never
  "/dream": never
  "/faq": never
  "/iching": never
  "/icp": never
  "/life-prediction": never
  "/myjourney": never
  "/notifications": never
  "/numerology": never
  "/offline": never
  "/past-life": never
  "/personality": never
  "/premium-reports": never
  "/pricing": never
  "/profile": never
  "/saju": never
  "/success": never
  "/tarot": never
  "/test-credit-modal": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
gnin": {}
  "/blog": {}
  "/blog/[slug]": { "slug": string; }
  "/blog/numerology-[slug]": {}
  "/blog/numerology-life-path-numbers-explained": {}
  "/calendar": {}
  "/community": {}
  "/community/matching": {}
  "/community/recommendations": {}
  "/compatibility": {}
  "/compatibility/chat": {}
  "/compatibility/counselor": {}
  "/compatibility/insights": {}
  "/contact": {}
  "/destiny-counselor": {}
  "/destiny-counselor/chat": {}
  "/destiny-map": {}
  "/destiny-map/counselor": {}
  "/destiny-map/matrix": {}
  "/destiny-map/result": {}
  "/destiny-map/theme": {}
  "/destiny-match": {}
  "/destiny-match/matches": {}
  "/destiny-match/setup": {}
  "/destiny-matrix": {}
  "/destiny-matrix/themed-reports": {}
  "/destiny-matrix/viewer": {}
  "/destiny-pal": {}
  "/dream": {}
  "/faq": {}
  "/iching": {}
  "/icp": {}
  "/life-prediction": {}
  "/myjourney": {}
  "/notifications": {}
  "/numerology": {}
  "/offline": {}
  "/past-life": {}
  "/personality": {}
  "/premium-reports": {}
  "/premium-reports/result": {}
  "/pricing": {}
  "/profile": {}
  "/report": {}
  "/saju": {}
  "/success": {}
  "/tarot": {}
  "/test-credit-modal": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/about": never
  "/about/features": never
  "/about/matrix": never
  "/admin": never
  "/api-docs": never
  "/astrology": never
  "/auth": never
  "/compatibility": never
  "/contact": never
  "/destiny-map": never
  "/destiny-map/counselor": never
  "/destiny-match": never
  "/dream": never
  "/faq": never
  "/iching": never
  "/icp": never
  "/life-prediction": never
  "/myjourney": never
  "/notifications": never
  "/numerology": never
  "/offline": never
  "/past-life": never
  "/personality": never
  "/premium-reports": never
  "/pricing": never
  "/profile": never
  "/saju": never
  "/success": never
  "/tarot": never
  "/test-credit-modal": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
xt.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
{}
  "/api/destiny-map/chat-stream": {}
  "/api/destiny-match/block": {}
  "/api/destiny-match/chat": {}
  "/api/destiny-match/discover": {}
  "/api/destiny-match/matches": {}
  "/api/destiny-match/profile": {}
  "/api/destiny-match/report": {}
  "/api/destiny-match/swipe": {}
  "/api/destiny-matrix": {}
  "/api/destiny-matrix/ai-report": {}
  "/api/destiny-matrix/report": {}
  "/api/destiny-matrix/save": {}
  "/api/dream": {}
  "/api/dream/chat": {}
  "/api/dream/chat/save": {}
  "/api/dream/history": {}
  "/api/dream/stream": {}
  "/api/feedback": {}
  "/api/feedback/records": {}
  "/api/fortune": {}
  "/api/health/redis": {}
  "/api/iching/changing-line": {}
  "/api/iching/stream": {}
  "/api/icp": {}
  "/api/icp/analytics": {}
  "/api/latlon-to-timezone": {}
  "/api/lib-health": {}
  "/api/life-prediction": {}
  "/api/life-prediction/advisor-chat": {}
  "/api/life-prediction/analyze-question": {}
  "/api/life-prediction/backend-predict": {}
  "/api/life-prediction/explain-results": {}
  "/api/life-prediction/save": {}
  "/api/life-prediction/save-timing": {}
  "/api/me": {}
  "/api/me/circle": {}
  "/api/me/credits": {}
  "/api/me/history": {}
  "/api/me/premium": {}
  "/api/me/profile": {}
  "/api/me/saju": {}
  "/api/metrics/public": {}
  "/api/metrics/track": {}
  "/api/notifications/send": {}
  "/api/notifications/stream": {}
  "/api/numerology": {}
  "/api/past-life": {}
  "/api/past-life/save": {}
  "/api/persona-memory": {}
  "/api/persona-memory/update-from-chat": {}
  "/api/personality": {}
  "/api/personality-compatibility": {}
  "/api/personality/compatibility/save": {}
  "/api/personality/icp/save": {}
  "/api/precompute-chart": {}
  "/api/push/send": {}
  "/api/push/subscribe": {}
  "/api/readings": {}
  "/api/readings/[id]": { "id": string; }
  "/api/referral/claim": {}
  "/api/referral/create-code": {}
  "/api/referral/link": {}
  "/api/referral/me": {}
  "/api/referral/stats": {}
  "/api/referral/validate": {}
  "/api/reports/[id]": { "id": string; }
  "/api/review/assessment": {}
  "/api/saju": {}
  "/api/saju/chat-stream": {}
  "/api/share/[id]": { "id": string; }
  "/api/share/generate-image": {}
  "/api/stats": {}
  "/api/tarot": {}
  "/api/tarot/analyze-question": {}
  "/api/tarot/chat": {}
  "/api/tarot/chat/stream": {}
  "/api/tarot/couple-reading": {}
  "/api/tarot/couple-reading/[readingId]": { "readingId": string; }
  "/api/tarot/interpret": {}
  "/api/tarot/interpret-stream": {}
  "/api/tarot/interpret/stream": {}
  "/api/tarot/prefetch": {}
  "/api/tarot/question-engine-v2": {}
  "/api/tarot/save": {}
  "/api/tarot/save/[id]": { "id": string; }
  "/api/user/update-birth-info": {}
  "/api/user/upload-photo": {}
  "/api/visitors-today": {}
  "/api/webhook/stripe": {}
  "/api/weekly-fortune": {}
  "/astrology": {}
  "/astrology/counselor": {}
  "/auth": {}
  "/auth/signin": {}
  "/blog": {}
  "/blog/[slug]": { "slug": string; }
  "/blog/numerology-[slug]": {}
  "/blog/numerology-life-path-numbers-explained": {}
  "/calendar": {}
  "/community": {}
  "/community/matching": {}
  "/community/recommendations": {}
  "/compatibility": {}
  "/compatibility/chat": {}
  "/compatibility/counselor": {}
  "/compatibility/insights": {}
  "/contact": {}
  "/destiny-counselor": {}
  "/destiny-counselor/chat": {}
  "/destiny-map": {}
  "/destiny-map/counselor": {}
  "/destiny-map/matrix": {}
  "/destiny-map/result": {}
  "/destiny-map/theme": {}
  "/destiny-match": {}
  "/destiny-match/chat/[connectionId]": { "connectionId": string; }
  "/destiny-match/matches": {}
  "/destiny-match/setup": {}
  "/destiny-matrix": {}
  "/destiny-matrix/themed-reports": {}
  "/destiny-matrix/viewer": {}
  "/destiny-pal": {}
  "/dream": {}
  "/faq": {}
  "/iching": {}
  "/icp": {}
  "/icp/quiz": {}
  "/icp/result": {}
  "/life-prediction": {}
  "/life-prediction/result": {}
  "/myjourney": {}
  "/myjourney/circle": {}
  "/myjourney/history": {}
  "/notifications": {}
  "/numerology": {}
  "/offline": {}
  "/past-life": {}
  "/personality": {}
  "/personality/combined": {}
  "/personality/compatibility": {}
  "/personality/quiz": {}
  "/personality/result": {}
  "/personality/select": {}
  "/policy/privacy": {}
  "/policy/refund": {}
  "/policy/terms": {}
  "/premium-reports": {}
  "/premium-reports/comprehensive": {}
  "/premium-reports/result": {}
  "/premium-reports/result/[id]": { "id": string; }
  "/premium-reports/themed": {}
  "/premium-reports/timing": {}
  "/pricing": {}
  "/profile": {}
  "/report": {}
  "/saju": {}
  "/saju/counselor": {}
  "/shared/[id]": { "id": string; }
  "/success": {}
  "/tarot": {}
  "/tarot/[categoryName]": { "categoryName": string; }
  "/tarot/[categoryName]/[spreadId]": { "categoryName": string; "spreadId": string; }
  "/tarot/couple": {}
  "/tarot/couple/[readingId]": { "readingId": string; }
  "/tarot/history": {}
  "/test-credit-modal": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/about": never
  "/about/features": never
  "/about/matrix": never
  "/admin": never
  "/api-docs": never
  "/astrology": never
  "/auth": never
  "/compatibility": never
  "/contact": never
  "/destiny-map": never
  "/destiny-map/counselor": never
  "/destiny-match": never
  "/dream": never
  "/faq": never
  "/iching": never
  "/icp": never
  "/life-prediction": never
  "/myjourney": never
  "/notifications": never
  "/numerology": never
  "/offline": never
  "/past-life": never
  "/personality": never
  "/policy/privacy": never
  "/policy/refund": never
  "/policy/terms": never
  "/premium-reports": never
  "/pricing": never
  "/profile": never
  "/saju": never
  "/success": never
  "/tarot": never
  "/test-credit-modal": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
