// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../../src/app/(main)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about">> = Specific
  const handler = {} as typeof import("../../../src/app/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/ai-report/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ai-report">> = Specific
  const handler = {} as typeof import("../../../src/app/ai-report/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api-docs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/api-docs">> = Specific
  const handler = {} as typeof import("../../../src/app/api-docs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/astrology/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/astrology">> = Specific
  const handler = {} as typeof import("../../../src/app/astrology/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/blog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog">> = Specific
  const handler = {} as typeof import("../../../src/app/blog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/calendar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/calendar">> = Specific
  const handler = {} as typeof import("../../../src/app/calendar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/community/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/community">> = Specific
  const handler = {} as typeof import("../../../src/app/community/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/compatibility/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/compatibility">> = Specific
  const handler = {} as typeof import("../../../src/app/compatibility/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contact">> = Specific
  const handler = {} as typeof import("../../../src/app/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/destiny-counselor/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/destiny-counselor">> = Specific
  const handler = {} as typeof import("../../../src/app/destiny-counselor/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/destiny-map/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/destiny-map">> = Specific
  const handler = {} as typeof import("../../../src/app/destiny-map/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/destiny-match/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/destiny-match">> = Specific
  const handler = {} as typeof import("../../../src/app/destiny-match/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/destiny-matrix/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/destiny-matrix">> = Specific
  const handler = {} as typeof import("../../../src/app/destiny-matrix/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/destiny-pal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/destiny-pal">> = Specific
  const handler = {} as typeof import("../../../src/app/destiny-pal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dream/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dream">> = Specific
  const handler = {} as typeof import("../../../src/app/dream/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/faq/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/faq">> = Specific
  const handler = {} as typeof import("../../../src/app/faq/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/iching/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/iching">> = Specific
  const handler = {} as typeof import("../../../src/app/iching/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/icp/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/icp">> = Specific
  const handler = {} as typeof import("../../../src/app/icp/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/life-prediction/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/life-prediction">> = Specific
  const handler = {} as typeof import("../../../src/app/life-prediction/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/myjourney/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/myjourney">> = Specific
  const handler = {} as typeof import("../../../src/app/myjourney/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/notifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/notifications">> = Specific
  const handler = {} as typeof import("../../../src/app/notifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/numerology/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/numerology">> = Specific
  const handler = {} as typeof import("../../../src/app/numerology/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/offline/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/offline">> = Specific
  const handler = {} as typeof import("../../../src/app/offline/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/past-life/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/past-life">> = Specific
  const handler = {} as typeof import("../../../src/app/past-life/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/personality/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/personality">> = Specific
  const handler = {} as typeof import("../../../src/app/personality/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/premium-reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/premium-reports">> = Specific
  const handler = {} as typeof import("../../../src/app/premium-reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/pricing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pricing">> = Specific
  const handler = {} as typeof import("../../../src/app/pricing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile">> = Specific
  const handler = {} as typeof import("../../../src/app/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/report/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/report">> = Specific
  const handler = {} as typeof import("../../../src/app/report/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/saju/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/saju">> = Specific
  const handler = {} as typeof import("../../../src/app/saju/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/success/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/success">> = Specific
  const handler = {} as typeof import("../../../src/app/success/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/tarot/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tarot">> = Specific
  const handler = {} as typeof import("../../../src/app/tarot/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/test-credit-modal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/test-credit-modal">> = Specific
  const handler = {} as typeof import("../../../src/app/test-credit-modal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../../src/app/about/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/about">> = Specific
  const handler = {} as typeof import("../../../src/app/about/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api-docs/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/api-docs">> = Specific
  const handler = {} as typeof import("../../../src/app/api-docs/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/astrology/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/astrology">> = Specific
  const handler = {} as typeof import("../../../src/app/astrology/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/auth/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/auth">> = Specific
  const handler = {} as typeof import("../../../src/app/auth/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/compatibility/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/compatibility">> = Specific
  const handler = {} as typeof import("../../../src/app/compatibility/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/contact/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/contact">> = Specific
  const handler = {} as typeof import("../../../src/app/contact/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/destiny-map/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/destiny-map">> = Specific
  const handler = {} as typeof import("../../../src/app/destiny-map/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/destiny-match/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/destiny-match">> = Specific
  const handler = {} as typeof import("../../../src/app/destiny-match/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dream/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dream">> = Specific
  const handler = {} as typeof import("../../../src/app/dream/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/faq/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/faq">> = Specific
  const handler = {} as typeof import("../../../src/app/faq/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/iching/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/iching">> = Specific
  const handler = {} as typeof import("../../../src/app/iching/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/icp/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/icp">> = Specific
  const handler = {} as typeof import("../../../src/app/icp/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/life-prediction/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/life-prediction">> = Specific
  const handler = {} as typeof import("../../../src/app/life-prediction/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/myjourney/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/myjourney">> = Specific
  const handler = {} as typeof import("../../../src/app/myjourney/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/notifications/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/notifications">> = Specific
  const handler = {} as typeof import("../../../src/app/notifications/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/numerology/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/numerology">> = Specific
  const handler = {} as typeof import("../../../src/app/numerology/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/offline/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/offline">> = Specific
  const handler = {} as typeof import("../../../src/app/offline/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/past-life/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/past-life">> = Specific
  const handler = {} as typeof import("../../../src/app/past-life/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/personality/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/personality">> = Specific
  const handler = {} as typeof import("../../../src/app/personality/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/premium-reports/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/premium-reports">> = Specific
  const handler = {} as typeof import("../../../src/app/premium-reports/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/pricing/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/pricing">> = Specific
  const handler = {} as typeof import("../../../src/app/pricing/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/profile/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/profile">> = Specific
  const handler = {} as typeof import("../../../src/app/profile/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/saju/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/saju">> = Specific
  const handler = {} as typeof import("../../../src/app/saju/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/success/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/success">> = Specific
  const handler = {} as typeof import("../../../src/app/success/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/tarot/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/tarot">> = Specific
  const handler = {} as typeof import("../../../src/app/tarot/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/test-credit-modal/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/test-credit-modal">> = Specific
  const handler = {} as typeof import("../../../src/app/test-credit-modal/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/personality/result/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/personality/result">> = Specific
  const handler = {} as typeof import("../../../src/app/personality/result/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/personality/select/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/personality/select">> = Specific
  const handler = {} as typeof import("../../../src/app/personality/select/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/policy/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/policy/privacy">> = Specific
  const handler = {} as typeof import("../../../src/app/policy/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/policy/refund/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/policy/refund">> = Specific
  const handler = {} as typeof import("../../../src/app/policy/refund/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/policy/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/policy/terms">> = Specific
  const handler = {} as typeof import("../../../src/app/policy/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/premium-reports/comprehensive/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/premium-reports/comprehensive">> = Specific
  const handler = {} as typeof import("../../../src/app/premium-reports/comprehensive/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/premium-reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/premium-reports">> = Specific
  const handler = {} as typeof import("../../../src/app/premium-reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/premium-reports/result/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/premium-reports/result">> = Specific
  const handler = {} as typeof import("../../../src/app/premium-reports/result/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/premium-reports/themed/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/premium-reports/themed">> = Specific
  const handler = {} as typeof import("../../../src/app/premium-reports/themed/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/premium-reports/timing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/premium-reports/timing">> = Specific
  const handler = {} as typeof import("../../../src/app/premium-reports/timing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/pricing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pricing">> = Specific
  const handler = {} as typeof import("../../../src/app/pricing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile">> = Specific
  const handler = {} as typeof import("../../../src/app/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/report/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/report">> = Specific
  const handler = {} as typeof import("../../../src/app/report/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/saju/counselor/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/saju/counselor">> = Specific
  const handler = {} as typeof import("../../../src/app/saju/counselor/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/saju/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/saju">> = Specific
  const handler = {} as typeof import("../../../src/app/saju/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/shared/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/shared/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/shared/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/success/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/success">> = Specific
  const handler = {} as typeof import("../../../src/app/success/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/tarot/[categoryName]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tarot/[categoryName]">> = Specific
  const handler = {} as typeof import("../../../src/app/tarot/[categoryName]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/tarot/couple/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tarot/couple">> = Specific
  const handler = {} as typeof import("../../../src/app/tarot/couple/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/tarot/history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tarot/history">> = Specific
  const handler = {} as typeof import("../../../src/app/tarot/history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/tarot/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tarot">> = Specific
  const handler = {} as typeof import("../../../src/app/tarot/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/test-credit-modal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/test-credit-modal">> = Specific
  const handler = {} as typeof import("../../../src/app/test-credit-modal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/astrology/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/astrology">> = Specific
  const handler = {} as typeof import("../../../src/app/api/astrology/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/calendar/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/calendar">> = Specific
  const handler = {} as typeof import("../../../src/app/api/calendar/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/checkout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/checkout">> = Specific
  const handler = {} as typeof import("../../../src/app/api/checkout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/cities/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cities">> = Specific
  const handler = {} as typeof import("../../../src/app/api/cities/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/compatibility/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/compatibility">> = Specific
  const handler = {} as typeof import("../../../src/app/api/compatibility/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/consultation/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/consultation">> = Specific
  const handler = {} as typeof import("../../../src/app/api/consultation/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/content-access/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/content-access">> = Specific
  const handler = {} as typeof import("../../../src/app/api/content-access/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/csp-report/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/csp-report">> = Specific
  const handler = {} as typeof import("../../../src/app/api/csp-report/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/daily-fortune/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/daily-fortune">> = Specific
  const handler = {} as typeof import("../../../src/app/api/daily-fortune/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/dates/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dates">> = Specific
  const handler = {} as typeof import("../../../src/app/api/dates/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/db-ping/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/db-ping">> = Specific
  const handler = {} as typeof import("../../../src/app/api/db-ping/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/destiny-feedback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/destiny-feedback">> = Specific
  const handler = {} as typeof import("../../../src/app/api/destiny-feedback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/destiny-map/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/destiny-map">> = Specific
  const handler = {} as typeof import("../../../src/app/api/destiny-map/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/destiny-matrix/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/destiny-matrix">> = Specific
  const handler = {} as typeof import("../../../src/app/api/destiny-matrix/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/dream/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dream">> = Specific
  const handler = {} as typeof import("../../../src/app/api/dream/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/feedback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/feedback">> = Specific
  const handler = {} as typeof import("../../../src/app/api/feedback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/fortune/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/fortune">> = Specific
  const handler = {} as typeof import("../../../src/app/api/fortune/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/icp/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/icp">> = Specific
  const handler = {} as typeof import("../../../src/app/api/icp/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/latlon-to-timezone/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/latlon-to-timezone">> = Specific
  const handler = {} as typeof import("../../../src/app/api/latlon-to-timezone/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/lib-health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/lib-health">> = Specific
  const handler = {} as typeof import("../../../src/app/api/lib-health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/life-prediction/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/life-prediction">> = Specific
  const handler = {} as typeof import("../../../src/app/api/life-prediction/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/me/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/me">> = Specific
  const handler = {} as typeof import("../../../src/app/api/me/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/numerology/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/numerology">> = Specific
  const handler = {} as typeof import("../../../src/app/api/numerology/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/past-life/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/past-life">> = Specific
  const handler = {} as typeof import("../../../src/app/api/past-life/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/persona-memory/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/persona-memory">> = Specific
  const handler = {} as typeof import("../../../src/app/api/persona-memory/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/personality-compatibility/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/personality-compatibility">> = Specific
  const handler = {} as typeof import("../../../src/app/api/personality-compatibility/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/personality/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/personality">> = Specific
  const handler = {} as typeof import("../../../src/app/api/personality/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/precompute-chart/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/precompute-chart">> = Specific
  const handler = {} as typeof import("../../../src/app/api/precompute-chart/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/readings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/readings">> = Specific
  const handler = {} as typeof import("../../../src/app/api/readings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/saju/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/saju">> = Specific
  const handler = {} as typeof import("../../../src/app/api/saju/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stats">> = Specific
  const handler = {} as typeof import("../../../src/app/api/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/tarot/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tarot">> = Specific
  const handler = {} as typeof import("../../../src/app/api/tarot/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/visitors-today/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/visitors-today">> = Specific
  const handler = {} as typeof import("../../../src/app/api/visitors-today/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/weekly-fortune/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/weekly-fortune">> = Specific
  const handler = {} as typeof import("../../../src/app/api/weekly-fortune/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../src/app/about/features/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/about/features">> = Specific
  const handler = {} as typeof import("../../../src/app/about/features/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/about/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/about">> = Specific
  const handler = {} as typeof import("../../../src/app/about/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/about/matrix/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/about/matrix">> = Specific
  const handler = {} as typeof import("../../../src/app/about/matrix/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api-docs/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/api-docs">> = Specific
  const handler = {} as typeof import("../../../src/app/api-docs/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/astrology/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/astrology">> = Specific
  const handler = {} as typeof import("../../../src/app/astrology/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/auth/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/auth">> = Specific
  const handler = {} as typeof import("../../../src/app/auth/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/compatibility/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/compatibility">> = Specific
  const handler = {} as typeof import("../../../src/app/compatibility/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/contact/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/contact">> = Specific
  const handler = {} as typeof import("../../../src/app/contact/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/destiny-map/counselor/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/destiny-map/counselor">> = Specific
  const handler = {} as typeof import("../../../src/app/destiny-map/counselor/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/destiny-map/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/destiny-map">> = Specific
  const handler = {} as typeof import("../../../src/app/destiny-map/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/destiny-match/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/destiny-match">> = Specific
  const handler = {} as typeof import("../../../src/app/destiny-match/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dream/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dream">> = Specific
  const handler = {} as typeof import("../../../src/app/dream/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/faq/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/faq">> = Specific
  const handler = {} as typeof import("../../../src/app/faq/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/iching/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/iching">> = Specific
  const handler = {} as typeof import("../../../src/app/iching/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/icp/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/icp">> = Specific
  const handler = {} as typeof import("../../../src/app/icp/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/life-prediction/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/life-prediction">> = Specific
  const handler = {} as typeof import("../../../src/app/life-prediction/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/myjourney/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/myjourney">> = Specific
  const handler = {} as typeof import("../../../src/app/myjourney/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/notifications/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/notifications">> = Specific
  const handler = {} as typeof import("../../../src/app/notifications/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/numerology/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/numerology">> = Specific
  const handler = {} as typeof import("../../../src/app/numerology/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/offline/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/offline">> = Specific
  const handler = {} as typeof import("../../../src/app/offline/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/past-life/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/past-life">> = Specific
  const handler = {} as typeof import("../../../src/app/past-life/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/personality/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/personality">> = Specific
  const handler = {} as typeof import("../../../src/app/personality/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/policy/privacy/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/policy/privacy">> = Specific
  const handler = {} as typeof import("../../../src/app/policy/privacy/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/policy/refund/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/policy/refund">> = Specific
  const handler = {} as typeof import("../../../src/app/policy/refund/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/policy/terms/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/policy/terms">> = Specific
  const handler = {} as typeof import("../../../src/app/policy/terms/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/premium-reports/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/premium-reports">> = Specific
  const handler = {} as typeof import("../../../src/app/premium-reports/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/pricing/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/pricing">> = Specific
  const handler = {} as typeof import("../../../src/app/pricing/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/profile/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/profile">> = Specific
  const handler = {} as typeof import("../../../src/app/profile/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/saju/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/saju">> = Specific
  const handler = {} as typeof import("../../../src/app/saju/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/success/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/success">> = Specific
  const handler = {} as typeof import("../../../src/app/success/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/tarot/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/tarot">> = Specific
  const handler = {} as typeof import("../../../src/app/tarot/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/test-credit-modal/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/test-credit-modal">> = Specific
  const handler = {} as typeof import("../../../src/app/test-credit-modal/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
 // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/destiny-match/swipe/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/destiny-match/swipe">> = Specific
  const handler = {} as typeof import("../../../src/app/api/destiny-match/swipe/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/destiny-matrix/ai-report/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/destiny-matrix/ai-report">> = Specific
  const handler = {} as typeof import("../../../src/app/api/destiny-matrix/ai-report/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/destiny-matrix/report/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/destiny-matrix/report">> = Specific
  const handler = {} as typeof import("../../../src/app/api/destiny-matrix/report/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/destiny-matrix/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/destiny-matrix">> = Specific
  const handler = {} as typeof import("../../../src/app/api/destiny-matrix/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/destiny-matrix/save/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/destiny-matrix/save">> = Specific
  const handler = {} as typeof import("../../../src/app/api/destiny-matrix/save/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/dream/chat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dream/chat">> = Specific
  const handler = {} as typeof import("../../../src/app/api/dream/chat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/dream/chat/save/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dream/chat/save">> = Specific
  const handler = {} as typeof import("../../../src/app/api/dream/chat/save/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/dream/history/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dream/history">> = Specific
  const handler = {} as typeof import("../../../src/app/api/dream/history/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/dream/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dream">> = Specific
  const handler = {} as typeof import("../../../src/app/api/dream/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/dream/stream/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dream/stream">> = Specific
  const handler = {} as typeof import("../../../src/app/api/dream/stream/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/feedback/records/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/feedback/records">> = Specific
  const handler = {} as typeof import("../../../src/app/api/feedback/records/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/feedback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/feedback">> = Specific
  const handler = {} as typeof import("../../../src/app/api/feedback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/fortune/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/fortune">> = Specific
  const handler = {} as typeof import("../../../src/app/api/fortune/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/health/redis/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health/redis">> = Specific
  const handler = {} as typeof import("../../../src/app/api/health/redis/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/iching/changing-line/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/iching/changing-line">> = Specific
  const handler = {} as typeof import("../../../src/app/api/iching/changing-line/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/iching/stream/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/iching/stream">> = Specific
  const handler = {} as typeof import("../../../src/app/api/iching/stream/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/icp/analytics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/icp/analytics">> = Specific
  const handler = {} as typeof import("../../../src/app/api/icp/analytics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/icp/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/icp">> = Specific
  const handler = {} as typeof import("../../../src/app/api/icp/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/latlon-to-timezone/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/latlon-to-timezone">> = Specific
  const handler = {} as typeof import("../../../src/app/api/latlon-to-timezone/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/lib-health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/lib-health">> = Specific
  const handler = {} as typeof import("../../../src/app/api/lib-health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/life-prediction/advisor-chat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/life-prediction/advisor-chat">> = Specific
  const handler = {} as typeof import("../../../src/app/api/life-prediction/advisor-chat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/life-prediction/analyze-question/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/life-prediction/analyze-question">> = Specific
  const handler = {} as typeof import("../../../src/app/api/life-prediction/analyze-question/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/life-prediction/backend-predict/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/life-prediction/backend-predict">> = Specific
  const handler = {} as typeof import("../../../src/app/api/life-prediction/backend-predict/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/life-prediction/explain-results/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/life-prediction/explain-results">> = Specific
  const handler = {} as typeof import("../../../src/app/api/life-prediction/explain-results/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/life-prediction/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/life-prediction">> = Specific
  const handler = {} as typeof import("../../../src/app/api/life-prediction/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/life-prediction/save-timing/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/life-prediction/save-timing">> = Specific
  const handler = {} as typeof import("../../../src/app/api/life-prediction/save-timing/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/life-prediction/save/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/life-prediction/save">> = Specific
  const handler = {} as typeof import("../../../src/app/api/life-prediction/save/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/me/circle/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/me/circle">> = Specific
  const handler = {} as typeof import("../../../src/app/api/me/circle/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/me/credits/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/me/credits">> = Specific
  const handler = {} as typeof import("../../../src/app/api/me/credits/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/me/history/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/me/history">> = Specific
  const handler = {} as typeof import("../../../src/app/api/me/history/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/me/premium/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/me/premium">> = Specific
  const handler = {} as typeof import("../../../src/app/api/me/premium/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/me/profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/me/profile">> = Specific
  const handler = {} as typeof import("../../../src/app/api/me/profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/me/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/me">> = Specific
  const handler = {} as typeof import("../../../src/app/api/me/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/me/saju/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/me/saju">> = Specific
  const handler = {} as typeof import("../../../src/app/api/me/saju/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/metrics/public/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/metrics/public">> = Specific
  const handler = {} as typeof import("../../../src/app/api/metrics/public/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/metrics/track/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/metrics/track">> = Specific
  const handler = {} as typeof import("../../../src/app/api/metrics/track/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/notifications/send/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications/send">> = Specific
  const handler = {} as typeof import("../../../src/app/api/notifications/send/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/notifications/stream/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications/stream">> = Specific
  const handler = {} as typeof import("../../../src/app/api/notifications/stream/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/numerology/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/numerology">> = Specific
  const handler = {} as typeof import("../../../src/app/api/numerology/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/past-life/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/past-life">> = Specific
  const handler = {} as typeof import("../../../src/app/api/past-life/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/past-life/save/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/past-life/save">> = Specific
  const handler = {} as typeof import("../../../src/app/api/past-life/save/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/persona-memory/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/persona-memory">> = Specific
  const handler = {} as typeof import("../../../src/app/api/persona-memory/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/persona-memory/update-from-chat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/persona-memory/update-from-chat">> = Specific
  const handler = {} as typeof import("../../../src/app/api/persona-memory/update-from-chat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/personality-compatibility/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/personality-compatibility">> = Specific
  const handler = {} as typeof import("../../../src/app/api/personality-compatibility/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/personality/compatibility/save/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/personality/compatibility/save">> = Specific
  const handler = {} as typeof import("../../../src/app/api/personality/compatibility/save/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/personality/icp/save/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/personality/icp/save">> = Specific
  const handler = {} as typeof import("../../../src/app/api/personality/icp/save/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/personality/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/personality">> = Specific
  const handler = {} as typeof import("../../../src/app/api/personality/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/precompute-chart/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/precompute-chart">> = Specific
  const handler = {} as typeof import("../../../src/app/api/precompute-chart/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/push/send/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/push/send">> = Specific
  const handler = {} as typeof import("../../../src/app/api/push/send/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/push/subscribe/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/push/subscribe">> = Specific
  const handler = {} as typeof import("../../../src/app/api/push/subscribe/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/readings/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/readings/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/readings/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/readings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/readings">> = Specific
  const handler = {} as typeof import("../../../src/app/api/readings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/referral/claim/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/referral/claim">> = Specific
  const handler = {} as typeof import("../../../src/app/api/referral/claim/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/referral/create-code/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/referral/create-code">> = Specific
  const handler = {} as typeof import("../../../src/app/api/referral/create-code/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/referral/link/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/referral/link">> = Specific
  const handler = {} as typeof import("../../../src/app/api/referral/link/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/referral/me/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/referral/me">> = Specific
  const handler = {} as typeof import("../../../src/app/api/referral/me/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/referral/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/referral/stats">> = Specific
  const handler = {} as typeof import("../../../src/app/api/referral/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/referral/validate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/referral/validate">> = Specific
  const handler = {} as typeof import("../../../src/app/api/referral/validate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/reports/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reports/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/reports/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/review/assessment/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/review/assessment">> = Specific
  const handler = {} as typeof import("../../../src/app/api/review/assessment/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/saju/chat-stream/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/saju/chat-stream">> = Specific
  const handler = {} as typeof import("../../../src/app/api/saju/chat-stream/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/saju/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/saju">> = Specific
  const handler = {} as typeof import("../../../src/app/api/saju/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/share/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/share/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/share/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/share/generate-image/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/share/generate-image">> = Specific
  const handler = {} as typeof import("../../../src/app/api/share/generate-image/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stats">> = Specific
  const handler = {} as typeof import("../../../src/app/api/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/tarot/analyze-question/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tarot/analyze-question">> = Specific
  const handler = {} as typeof import("../../../src/app/api/tarot/analyze-question/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/tarot/chat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tarot/chat">> = Specific
  const handler = {} as typeof import("../../../src/app/api/tarot/chat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/tarot/chat/stream/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tarot/chat/stream">> = Specific
  const handler = {} as typeof import("../../../src/app/api/tarot/chat/stream/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/tarot/couple-reading/[readingId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tarot/couple-reading/[readingId]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/tarot/couple-reading/[readingId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/tarot/couple-reading/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tarot/couple-reading">> = Specific
  const handler = {} as typeof import("../../../src/app/api/tarot/couple-reading/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/tarot/interpret-stream/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tarot/interpret-stream">> = Specific
  const handler = {} as typeof import("../../../src/app/api/tarot/interpret-stream/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/tarot/interpret/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tarot/interpret">> = Specific
  const handler = {} as typeof import("../../../src/app/api/tarot/interpret/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/tarot/interpret/stream/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tarot/interpret/stream">> = Specific
  const handler = {} as typeof import("../../../src/app/api/tarot/interpret/stream/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/tarot/prefetch/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tarot/prefetch">> = Specific
  const handler = {} as typeof import("../../../src/app/api/tarot/prefetch/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/tarot/question-engine-v2/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tarot/question-engine-v2">> = Specific
  const handler = {} as typeof import("../../../src/app/api/tarot/question-engine-v2/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/tarot/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tarot">> = Specific
  const handler = {} as typeof import("../../../src/app/api/tarot/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/tarot/save/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tarot/save/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/tarot/save/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/tarot/save/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tarot/save">> = Specific
  const handler = {} as typeof import("../../../src/app/api/tarot/save/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/user/update-birth-info/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user/update-birth-info">> = Specific
  const handler = {} as typeof import("../../../src/app/api/user/update-birth-info/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/user/upload-photo/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user/upload-photo">> = Specific
  const handler = {} as typeof import("../../../src/app/api/user/upload-photo/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/visitors-today/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/visitors-today">> = Specific
  const handler = {} as typeof import("../../../src/app/api/visitors-today/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/webhook/stripe/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhook/stripe">> = Specific
  const handler = {} as typeof import("../../../src/app/api/webhook/stripe/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/weekly-fortune/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/weekly-fortune">> = Specific
  const handler = {} as typeof import("../../../src/app/api/weekly-fortune/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../src/app/about/features/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/about/features">> = Specific
  const handler = {} as typeof import("../../../src/app/about/features/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/about/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/about">> = Specific
  const handler = {} as typeof import("../../../src/app/about/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/about/matrix/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/about/matrix">> = Specific
  const handler = {} as typeof import("../../../src/app/about/matrix/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api-docs/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/api-docs">> = Specific
  const handler = {} as typeof import("../../../src/app/api-docs/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/astrology/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/astrology">> = Specific
  const handler = {} as typeof import("../../../src/app/astrology/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/auth/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/auth">> = Specific
  const handler = {} as typeof import("../../../src/app/auth/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/compatibility/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/compatibility">> = Specific
  const handler = {} as typeof import("../../../src/app/compatibility/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/contact/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/contact">> = Specific
  const handler = {} as typeof import("../../../src/app/contact/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/destiny-map/counselor/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/destiny-map/counselor">> = Specific
  const handler = {} as typeof import("../../../src/app/destiny-map/counselor/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/destiny-map/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/destiny-map">> = Specific
  const handler = {} as typeof import("../../../src/app/destiny-map/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/destiny-match/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/destiny-match">> = Specific
  const handler = {} as typeof import("../../../src/app/destiny-match/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dream/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dream">> = Specific
  const handler = {} as typeof import("../../../src/app/dream/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/faq/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/faq">> = Specific
  const handler = {} as typeof import("../../../src/app/faq/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/iching/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/iching">> = Specific
  const handler = {} as typeof import("../../../src/app/iching/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/icp/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/icp">> = Specific
  const handler = {} as typeof import("../../../src/app/icp/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/life-prediction/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/life-prediction">> = Specific
  const handler = {} as typeof import("../../../src/app/life-prediction/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/myjourney/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/myjourney">> = Specific
  const handler = {} as typeof import("../../../src/app/myjourney/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/notifications/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/notifications">> = Specific
  const handler = {} as typeof import("../../../src/app/notifications/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/numerology/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/numerology">> = Specific
  const handler = {} as typeof import("../../../src/app/numerology/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/offline/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/offline">> = Specific
  const handler = {} as typeof import("../../../src/app/offline/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/past-life/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/past-life">> = Specific
  const handler = {} as typeof import("../../../src/app/past-life/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/personality/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/personality">> = Specific
  const handler = {} as typeof import("../../../src/app/personality/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/policy/privacy/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/policy/privacy">> = Specific
  const handler = {} as typeof import("../../../src/app/policy/privacy/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/policy/refund/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/policy/refund">> = Specific
  const handler = {} as typeof import("../../../src/app/policy/refund/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/policy/terms/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/policy/terms">> = Specific
  const handler = {} as typeof import("../../../src/app/policy/terms/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/premium-reports/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/premium-reports">> = Specific
  const handler = {} as typeof import("../../../src/app/premium-reports/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/pricing/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/pricing">> = Specific
  const handler = {} as typeof import("../../../src/app/pricing/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/profile/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/profile">> = Specific
  const handler = {} as typeof import("../../../src/app/profile/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/saju/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/saju">> = Specific
  const handler = {} as typeof import("../../../src/app/saju/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/success/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/success">> = Specific
  const handler = {} as typeof import("../../../src/app/success/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/tarot/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/tarot">> = Specific
  const handler = {} as typeof import("../../../src/app/tarot/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/test-credit-modal/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/test-credit-modal">> = Specific
  const handler = {} as typeof import("../../../src/app/test-credit-modal/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
