// SSR 로 미리 번역해 PricingPageClient 로 넘기는 카피 키 목록.
// pricing/page.tsx 가 이 순서대로 번역 배열(ssrCopy)을 만들고,
// PricingPageClient 가 같은 순서로 인덱싱(SSR_PRICING_INDEX)하므로 — 둘이
// 어긋나면 카피가 통째로 밀린다 — 단일 출처로 둔다.
export const SSR_PRICING_KEYS = [
  'paymentError',
  'eyebrow',
  'heroTitle',
  'heroSub',
  'creditPacks',
  'creditPacksDesc',
  'bestValue',
  'readings',
  'perReading',
  'buyNow',
  'howItWorks',
  'oneReading',
  'oneReadingDesc',
  'freeFeature',
  'freeFeatureDesc',
  'validity',
  'validityDesc',
  'faq',
  'faqs.q1',
  'faqs.a1',
  'faqs.q2',
  'faqs.a2',
  'faqs.q3',
  'faqs.a3',
  'faqs.q4',
  'faqs.a4',
  'faqs.q5',
  'faqs.a5',
  'faqs.q6',
  'faqs.a6',
  'faqs.q7',
  'faqs.a7',
  'faqs.q8',
  'faqs.a8',
  'guarantee',
  'guaranteeDesc',
  'ctaTitle',
  'ctaSub',
  'startFree',
  'learnMore',
] as const
