/**
 * Tarot Recommendation Data
 * Shared static data for tarot recommendations.
 */

export const themeKeywords: Record<string, string[]> = {
  'love-relationships': [
    '연애',
    '사랑',
    '썸',
    '짝사랑',
    '이별',
    '결혼',
    '애인',
    '남친',
    '여친',
    '관계',
    '데이트',
    '고백',
    '재회',
    '헤어',
    '남자친구',
    '여자친구',
    '배우자',
    '좋아',
    '호감',
    '그 사람',
    '그사람',
    '상대방',
    '마음에 들',
    '설레',
    '전남친',
    '전여친',
    'ex',
    '다시 만날',
    '돌아올',
    '연락',
    'love',
    'relationship',
    'dating',
    'partner',
    'marriage',
    'breakup',
    'crush',
    'like',
    'ex',
  ],
  'career-work': [
    '직장',
    '이직',
    '취업',
    '회사',
    '커리어',
    '상사',
    '동료',
    '업무',
    '승진',
    '면접',
    '퇴사',
    '사업',
    '창업',
    '진로',
    '직업',
    '월급',
    '근무',
    '회사생활',
    '시험',
    '합격',
    '붙을',
    '떨어',
    '자격증',
    '공무원',
    '공시',
    '토익',
    '수능',
    '그만두',
    '관두',
    '옮기',
    '이직할',
    'career',
    'job',
    'work',
    'boss',
    'promotion',
    'interview',
    'office',
    'workplace',
    'exam',
    'test',
    'pass',
    'quit',
  ],
  'money-finance': [
    '돈',
    '재정',
    '투자',
    '월급',
    '수입',
    '재물',
    '금전',
    '주식',
    '부동산',
    '저축',
    '대출',
    '빚',
    '재산',
    '경제',
    '부자',
    '수익',
    '재테크',
    '코인',
    '비트',
    '재물운',
    '금전운',
    '돈이 들어',
    '돈 들어',
    '사야',
    '살까',
    '구매',
    '구입',
    '지출',
    '비싼',
    '가격',
    '물건',
    'money',
    'finance',
    'investment',
    'salary',
    'wealth',
    'crypto',
    'bitcoin',
    'buy',
    'purchase',
  ],
  'well-being-health': [
    '건강',
    '몸',
    '피곤',
    '스트레스',
    '아픔',
    '병원',
    '다이어트',
    '운동',
    '잠',
    '수면',
    '멘탈',
    '우울',
    '불안',
    '치료',
    '회복',
    '힐링',
    '균형',
    '슬퍼',
    '외로워',
    '힘들어',
    '지쳐',
    '무서워',
    '화나',
    '짜증',
    'health',
    'healing',
    'balance',
    'mind and body',
    'stress',
    'tired',
    'sick',
    'mental',
    'sad',
    'lonely',
    'anxious',
  ],
  'decisions-crossroads': [
    '선택',
    '결정',
    '고민',
    '갈림길',
    '어떡해',
    '어쩌지',
    '할까 말까',
    '언제',
    '타이밍',
    '시기',
    '때',
    '시점',
    '기회',
    'vs',
    '아니면',
    '둘 중',
    'A B',
    '뭘',
    '어느',
    '어디',
    'decision',
    'choose',
    'choice',
    'should',
    'which',
    'when',
    'timing',
  ],
  'daily-reading': [
    '오늘',
    '하루',
    '내일',
    '아침',
    '저녁',
    '모레',
    '오늘의',
    '하루의',
    'today',
    'tomorrow',
    'daily',
  ],
  'self-discovery': [
    '나는 누구',
    '나에 대해',
    '본질',
    '정체성',
    '강점',
    '장점',
    '재능',
    '자아',
    '나다움',
    '내 정체성',
    'myself',
    'identity',
    'strength',
    'hidden strength',
    'talent',
    'who am i',
    'personality',
  ],
  'spiritual-growth': [
    '성장',
    '영적',
    '명상',
    '내면',
    '영혼',
    '깨달음',
    '수행',
    '수양',
    'spiritual',
    'growth',
    'meditation',
    'soul',
    'enlightenment',
  ],
  'general-insight': [
    '운세',
    '전반',
    '종합',
    '전체',
    '흐름',
    '에너지',
    '기운',
    'fortune',
    'general',
    'overall',
    'energy',
  ],
}

export const complexityKeywords = {
  simple: ['간단', '빠르게', '한마디', '핵심', '짧게', 'quick', 'simple', 'brief'],
  detailed: ['자세히', '깊게', '분석', '종합', '상세', 'detail', 'deep', 'thorough'],
}

export const quickQuestions = [
  {
    emoji: '☀️',
    label: '오늘 운세',
    labelEn: 'Today',
    question: '오늘 하루 어떤 일이 생길까요?',
    questionEn: 'What will happen today?',
  },
  {
    emoji: '💕',
    label: '썸남/썸녀',
    labelEn: 'Crush',
    question: '그 사람이 나를 좋아할까요?',
    questionEn: 'Does my crush like me back?',
  },
  {
    emoji: '💼',
    label: '면접 결과',
    labelEn: 'Interview',
    question: '이번 면접 붙을 수 있을까요?',
    questionEn: 'Will I pass this interview?',
  },
  {
    emoji: '⚖️',
    label: 'A vs B',
    labelEn: 'Choice',
    question: 'A와 B 중에 뭘 선택해야 할까요?',
    questionEn: 'Should I choose A or B?',
  },
  {
    emoji: '🚀',
    label: '이직할까',
    labelEn: 'Quit',
    question: '지금 회사 그만두고 이직해도 될까요?',
    questionEn: 'Should I quit and find a new job?',
  },
  {
    emoji: '💰',
    label: '돈 들어올까',
    labelEn: 'Money',
    question: '이번 달 돈이 들어올까요?',
    questionEn: 'Will I receive money this month?',
  },
  {
    emoji: '📝',
    label: '시험 합격',
    labelEn: 'Exam',
    question: '이번 시험 합격할 수 있을까요?',
    questionEn: 'Will I pass this exam?',
  },
  {
    emoji: '💔',
    label: '재회 가능할까',
    labelEn: 'Ex',
    question: '헤어진 사람과 다시 만날 수 있을까요?',
    questionEn: 'Can I get back with my ex?',
  },
]

export interface DirectMatch {
  keywords: string[]
  // 복합 키워드: 이 키워드들 중 하나라도 포함되어야 매칭 (주제 한정)
  contextKeywords?: string[]
  themeId: string
  spreadId: string
  reason: string
  reasonKo: string
  priority: number // 높을수록 우선순위 높음
}

export const directMatches: DirectMatch[] = [
  // ========== 복합 매칭 (높은 우선순위) ==========
  // 취업 + 시기 → career-path (취업 언제?)
  {
    keywords: ['취업', '구직', '일자리'],
    contextKeywords: ['언제', '시기', '타이밍', 'when', 'timing', '할 수 있', '될까', '가능'],
    themeId: 'career-work',
    spreadId: 'career-path',
    reason: 'When will you get hired?',
    reasonKo: '취업 시기와 방향을 봐요',
    priority: 100,
  },
  // 이직 + 시기 → job-change (타이밍 강조)
  {
    keywords: ['이직', '옮기'],
    contextKeywords: ['언제', '시기', '타이밍', 'when', 'timing'],
    themeId: 'career-work',
    spreadId: 'job-change',
    reason: 'Best timing for job change',
    reasonKo: '이직 적기를 봐요',
    priority: 100,
  },
  // 결혼 + 시기 → finding-a-partner
  {
    keywords: ['결혼'],
    contextKeywords: ['언제', '시기', '타이밍', 'when', 'timing', '할 수 있', '될까'],
    themeId: 'love-relationships',
    spreadId: 'finding-a-partner',
    reason: 'When will you get married?',
    reasonKo: '결혼 시기를 봐요',
    priority: 100,
  },
  // 연애 + 시기 → finding-a-partner
  {
    keywords: ['연애', '사랑', '만남', '애인'],
    contextKeywords: ['언제', '시기', '시작', 'when', 'timing', 'start', '할 수 있', '생길'],
    themeId: 'love-relationships',
    spreadId: 'finding-a-partner',
    reason: 'When will love come?',
    reasonKo: '연애 시기를 봐요',
    priority: 100,
  },
  // 돈 + 언제 → abundance-path
  {
    keywords: ['돈', '재물', '금전', '돈이'],
    contextKeywords: ['언제', '들어올', '생길', 'when', '벌', '받을'],
    themeId: 'money-finance',
    spreadId: 'abundance-path',
    reason: 'When will money come?',
    reasonKo: '재물운 시기를 봐요',
    priority: 100,
  },
  // 승진 + 시기
  {
    keywords: ['승진'],
    contextKeywords: ['언제', '시기', '될까', '할 수 있'],
    themeId: 'career-work',
    spreadId: 'career-path',
    reason: 'When will you get promoted?',
    reasonKo: '승진 시기를 봐요',
    priority: 100,
  },

  // ========== 연애 관련 ==========
  // 운명의 상대/인연 찾기
  {
    keywords: ['운명의 상대', '인연', '소울메이트', 'soulmate', 'destiny'],
    themeId: 'love-relationships',
    spreadId: 'finding-a-partner',
    reason: 'Find your destined partner',
    reasonKo: '운명의 인연을 봐요',
    priority: 85,
  },
  {
    keywords: [
      '그 사람',
      '그사람',
      '상대',
      '상대방',
      '걔',
      '쟤',
      '썸남',
      '썸녀',
      '짝사랑',
      'crush',
    ],
    contextKeywords: [
      '마음',
      '속마음',
      '감정',
      '생각',
      '나를 좋아',
      '날 좋아',
      '호감',
      '관심',
      '날 어떻게',
      'like me',
      'feelings',
      'into me',
    ],
    themeId: 'love-relationships',
    spreadId: 'crush-feelings',
    reason: 'Find out how they feel',
    reasonKo: '그 사람 마음을 읽어봐요',
    priority: 80,
  },
  {
    keywords: ['that person', 'the person', 'person i like'],
    contextKeywords: ['feel', 'feels', 'about me', 'thinks of me', 'think about me'],
    themeId: 'love-relationships',
    spreadId: 'crush-feelings',
    reason: 'Find out how they feel',
    reasonKo: '그 사람 마음을 읽어봐요',
    priority: 80,
  },
  {
    keywords: ['재회', '다시 만', '돌아올', '전남친', '전여친', '헤어진', 'ex', '다시 사귈'],
    themeId: 'love-relationships',
    spreadId: 'reconciliation',
    reason: 'Explore reconciliation',
    reasonKo: '재회 가능성을 봐요',
    priority: 80,
  },
  {
    keywords: ['우리 관계', '사이가', '사귀는', '연인', '이혼'],
    themeId: 'love-relationships',
    spreadId: 'relationship-check-in',
    reason: 'Check your relationship',
    reasonKo: '관계 상태를 점검해요',
    priority: 75,
  },

  // ========== 커리어/시험 관련 ==========
  {
    keywords: ['취업', '구직', '일자리', 'job', 'hire', 'employ', '직장'],
    themeId: 'career-work',
    spreadId: 'career-path',
    reason: 'Check job opportunities',
    reasonKo: '취업/커리어 방향을 봐요',
    priority: 70,
  },
  {
    keywords: ['면접', 'interview'],
    themeId: 'career-work',
    spreadId: 'interview-result',
    reason: 'Check your interview chances',
    reasonKo: '면접 결과를 미리 봐요',
    priority: 70,
  },
  {
    keywords: ['시험', '합격', '붙을', '수능', '공시', '자격증', 'exam', 'test', 'pass', '토익'],
    themeId: 'career-work',
    spreadId: 'exam-pass',
    reason: 'Check exam success',
    reasonKo: '시험 합격 가능성을 봐요',
    priority: 70,
  },
  {
    keywords: [
      '이직',
      '그만두',
      '그만둬',
      '관두',
      '관둬',
      '퇴사',
      'quit',
      '옮기',
      '회사 떠나',
      '회사 나가',
    ],
    themeId: 'career-work',
    spreadId: 'job-change',
    reason: 'Should you change jobs?',
    reasonKo: '이직 여부를 봐요',
    priority: 70,
  },
  {
    keywords: ['승진', 'promotion', '진급'],
    themeId: 'career-work',
    spreadId: 'career-path',
    reason: 'Check promotion chances',
    reasonKo: '승진 가능성을 봐요',
    priority: 70,
  },
  {
    keywords: ['사업', '창업', '자영업', 'business', 'startup'],
    themeId: 'career-work',
    spreadId: 'career-path',
    reason: 'Business prospects',
    reasonKo: '사업/창업 전망을 봐요',
    priority: 70,
  },

  // ========== 재정 관련 ==========
  {
    keywords: ['주식', '투자', '코인', '비트코인', '부동산', 'stock', 'invest', 'crypto'],
    themeId: 'money-finance',
    spreadId: 'financial-snapshot',
    reason: 'Investment outlook',
    reasonKo: '투자 전망을 봐요',
    priority: 70,
  },
  {
    keywords: ['돈', '재물', '금전', '월급', '수입', 'money', 'income'],
    themeId: 'money-finance',
    spreadId: 'abundance-path',
    reason: 'Financial prospects',
    reasonKo: '재물운을 봐요',
    priority: 65,
  },

  // ========== 건강/감정 관련 ==========
  {
    keywords: ['건강', '아프', '병', '치료', '회복', 'health', 'sick'],
    themeId: 'well-being-health',
    spreadId: 'healing-path',
    reason: 'Health guidance',
    reasonKo: '건강 상태를 봐요',
    priority: 70,
  },
  {
    keywords: [
      '스트레스',
      '우울',
      '불안',
      '멘탈',
      '지친',
      '힘들',
      '슬퍼',
      '외로워',
      '화나',
      '짜증',
      '무서워',
      '지쳐',
      'stress',
      'anxious',
      'tired',
      'sad',
      'lonely',
      'angry',
      'scared',
    ],
    themeId: 'well-being-health',
    spreadId: 'mind-body-scan',
    reason: 'Mental wellness check',
    reasonKo: '마음 상태를 봐요',
    priority: 70,
  },

  // ========== 일간/주간 ==========
  {
    keywords: ['오늘', '하루', 'today'],
    themeId: 'daily-reading',
    spreadId: 'day-card',
    reason: 'Your daily message',
    reasonKo: '오늘의 메시지',
    priority: 60,
  },
  {
    keywords: ['이번 주', '주간', '일주일', 'week', '이번주'],
    themeId: 'daily-reading',
    spreadId: 'weekly-forecast',
    reason: 'Your week ahead',
    reasonKo: '이번 주 운세를 봐요',
    priority: 60,
  },
  {
    keywords: ['아침', '오전', 'morning'],
    themeId: 'daily-reading',
    spreadId: 'three-times',
    reason: 'Morning guidance',
    reasonKo: '하루의 흐름을 봐요',
    priority: 55,
  },

  // ========== 자기탐색/성장 ==========
  {
    keywords: ['나는', '나에 대해', '내가 누구', '정체성', 'myself', 'who am i'],
    themeId: 'self-discovery',
    spreadId: 'identity-core',
    reason: 'Discover yourself',
    reasonKo: '나를 더 알아봐요',
    priority: 60,
  },
  {
    keywords: ['성장', '발전', '앞으로', '미래', 'growth', 'future'],
    themeId: 'spiritual-growth',
    spreadId: 'path-of-growth',
    reason: 'Path of growth',
    reasonKo: '성장의 방향을 봐요',
    priority: 55,
  },

  // ========== 커리어 선택 (A vs B) ==========
  {
    keywords: [
      'vs',
      '어느',
      '어디로',
      '둘 중',
      '둘중',
      '두 곳',
      '두곳',
      '비교',
      '선택',
      '갈까',
      '가야',
      '어느 쪽',
      '어느쪽',
      '어떤 회사',
      '회사 중',
      '둘 중에',
      'which',
      'either',
    ],
    contextKeywords: [
      '회사',
      '직장',
      '이직',
      '취업',
      '면접',
      '오퍼',
      '연봉',
      '직무',
      '포지션',
      '부서',
      '팀',
      '커리어',
      '직업',
      'job',
      'career',
      'company',
      'offer',
      'salary',
      'position',
      'role',
      'department',
      'team',
    ],
    themeId: 'career-work',
    spreadId: 'career-path',
    reason: 'Compare career options',
    reasonKo: '커리어 선택을 비교하는 질문',
    priority: 85,
  },

  // ========== 선택/결정 ==========
  // 비교 질문 (A vs B, 살까 말까)
  {
    keywords: ['vs', '아니면', '둘 중', '어느', '뭘 선택', '어떤 걸', '살까 말까', '갈까 말까'],
    themeId: 'decisions-crossroads',
    spreadId: 'two-paths',
    reason: 'Compare your options',
    reasonKo: '두 선택지를 비교해봐요',
    priority: 50,
  },
  // "~할까" 패턴 (선택)
  {
    keywords: [
      '할까',
      '갈까',
      '볼까',
      '먹을까',
      '살까',
      '마실까',
      '해볼까',
      '탈까',
      '입을까',
      '쓸까',
      '들을까',
      '읽을까',
      '볼까',
      '만날까',
      '말할까',
      '물어볼까',
      '신청할까',
      '등록할까',
      '시작할까',
      '끝낼까',
      '바꿀까',
      '고를까',
    ],
    themeId: 'decisions-crossroads',
    spreadId: 'yes-no-why',
    reason: 'Yes or No guidance',
    reasonKo: '해야 할지 말아야 할지',
    priority: 45,
  },
  // "~도 될까/되나/돼" 패턴 (허락/확인형 질문)
  {
    keywords: [
      '도 될까',
      '도 되나',
      '도 돼',
      '도될까',
      '도되나',
      '도돼',
      '면 될까',
      '면 되나',
      '면 돼',
      '어도 될',
      '어도 되',
      '아도 될',
      '아도 되',
      '해도 될',
      '해도 되',
      '가도 될',
      '가도 되',
      '사도 될',
      '사도 되',
      '먹어도 될',
      '먹어도 되',
      '마셔도 될',
      '마셔도 되',
      '써도 될',
      '써도 되',
      '타도 될',
      '타도 되',
      '입어도 될',
      '입어도 되',
      '봐도 될',
      '봐도 되',
      '만나도 될',
      '만나도 되',
      '해봐도 될',
      '해봐도 되',
      '시작해도 될',
      '시작해도 되',
      '그만둬도 될',
      '그만둬도 되',
      '바꿔도 될',
      '바꿔도 되',
      '신청해도 될',
      '신청해도 되',
      '등록해도 될',
      '등록해도 되',
    ],
    themeId: 'decisions-crossroads',
    spreadId: 'yes-no-why',
    reason: 'Yes or No guidance',
    reasonKo: '해도 될지 안 될지',
    priority: 50,
  },
  // "해야 할까/하나/해" 패턴
  {
    keywords: [
      '해야 할까',
      '해야 하나',
      '해야 돼',
      '해야할까',
      '해야하나',
      '해야돼',
      '가야 할까',
      '가야 하나',
      '가야 돼',
      '사야 할까',
      '사야 하나',
      '사야 돼',
      '먹어야 할까',
      '먹어야 하나',
      '타야 할까',
      '타야 하나',
      '봐야 할까',
      '봐야 하나',
      '만나야 할까',
      '만나야 하나',
      '바꿔야 할까',
      '바꿔야 하나',
      '그만둬야 할까',
      '그만둬야 하나',
      '시작해야 할까',
      '시작해야 하나',
    ],
    themeId: 'decisions-crossroads',
    spreadId: 'yes-no-why',
    reason: 'Yes or No guidance',
    reasonKo: '해야 할지 말아야 할지',
    priority: 50,
  },
  // "괜찮을까/좋을까" 패턴
  {
    keywords: [
      '괜찮을까',
      '괜찮나',
      '좋을까',
      '좋나',
      '나을까',
      '나을까요',
      '맞을까',
      '맞나',
      '될까',
      '될까요',
      '되나',
      '되나요',
      '가능할까',
      '가능하나',
      '할 수 있을까',
      '할수있을까',
    ],
    themeId: 'decisions-crossroads',
    spreadId: 'yes-no-why',
    reason: 'Yes or No guidance',
    reasonKo: '될지 안 될지',
    priority: 48,
  },
  // "언제"는 다른 주제 키워드 없을 때만 일반 타이밍으로
  {
    keywords: ['언제', '타이밍', '시기', '때가', 'when', 'timing'],
    themeId: 'decisions-crossroads',
    spreadId: 'timing-window',
    reason: 'Find the right timing',
    reasonKo: '적절한 타이밍을 봐요',
    priority: 30,
  }, // 낮은 우선순위

  // ========== 특수 키워드 ==========
  // 로또/복권/행운
  {
    keywords: ['로또', '복권', '당첨', 'lottery', 'lucky'],
    themeId: 'money-finance',
    spreadId: 'abundance-path',
    reason: 'Luck and fortune',
    reasonKo: '행운을 봐요',
    priority: 60,
  },
  // 이민/유학
  {
    keywords: ['이민', '유학', '해외', '외국', 'abroad', 'immigration'],
    themeId: 'decisions-crossroads',
    spreadId: 'two-paths',
    reason: 'Big life decision',
    reasonKo: '큰 결정을 봐요',
    priority: 55,
  },
]
export const dangerousKeywords = [
  '자살',
  '죽고 싶',
  '죽을래',
  '살기 싫',
  '끝내고 싶',
  '죽어버릴',
  '자해',
  '목숨',
  '생을 마감',
  '세상 떠나',
  'suicide',
  'kill myself',
  'end my life',
  'want to die',
]

export const cardCountPatterns = {
  one: ['오늘', '하루', 'today', 'daily', '한마디', '핵심', '간단', '빠르게', 'quick', 'simple'],
  two: [
    'vs',
    '아니면',
    '둘 중',
    'A B',
    '어느',
    '뭘 선택',
    '할까 말까',
    '해도 될까',
    '해야 할까',
    'should i',
    '이것 저것',
    '이거 저거',
  ],
  three: [
    '흐름',
    '과거',
    '현재',
    '미래',
    'flow',
    'past',
    'present',
    'future',
    '좋아할까',
    '마음',
    '감정',
    'feelings',
    'like me',
    '면접',
    '시험',
    '합격',
    'interview',
    'exam',
    'pass',
    '재회',
    '다시',
    '돌아올',
    'ex',
    'back together',
  ],
  four: [
    '이직',
    '퇴사',
    '그만두',
    'job change',
    'quit',
    '관계',
    '사이',
    'relationship',
    '원인',
    '해결',
    '조언',
    'cause',
    'solution',
    'advice',
  ],
  five: [
    '자세히',
    '깊게',
    '분석',
    'detail',
    'deep',
    'thorough',
    '종합',
    '전반',
    'overall',
    'comprehensive',
  ],
  seven: ['이번 주', '주간', '일주일', 'week', 'weekly'],
  ten: [
    '인생',
    '전체',
    '모든',
    'life',
    'everything',
    'all aspects',
    '켈틱',
    'celtic',
    '상세 분석',
    'detailed analysis',
  ],
}
