import { TarotTheme } from "./tarot.types";

// Spread/theme definitions for Tarot with Korean translations
export const tarotThemes: TarotTheme[] = [
  {
    id: "general-insight",
    category: "General Insight",
    categoryKo: "일반 통찰",
    description: "Explore the overall energy surrounding you.",
    descriptionKo: "당신을 둘러싼 전체적인 에너지를 탐색하세요.",
    spreads: [
      {
        id: "quick-reading",
        title: "Quick Reading",
        titleKo: "빠른 리딩",
        cardCount: 1,
        description: "A quick, clear piece of advice or a core insight into your current situation.",
        descriptionKo: "현재 상황에 대한 빠르고 명확한 조언 또는 핵심 통찰.",
        positions: [{ title: "Core Insight", titleKo: "핵심 통찰" }],
      },
      {
        id: "past-present-future",
        title: "Past, Present, Future",
        titleKo: "과거, 현재, 미래",
        cardCount: 3,
        description: "Examine the flow of time: the cause from the past, the current situation, and the likely future.",
        descriptionKo: "시간의 흐름을 살펴보세요: 과거의 원인, 현재 상황, 그리고 예상되는 미래.",
        positions: [
          { title: "The Past", titleKo: "과거" },
          { title: "The Present", titleKo: "현재" },
          { title: "The Future", titleKo: "미래" }
        ],
      },
      {
        id: "celtic-cross",
        title: "The Celtic Cross",
        titleKo: "켈틱 크로스",
        cardCount: 10,
        description: "A deep and comprehensive reading that covers all aspects of your situation in great detail.",
        descriptionKo: "상황의 모든 측면을 자세히 다루는 깊고 포괄적인 리딩.",
        positions: [
          { title: "The Present", titleKo: "현재" },
          { title: "The Challenge", titleKo: "도전" },
          { title: "The Past", titleKo: "과거" },
          { title: "The Future", titleKo: "미래" },
          { title: "Above (Conscious)", titleKo: "위 (의식)" },
          { title: "Below (Subconscious)", titleKo: "아래 (무의식)" },
          { title: "Advice", titleKo: "조언" },
          { title: "External Influences", titleKo: "외부 영향" },
          { title: "Hopes and Fears", titleKo: "희망과 두려움" },
          { title: "The Outcome", titleKo: "결과" },
        ],
      },
    ],
  },
  {
    id: "love-relationships",
    category: "Love & Relationships",
    categoryKo: "사랑 & 관계",
    description: "Uncover the mysteries of your heart.",
    descriptionKo: "마음의 신비를 밝혀보세요.",
    spreads: [
      {
        id: "relationship-check-in",
        title: "Relationship Check-in",
        titleKo: "관계 점검",
        cardCount: 2,
        description: "A snapshot of you and your partner's energies within the relationship.",
        descriptionKo: "관계 내에서 당신과 파트너의 에너지 스냅샷.",
        positions: [
          { title: "Your Energy", titleKo: "당신의 에너지" },
          { title: "Partner's Energy", titleKo: "파트너의 에너지" }
        ],
      },
      {
        id: "relationship-cross",
        title: "Relationship Cross",
        titleKo: "관계 크로스",
        cardCount: 5,
        description: "An in-depth analysis of your connection, challenges, and future direction.",
        descriptionKo: "연결, 도전, 그리고 미래 방향에 대한 심층 분석.",
        positions: [
          { title: "You", titleKo: "당신" },
          { title: "Your Partner", titleKo: "파트너" },
          { title: "The Connection", titleKo: "연결" },
          { title: "The Challenge", titleKo: "도전" },
          { title: "The Outcome", titleKo: "결과" },
        ],
      },
      {
        id: "finding-a-partner",
        title: "Finding a Partner",
        titleKo: "파트너 찾기",
        cardCount: 4,
        description: "Gain clarity on what you seek, what blocks you, and how to attract love.",
        descriptionKo: "원하는 것, 장애물, 그리고 사랑을 끌어당기는 방법에 대한 명확성을 얻으세요.",
        positions: [
          { title: "What You Seek", titleKo: "원하는 것" },
          { title: "What Blocks You", titleKo: "장애물" },
          { title: "How to Attract", titleKo: "끌어당기는 방법" },
          { title: "Potential Partner", titleKo: "잠재적 파트너" },
        ],
      },
    ],
  },
  {
    id: "career-work",
    category: "Career & Work",
    categoryKo: "커리어 & 직장",
    description: "Find clarity on your professional journey.",
    descriptionKo: "직업적 여정에 대한 명확성을 찾으세요.",
    spreads: [
      {
        id: "quick-guidance",
        title: "Quick Guidance",
        titleKo: "빠른 가이드",
        cardCount: 1,
        description: "A single point of focus or advice for your professional life today.",
        descriptionKo: "오늘 직업 생활을 위한 단일 초점 또는 조언.",
        positions: [{ title: "Key Focus", titleKo: "핵심 초점" }],
      },
      {
        id: "career-path",
        title: "Career Path",
        titleKo: "커리어 경로",
        cardCount: 3,
        description: "Understand your current role, your next step, and your ultimate career potential.",
        descriptionKo: "현재 역할, 다음 단계, 그리고 궁극적인 커리어 잠재력을 이해하세요.",
        positions: [
          { title: "Current Role", titleKo: "현재 역할" },
          { title: "Next Step", titleKo: "다음 단계" },
          { title: "Long-term Potential", titleKo: "장기적 잠재력" }
        ],
      },
      {
        id: "work-life-balance",
        title: "Work-Life Balance",
        titleKo: "일과 삶의 균형",
        cardCount: 5,
        description: "Explore the dynamics between your career, personal life, and overall well-being.",
        descriptionKo: "커리어, 개인 생활, 그리고 전반적인 웰빙 사이의 역학을 탐색하세요.",
        positions: [
          { title: "Work Energy", titleKo: "업무 에너지" },
          { title: "Life Energy", titleKo: "삶의 에너지" },
          { title: "The Conflict", titleKo: "갈등" },
          { title: "Path to Harmony", titleKo: "조화로의 길" },
          { title: "Ideal State", titleKo: "이상적인 상태" },
        ],
      },
    ],
  },
  {
    id: "money-finance",
    category: "Money & Finance",
    categoryKo: "돈 & 재정",
    description: "Seek guidance on your financial situation.",
    descriptionKo: "재정 상황에 대한 가이드를 구하세요.",
    spreads: [
      {
        id: "financial-snapshot",
        title: "Financial Snapshot",
        titleKo: "재정 스냅샷",
        cardCount: 2,
        description: "A quick look at your current money flow and the immediate next step.",
        descriptionKo: "현재 자금 흐름과 즉각적인 다음 단계에 대한 빠른 검토.",
        positions: [
          { title: "Current Flow", titleKo: "현재 흐름" },
          { title: "Next Step", titleKo: "다음 단계" }
        ],
      },
      {
        id: "abundance-path",
        title: "Abundance Path",
        titleKo: "풍요의 길",
        cardCount: 4,
        description: "Understand your money mindset, opportunities, and how to align with abundance.",
        descriptionKo: "돈에 대한 마음가짐, 기회, 그리고 풍요와 조화를 이루는 방법을 이해하세요.",
        positions: [
          { title: "Mindset", titleKo: "마음가짐" },
          { title: "Opportunity", titleKo: "기회" },
          { title: "Action", titleKo: "행동" },
          { title: "Long-term Outlook", titleKo: "장기 전망" },
        ],
      },
      {
        id: "career-money",
        title: "Career & Money",
        titleKo: "커리어 & 돈",
        cardCount: 5,
        description: "Connect your career direction with your financial goals.",
        descriptionKo: "커리어 방향을 재정 목표와 연결하세요.",
        positions: [
          { title: "Career Direction", titleKo: "커리어 방향" },
          { title: "Skills to Leverage", titleKo: "활용할 스킬" },
          { title: "Blockers", titleKo: "장애물" },
          { title: "Money Advice", titleKo: "돈 조언" },
          { title: "Outcome", titleKo: "결과" },
        ],
      },
    ],
  },
  {
    id: "well-being-health",
    category: "Well-being & Health",
    categoryKo: "웰빙 & 건강",
    description: "Listen to the whispers of your body and mind.",
    descriptionKo: "몸과 마음의 속삭임에 귀 기울이세요.",
    spreads: [
      {
        id: "mind-body-scan",
        title: "Mind-Body Scan",
        titleKo: "심신 스캔",
        cardCount: 3,
        description: "Check-in with mind, body, and spirit to regain balance.",
        descriptionKo: "균형을 되찾기 위해 마음, 몸, 영혼을 점검하세요.",
        positions: [
          { title: "Mind", titleKo: "마음" },
          { title: "Body", titleKo: "몸" },
          { title: "Spirit", titleKo: "영혼" }
        ],
      },
      {
        id: "healing-path",
        title: "Healing Path",
        titleKo: "치유의 길",
        cardCount: 4,
        description: "Identify areas needing care and the steps to heal.",
        descriptionKo: "돌봄이 필요한 영역과 치유 단계를 파악하세요.",
        positions: [
          { title: "Area Needing Care", titleKo: "돌봄이 필요한 영역" },
          { title: "What Supports Healing", titleKo: "치유를 지원하는 것" },
          { title: "What to Release", titleKo: "놓아야 할 것" },
          { title: "Outcome", titleKo: "결과" },
        ],
      },
      {
        id: "energy-balance",
        title: "Energy Balance",
        titleKo: "에너지 균형",
        cardCount: 5,
        description: "Balance your energy flow and daily routine.",
        descriptionKo: "에너지 흐름과 일상 루틴의 균형을 맞추세요.",
        positions: [
          { title: "Morning Energy", titleKo: "아침 에너지" },
          { title: "Midday Energy", titleKo: "정오 에너지" },
          { title: "Evening Energy", titleKo: "저녁 에너지" },
          { title: "Energy Drain", titleKo: "에너지 소모" },
          { title: "Energy Refill", titleKo: "에너지 충전" },
        ],
      },
    ],
  },
  {
    id: "spiritual-growth",
    category: "Spiritual Growth",
    categoryKo: "영적 성장",
    description: "Connect with your higher self.",
    descriptionKo: "더 높은 자아와 연결하세요.",
    spreads: [
      {
        id: "inner-voice",
        title: "Inner Voice",
        titleKo: "내면의 목소리",
        cardCount: 1,
        description: "A single card to hear what your higher self wants to say.",
        descriptionKo: "더 높은 자아가 말하고 싶은 것을 듣기 위한 단일 카드.",
        positions: [{ title: "Message", titleKo: "메시지" }],
      },
      {
        id: "shadow-work",
        title: "Shadow Work",
        titleKo: "그림자 작업",
        cardCount: 4,
        description: "Meet and heal the shadow aspects within.",
        descriptionKo: "내면의 그림자 측면을 만나고 치유하세요.",
        positions: [
          { title: "Shadow Aspect", titleKo: "그림자 측면" },
          { title: "How It Shows Up", titleKo: "나타나는 방식" },
          { title: "How to Heal", titleKo: "치유 방법" },
          { title: "Lesson", titleKo: "교훈" },
        ],
      },
      {
        id: "path-of-growth",
        title: "Path of Growth",
        titleKo: "성장의 길",
        cardCount: 5,
        description: "Understand your current spiritual lesson and next steps.",
        descriptionKo: "현재 영적 교훈과 다음 단계를 이해하세요.",
        positions: [
          { title: "Current Lesson", titleKo: "현재 교훈" },
          { title: "Support", titleKo: "지원" },
          { title: "Challenge", titleKo: "도전" },
          { title: "Practice", titleKo: "실천" },
          { title: "Outcome", titleKo: "결과" },
        ],
      },
    ],
  },
  {
    id: "decisions-crossroads",
    category: "Decisions & Crossroads",
    categoryKo: "결정 & 갈림길",
    description: "Compare options and pick the most aligned path.",
    descriptionKo: "선택지를 비교하고 가장 맞는 길을 선택하세요.",
    spreads: [
      {
        id: "two-paths",
        title: "Two Paths",
        titleKo: "두 갈래 길",
        cardCount: 6,
        description: "Contrast two options side by side and reveal the guidance between them.",
        descriptionKo: "두 가지 선택지를 나란히 비교하고 그 사이의 가이드를 밝히세요.",
        positions: [
          { title: "Past Influence", titleKo: "과거 영향" },
          { title: "Path A - Strength", titleKo: "경로 A - 강점" },
          { title: "Path A - Risk", titleKo: "경로 A - 위험" },
          { title: "Path B - Strength", titleKo: "경로 B - 강점" },
          { title: "Path B - Risk", titleKo: "경로 B - 위험" },
          { title: "Guidance / Best Fit", titleKo: "가이드 / 최적 선택" },
        ],
      },
      {
        id: "yes-no-why",
        title: "Yes / No / Why",
        titleKo: "예 / 아니오 / 이유",
        cardCount: 3,
        description: "A concise check on feasibility plus the hidden factor you need to know.",
        descriptionKo: "실현 가능성에 대한 간결한 점검과 알아야 할 숨겨진 요소.",
        positions: [
          { title: "Yes Energy", titleKo: "예 에너지" },
          { title: "No Energy", titleKo: "아니오 에너지" },
          { title: "Hidden Factor", titleKo: "숨겨진 요소" },
        ],
      },
      {
        id: "timing-window",
        title: "Timing Window",
        titleKo: "타이밍 윈도우",
        cardCount: 4,
        description: "Assess when to act and how the energy shifts over time.",
        descriptionKo: "언제 행동해야 하는지, 시간이 지남에 따라 에너지가 어떻게 변하는지 평가하세요.",
        positions: [
          { title: "Now", titleKo: "지금" },
          { title: "1-3 Months", titleKo: "1-3개월" },
          { title: "3-6 Months", titleKo: "3-6개월" },
          { title: "Key Action to Unlock Timing", titleKo: "타이밍을 여는 핵심 행동" },
        ],
      },
    ],
  },
  {
    id: "self-discovery",
    category: "Self-Discovery",
    categoryKo: "자기 발견",
    description: "Deeper inner work beyond the day-to-day.",
    descriptionKo: "일상을 넘어선 더 깊은 내면 작업.",
    spreads: [
      {
        id: "identity-core",
        title: "Identity Core",
        titleKo: "정체성 핵심",
        cardCount: 5,
        description: "Clarify your core driver, blind spot, and the gift you bring.",
        descriptionKo: "핵심 동력, 사각지대, 그리고 당신이 가진 재능을 명확히 하세요.",
        positions: [
          { title: "Core Drive", titleKo: "핵심 동력" },
          { title: "Deep Need", titleKo: "깊은 필요" },
          { title: "Blind Spot", titleKo: "사각지대" },
          { title: "Unique Gift", titleKo: "독특한 재능" },
          { title: "Integration Step", titleKo: "통합 단계" },
        ],
      },
      {
        id: "shadow-integration",
        title: "Shadow Integration",
        titleKo: "그림자 통합",
        cardCount: 6,
        description: "Extend shadow work into practical integration steps.",
        descriptionKo: "그림자 작업을 실질적인 통합 단계로 확장하세요.",
        positions: [
          { title: "Shadow Pattern", titleKo: "그림자 패턴" },
          { title: "Trigger", titleKo: "트리거" },
          { title: "Protective Role", titleKo: "보호 역할" },
          { title: "Cost", titleKo: "대가" },
          { title: "Healing Practice", titleKo: "치유 실천" },
          { title: "Integration Signal", titleKo: "통합 신호" },
        ],
      },
    ],
  },
  {
    id: "daily-reading",
    category: "Daily Reading",
    categoryKo: "오늘의 리딩",
    description: "A quick look at the energies of your day.",
    descriptionKo: "오늘의 에너지를 빠르게 살펴보세요.",
    spreads: [
      {
        id: "day-card",
        title: "Card of the Day",
        titleKo: "오늘의 카드",
        cardCount: 1,
        description: "A single card to guide your day.",
        descriptionKo: "하루를 안내할 단일 카드.",
        positions: [{ title: "Message", titleKo: "메시지" }],
      },
      {
        id: "three-times",
        title: "The Day's Journey",
        titleKo: "하루의 여정",
        cardCount: 3,
        description: "A look at the energies of your morning, afternoon, and evening.",
        descriptionKo: "아침, 오후, 저녁의 에너지를 살펴보세요.",
        positions: [
          { title: "Morning", titleKo: "아침" },
          { title: "Afternoon", titleKo: "오후" },
          { title: "Evening", titleKo: "저녁" }
        ],
      },
    ],
  },
];
