import { TarotTheme } from "./tarot.types";

// Spread/theme definitions for Tarot with Korean translations
export const tarotThemes: TarotTheme[] = [
  {
    id: "general-insight",
    category: "General Insight",
    categoryKo: "전반 운세",
    description: "Explore the overall energy surrounding you.",
    descriptionKo: "지금 나를 둘러싼 흐름을 봐요.",
    spreads: [
      {
        id: "quick-reading",
        title: "Quick Reading",
        titleKo: "빠른 리딩",
        cardCount: 1,
        description: "A quick, clear piece of advice or a core insight into your current situation.",
        descriptionKo: "지금 상황에 대한 핵심 한마디.",
        positions: [{ title: "Core Insight", titleKo: "핵심" }],
      },
      {
        id: "past-present-future",
        title: "Past, Present, Future",
        titleKo: "과거, 현재, 미래",
        cardCount: 3,
        description: "Examine the flow of time: the cause from the past, the current situation, and the likely future.",
        descriptionKo: "과거 → 현재 → 미래 흐름을 한눈에.",
        positions: [
          { title: "The Past", titleKo: "과거" },
          { title: "The Present", titleKo: "현재" },
          { title: "The Future", titleKo: "미래" }
        ],
      },
      {
        id: "celtic-cross",
        title: "The Celtic Cross",
        titleKo: "켈틱 크로스",
        cardCount: 10,
        description: "A deep and comprehensive reading that covers all aspects of your situation in great detail.",
        descriptionKo: "상황을 다각도로 깊게 분석해요.",
        positions: [
          { title: "The Present", titleKo: "현재" },
          { title: "The Challenge", titleKo: "도전" },
          { title: "The Past", titleKo: "과거" },
          { title: "The Future", titleKo: "미래" },
          { title: "Above (Conscious)", titleKo: "의식" },
          { title: "Below (Subconscious)", titleKo: "무의식" },
          { title: "Advice", titleKo: "조언" },
          { title: "External Influences", titleKo: "외부 영향" },
          { title: "Hopes and Fears", titleKo: "희망과 두려움" },
          { title: "The Outcome", titleKo: "결과" },
        ],
      },
    ],
  },
  {
    id: "love-relationships",
    category: "Love & Relationships",
    categoryKo: "연애·관계",
    description: "Uncover the mysteries of your heart.",
    descriptionKo: "연애와 관계에 대해 물어봐요.",
    spreads: [
      {
        id: "crush-feelings",
        title: "Do They Like Me?",
        titleKo: "그 사람 마음",
        cardCount: 3,
        description: "Discover what your crush really feels about you.",
        descriptionKo: "그 사람이 나를 어떻게 생각하는지 봐요.",
        positions: [
          { title: "Their Feelings", titleKo: "상대 마음" },
          { title: "What They Want", titleKo: "원하는 것" },
          { title: "Possibility", titleKo: "가능성" }
        ],
      },
      {
        id: "relationship-check-in",
        title: "Relationship Check-in",
        titleKo: "관계 점검",
        cardCount: 2,
        description: "A snapshot of you and your partner's energies within the relationship.",
        descriptionKo: "나와 상대의 마음 상태를 확인해요.",
        positions: [
          { title: "Your Energy", titleKo: "내 마음" },
          { title: "Partner's Energy", titleKo: "상대 마음" }
        ],
      },
      {
        id: "reconciliation",
        title: "Reconciliation",
        titleKo: "재회 가능성",
        cardCount: 4,
        description: "Can you get back together? What are the chances?",
        descriptionKo: "헤어진 사람과 다시 만날 수 있을까요?",
        positions: [
          { title: "Their Current State", titleKo: "상대 현재 상태" },
          { title: "Your Energy", titleKo: "내 에너지" },
          { title: "Obstacles", titleKo: "장애물" },
          { title: "Outcome", titleKo: "결과" }
        ],
      },
      {
        id: "relationship-cross",
        title: "Relationship Cross",
        titleKo: "관계 크로스",
        cardCount: 5,
        description: "An in-depth analysis of your connection, challenges, and future direction.",
        descriptionKo: "둘 사이를 자세히 들여다봐요.",
        positions: [
          { title: "You", titleKo: "나" },
          { title: "Your Partner", titleKo: "상대" },
          { title: "The Connection", titleKo: "관계" },
          { title: "The Challenge", titleKo: "문제점" },
          { title: "The Outcome", titleKo: "앞으로" },
        ],
      },
      {
        id: "finding-a-partner",
        title: "Finding a Partner",
        titleKo: "인연 찾기",
        cardCount: 4,
        description: "Gain clarity on what you seek, what blocks you, and how to attract love.",
        descriptionKo: "좋은 인연을 만나려면 어떻게 해야 할지.",
        positions: [
          { title: "What You Seek", titleKo: "원하는 사람" },
          { title: "What Blocks You", titleKo: "걸림돌" },
          { title: "How to Attract", titleKo: "인연 만드는 법" },
          { title: "Potential Partner", titleKo: "다가올 인연" },
        ],
      },
    ],
  },
  {
    id: "career-work",
    category: "Career & Work",
    categoryKo: "직장·커리어",
    description: "Find clarity on your professional journey.",
    descriptionKo: "일과 커리어에 대해 물어봐요.",
    spreads: [
      {
        id: "quick-guidance",
        title: "Quick Guidance",
        titleKo: "한줄 조언",
        cardCount: 1,
        description: "A single point of focus or advice for your professional life today.",
        descriptionKo: "오늘 일에서 집중할 포인트.",
        positions: [{ title: "Key Focus", titleKo: "핵심" }],
      },
      {
        id: "interview-result",
        title: "Interview Result",
        titleKo: "면접 결과",
        cardCount: 3,
        description: "What are your chances? What should you focus on?",
        descriptionKo: "면접 붙을까요? 어떻게 준비하면 좋을까요?",
        positions: [
          { title: "Your Energy", titleKo: "내 에너지" },
          { title: "Interviewer's View", titleKo: "면접관 시선" },
          { title: "Outcome", titleKo: "결과" }
        ],
      },
      {
        id: "exam-pass",
        title: "Exam Success",
        titleKo: "시험 합격",
        cardCount: 3,
        description: "Will you pass? What do you need to focus on?",
        descriptionKo: "시험 붙을 수 있을까요? 집중할 부분은?",
        positions: [
          { title: "Current Preparation", titleKo: "현재 준비 상태" },
          { title: "What to Focus", titleKo: "집중할 부분" },
          { title: "Outcome", titleKo: "결과" }
        ],
      },
      {
        id: "job-change",
        title: "Should I Quit?",
        titleKo: "이직할까",
        cardCount: 4,
        description: "Is it time to move on? What are the risks and rewards?",
        descriptionKo: "지금 이직해도 될까요? 타이밍은?",
        positions: [
          { title: "Current Situation", titleKo: "현재 상황" },
          { title: "If You Stay", titleKo: "남으면" },
          { title: "If You Leave", titleKo: "떠나면" },
          { title: "Advice", titleKo: "조언" }
        ],
      },
      {
        id: "career-path",
        title: "Career Path",
        titleKo: "커리어 방향",
        cardCount: 3,
        description: "Understand your current role, your next step, and your ultimate career potential.",
        descriptionKo: "지금 → 다음 스텝 → 장기 방향.",
        positions: [
          { title: "Current Role", titleKo: "현재" },
          { title: "Next Step", titleKo: "다음 단계" },
          { title: "Long-term Potential", titleKo: "장기적으로" }
        ],
      },
      {
        id: "work-life-balance",
        title: "Work-Life Balance",
        titleKo: "워라밸",
        cardCount: 5,
        description: "Explore the dynamics between your career, personal life, and overall well-being.",
        descriptionKo: "일과 삶 사이 균형 잡는 법.",
        positions: [
          { title: "Work Energy", titleKo: "일" },
          { title: "Life Energy", titleKo: "삶" },
          { title: "The Conflict", titleKo: "충돌 지점" },
          { title: "Path to Harmony", titleKo: "해결책" },
          { title: "Ideal State", titleKo: "이상적 상태" },
        ],
      },
    ],
  },
  {
    id: "money-finance",
    category: "Money & Finance",
    categoryKo: "재물·금전",
    description: "Seek guidance on your financial situation.",
    descriptionKo: "돈과 재정에 대해 물어봐요.",
    spreads: [
      {
        id: "financial-snapshot",
        title: "Financial Snapshot",
        titleKo: "재정 체크",
        cardCount: 2,
        description: "A quick look at your current money flow and the immediate next step.",
        descriptionKo: "지금 돈 흐름과 다음 단계.",
        positions: [
          { title: "Current Flow", titleKo: "현재 상황" },
          { title: "Next Step", titleKo: "다음 단계" }
        ],
      },
      {
        id: "abundance-path",
        title: "Abundance Path",
        titleKo: "재물운 높이기",
        cardCount: 4,
        description: "Understand your money mindset, opportunities, and how to align with abundance.",
        descriptionKo: "돈에 대한 태도와 기회를 살펴봐요.",
        positions: [
          { title: "Mindset", titleKo: "마음가짐" },
          { title: "Opportunity", titleKo: "기회" },
          { title: "Action", titleKo: "할 일" },
          { title: "Long-term Outlook", titleKo: "장기 전망" },
        ],
      },
      {
        id: "career-money",
        title: "Career & Money",
        titleKo: "일과 돈",
        cardCount: 5,
        description: "Connect your career direction with your financial goals.",
        descriptionKo: "커리어와 재정을 함께 봐요.",
        positions: [
          { title: "Career Direction", titleKo: "커리어 방향" },
          { title: "Skills to Leverage", titleKo: "강점" },
          { title: "Blockers", titleKo: "걸림돌" },
          { title: "Money Advice", titleKo: "돈 조언" },
          { title: "Outcome", titleKo: "결과" },
        ],
      },
    ],
  },
  {
    id: "well-being-health",
    category: "Well-being & Health",
    categoryKo: "건강·웰빙",
    description: "Listen to the whispers of your body and mind.",
    descriptionKo: "몸과 마음 상태를 체크해요.",
    spreads: [
      {
        id: "mind-body-scan",
        title: "Mind-Body Scan",
        titleKo: "심신 체크",
        cardCount: 3,
        description: "Check-in with mind, body, and spirit to regain balance.",
        descriptionKo: "마음, 몸, 정신 상태를 점검해요.",
        positions: [
          { title: "Mind", titleKo: "마음" },
          { title: "Body", titleKo: "몸" },
          { title: "Spirit", titleKo: "정신" }
        ],
      },
      {
        id: "healing-path",
        title: "Healing Path",
        titleKo: "회복하기",
        cardCount: 4,
        description: "Identify areas needing care and the steps to heal.",
        descriptionKo: "어디가 지쳤는지, 어떻게 회복할지.",
        positions: [
          { title: "Area Needing Care", titleKo: "지친 부분" },
          { title: "What Supports Healing", titleKo: "도움이 되는 것" },
          { title: "What to Release", titleKo: "내려놓을 것" },
          { title: "Outcome", titleKo: "결과" },
        ],
      },
      {
        id: "energy-balance",
        title: "Energy Balance",
        titleKo: "에너지 밸런스",
        cardCount: 5,
        description: "Balance your energy flow and daily routine.",
        descriptionKo: "하루 에너지 흐름을 체크해요.",
        positions: [
          { title: "Morning Energy", titleKo: "아침" },
          { title: "Midday Energy", titleKo: "낮" },
          { title: "Evening Energy", titleKo: "저녁" },
          { title: "Energy Drain", titleKo: "에너지 빠지는 곳" },
          { title: "Energy Refill", titleKo: "에너지 채우는 법" },
        ],
      },
    ],
  },
  {
    id: "spiritual-growth",
    category: "Spiritual Growth",
    categoryKo: "자기 성장",
    description: "Connect with your higher self.",
    descriptionKo: "내면의 성장에 대해 물어봐요.",
    spreads: [
      {
        id: "inner-voice",
        title: "Inner Voice",
        titleKo: "내면의 소리",
        cardCount: 1,
        description: "A single card to hear what your higher self wants to say.",
        descriptionKo: "내 안의 목소리를 들어봐요.",
        positions: [{ title: "Message", titleKo: "메시지" }],
      },
      {
        id: "shadow-work",
        title: "Shadow Work",
        titleKo: "그림자 탐구",
        cardCount: 4,
        description: "Meet and heal the shadow aspects within.",
        descriptionKo: "숨겨진 내 모습을 마주해요.",
        positions: [
          { title: "Shadow Aspect", titleKo: "숨겨진 모습" },
          { title: "How It Shows Up", titleKo: "어떻게 나타나는지" },
          { title: "How to Heal", titleKo: "어떻게 다룰지" },
          { title: "Lesson", titleKo: "배울 점" },
        ],
      },
      {
        id: "path-of-growth",
        title: "Path of Growth",
        titleKo: "성장 방향",
        cardCount: 5,
        description: "Understand your current spiritual lesson and next steps.",
        descriptionKo: "지금 배워야 할 것과 다음 단계.",
        positions: [
          { title: "Current Lesson", titleKo: "지금 배울 것" },
          { title: "Support", titleKo: "도움" },
          { title: "Challenge", titleKo: "어려운 점" },
          { title: "Practice", titleKo: "실천할 것" },
          { title: "Outcome", titleKo: "결과" },
        ],
      },
    ],
  },
  {
    id: "decisions-crossroads",
    category: "Decisions & Crossroads",
    categoryKo: "선택·결정",
    description: "Compare options and pick the most aligned path.",
    descriptionKo: "결정을 앞두고 있을 때 물어봐요.",
    spreads: [
      {
        id: "two-paths",
        title: "Two Paths",
        titleKo: "A vs B",
        cardCount: 6,
        description: "Contrast two options side by side and reveal the guidance between them.",
        descriptionKo: "두 선택지를 비교해봐요.",
        positions: [
          { title: "Past Influence", titleKo: "배경" },
          { title: "Path A - Strength", titleKo: "A의 장점" },
          { title: "Path A - Risk", titleKo: "A의 리스크" },
          { title: "Path B - Strength", titleKo: "B의 장점" },
          { title: "Path B - Risk", titleKo: "B의 리스크" },
          { title: "Guidance / Best Fit", titleKo: "추천" },
        ],
      },
      {
        id: "yes-no-why",
        title: "Yes / No / Why",
        titleKo: "할까 말까",
        cardCount: 3,
        description: "A concise check on feasibility plus the hidden factor you need to know.",
        descriptionKo: "해야 할지 말아야 할지 고민될 때.",
        positions: [
          { title: "Yes Energy", titleKo: "하라는 신호" },
          { title: "No Energy", titleKo: "말라는 신호" },
          { title: "Hidden Factor", titleKo: "숨은 변수" },
        ],
      },
      {
        id: "timing-window",
        title: "Timing Window",
        titleKo: "언제가 좋을까",
        cardCount: 4,
        description: "Assess when to act and how the energy shifts over time.",
        descriptionKo: "행동하기 좋은 타이밍을 봐요.",
        positions: [
          { title: "Now", titleKo: "지금" },
          { title: "1-3 Months", titleKo: "1~3개월 후" },
          { title: "3-6 Months", titleKo: "3~6개월 후" },
          { title: "Key Action to Unlock Timing", titleKo: "해야 할 행동" },
        ],
      },
    ],
  },
  {
    id: "self-discovery",
    category: "Self-Discovery",
    categoryKo: "자기 탐색",
    description: "Deeper inner work beyond the day-to-day.",
    descriptionKo: "나에 대해 더 깊이 알아봐요.",
    spreads: [
      {
        id: "identity-core",
        title: "Identity Core",
        titleKo: "나는 누구인가",
        cardCount: 5,
        description: "Clarify your core driver, blind spot, and the gift you bring.",
        descriptionKo: "내 본질과 강점, 약점을 살펴봐요.",
        positions: [
          { title: "Core Drive", titleKo: "핵심 동기" },
          { title: "Deep Need", titleKo: "내면의 욕구" },
          { title: "Blind Spot", titleKo: "못 보는 부분" },
          { title: "Unique Gift", titleKo: "내 강점" },
          { title: "Integration Step", titleKo: "다음 단계" },
        ],
      },
      {
        id: "shadow-integration",
        title: "Shadow Integration",
        titleKo: "내면 통합",
        cardCount: 6,
        description: "Extend shadow work into practical integration steps.",
        descriptionKo: "숨겨진 내 모습을 받아들이는 법.",
        positions: [
          { title: "Shadow Pattern", titleKo: "반복되는 패턴" },
          { title: "Trigger", titleKo: "자극 요인" },
          { title: "Protective Role", titleKo: "방어 기제" },
          { title: "Cost", titleKo: "치르는 대가" },
          { title: "Healing Practice", titleKo: "치유 방법" },
          { title: "Integration Signal", titleKo: "성공 신호" },
        ],
      },
    ],
  },
  {
    id: "daily-reading",
    category: "Daily Reading",
    categoryKo: "오늘의 운세",
    description: "A quick look at the energies of your day.",
    descriptionKo: "오늘 하루를 미리 봐요.",
    spreads: [
      {
        id: "day-card",
        title: "Card of the Day",
        titleKo: "오늘의 카드",
        cardCount: 1,
        description: "A single card to guide your day.",
        descriptionKo: "오늘의 키워드 한 장.",
        positions: [{ title: "Message", titleKo: "메시지" }],
      },
      {
        id: "three-times",
        title: "The Day's Journey",
        titleKo: "하루 흐름",
        cardCount: 3,
        description: "A look at the energies of your morning, afternoon, and evening.",
        descriptionKo: "아침, 낮, 저녁 흐름을 봐요.",
        positions: [
          { title: "Morning", titleKo: "아침" },
          { title: "Afternoon", titleKo: "낮" },
          { title: "Evening", titleKo: "저녁" }
        ],
      },
      {
        id: "weekly-forecast",
        title: "Weekly Forecast",
        titleKo: "이번 주 운세",
        cardCount: 7,
        description: "A card for each day of the week.",
        descriptionKo: "월요일부터 일요일까지 일주일 흐름.",
        positions: [
          { title: "Monday", titleKo: "월요일" },
          { title: "Tuesday", titleKo: "화요일" },
          { title: "Wednesday", titleKo: "수요일" },
          { title: "Thursday", titleKo: "목요일" },
          { title: "Friday", titleKo: "금요일" },
          { title: "Saturday", titleKo: "토요일" },
          { title: "Sunday", titleKo: "일요일" }
        ],
      },
      {
        id: "oracle-message",
        title: "Oracle Message",
        titleKo: "오라클 메시지",
        cardCount: 1,
        description: "A special message the universe wants you to hear.",
        descriptionKo: "우주가 전하고 싶은 메시지.",
        positions: [{ title: "Message", titleKo: "메시지" }],
      },
    ],
  },
];
