// Element Mapping Utilities
// Converts between Saju (Five Elements) and Western (Four Elements) systems

import { SIGN_TO_ELEMENT } from '@/lib/destiny-matrix/data/layer1-element-core';
import type { WesternElement } from '@/lib/destiny-matrix/types';
import type { FiveElement } from '@/lib/Saju/types';

/**
 * Maps Saju Five Element to Western Four Element system
 *
 * This function bridges the traditional East Asian Five Elements (오행: 목/화/토/금/수)
 * with the Western Four Elements (fire/earth/air/water) system used in astrology.
 *
 * Mapping logic:
 * - 목 (Wood) → air (growth, expansion, communication)
 * - 화 (Fire) → fire (direct correspondence)
 * - 토 (Earth) → earth (direct correspondence)
 * - 금 (Metal) → air (sharpness, clarity, decisiveness)
 * - 수 (Water) → water (direct correspondence)
 *
 * @param element - Saju element in Korean ('목', '화', '토', '금', '수') or English ('wood', 'fire', etc.)
 * @returns Western element as lowercase string ('fire', 'earth', 'air', or 'water')
 *
 * @example
 * ```typescript
 * mapSajuElementToWestern('목') // Returns: 'air'
 * mapSajuElementToWestern('fire') // Returns: 'fire'
 * ```
 */
export function mapSajuElementToWestern(element: string): 'fire' | 'earth' | 'air' | 'water' {
  const mapping: Record<string, 'fire' | 'earth' | 'air' | 'water'> = {
    '목': 'air',    // Wood → Air (growth, expansion)
    '화': 'fire',   // Fire → Fire
    '토': 'earth',  // Earth → Earth
    '금': 'air',    // Metal → Air (sharpness, decisiveness)
    '수': 'water',  // Water → Water
    'wood': 'air',
    'fire': 'fire',
    'earth': 'earth',
    'metal': 'air',
    'water': 'water',
  };
  return mapping[element] || 'earth';
}

/**
 * Maps English element names to Korean Five Elements (Saju system)
 *
 * Converts lowercase English element names to their Korean equivalents used in Saju.
 *
 * @param el - English element name ('wood', 'fire', 'earth', 'metal', 'water')
 * @returns Korean Five Element character ('목', '화', '토', '금', '수'), defaults to '토' if not found
 *
 * @example
 * ```typescript
 * mapSajuElementToKo('wood') // Returns: '목'
 * mapSajuElementToKo('unknown') // Returns: '토' (default)
 * ```
 */
export function mapSajuElementToKo(el: string): FiveElement {
  const map: Record<string, FiveElement> = {
    wood: '목',
    fire: '화',
    earth: '토',
    metal: '금',
    water: '수',
  };
  return map[el] || '토';
}

/**
 * Gets Western Four Element from zodiac sign
 *
 * Converts a zodiac sign name to its associated Western element according to
 * traditional astrological correspondences:
 * - Fire: Aries, Leo, Sagittarius
 * - Earth: Taurus, Virgo, Capricorn
 * - Air: Gemini, Libra, Aquarius
 * - Water: Cancer, Scorpio, Pisces
 *
 * @param sign - Zodiac sign name (case-insensitive, e.g., 'aries', 'Taurus', 'GEMINI')
 * @returns Western element ('fire', 'earth', 'air', or 'water'), defaults to 'earth' if not found
 *
 * @example
 * ```typescript
 * getWestElementFromSign('Leo') // Returns: 'fire'
 * getWestElementFromSign('pisces') // Returns: 'water'
 * ```
 */
export function getWestElementFromSign(sign: string): WesternElement {
  const normalized = sign?.charAt(0).toUpperCase() + sign?.slice(1).toLowerCase();
  return SIGN_TO_ELEMENT[normalized] || 'earth';
}

/**
 * Five Element names in Korean
 */
export const elementNameKo: Record<string, string> = {
  '목': '나무',
  '화': '불',
  '토': '흙',
  '금': '쇠',
  '수': '물',
};

/**
 * Western element names in Korean
 */
export const westElementNameKo: Record<string, string> = {
  'fire': '불',
  'earth': '흙',
  'air': '바람',
  'water': '물',
};

/**
 * Five Element Relationship Functions
 * Used for health analysis and element interactions
 */

/**
 * Gets the element generated by this element (생 관계 / Generating Cycle)
 *
 * Returns the element that is nurtured or produced by the input element according
 * to the Five Elements Generating Cycle (상생):
 * - 목 (Wood) generates 화 (Fire)
 * - 화 (Fire) generates 토 (Earth)
 * - 토 (Earth) generates 금 (Metal)
 * - 금 (Metal) generates 수 (Water)
 * - 수 (Water) generates 목 (Wood)
 *
 * @param el - The source Five Element ('목', '화', '토', '금', '수')
 * @returns The element generated by the source element
 *
 * @example
 * ```typescript
 * getGeneratedElement('목') // Returns: '화' (Wood generates Fire)
 * getGeneratedElement('수') // Returns: '목' (Water generates Wood)
 * ```
 */
export function getGeneratedElement(el: FiveElement): FiveElement {
  const cycle: Record<FiveElement, FiveElement> = {
    '목': '화',
    '화': '토',
    '토': '금',
    '금': '수',
    '수': '목',
  };
  return cycle[el] || '토';
}

/**
 * Gets the element controlled/dominated by this element (극 관계 / Controlling Cycle)
 *
 * Returns the element that is restrained or controlled by the input element according
 * to the Five Elements Controlling Cycle (상극):
 * - 목 (Wood) controls 토 (Earth)
 * - 화 (Fire) controls 금 (Metal)
 * - 토 (Earth) controls 수 (Water)
 * - 금 (Metal) controls 목 (Wood)
 * - 수 (Water) controls 화 (Fire)
 *
 * @param el - The controlling Five Element ('목', '화', '토', '금', '수')
 * @returns The element controlled by the source element
 *
 * @example
 * ```typescript
 * getControlledElement('목') // Returns: '토' (Wood controls Earth)
 * getControlledElement('수') // Returns: '화' (Water controls Fire)
 * ```
 */
export function getControlledElement(el: FiveElement): FiveElement {
  const cycle: Record<FiveElement, FiveElement> = {
    '목': '토',
    '화': '금',
    '토': '수',
    '금': '목',
    '수': '화',
  };
  return cycle[el] || '토';
}

/**
 * Gets the element that controls this element (역극 관계 / Reverse Controlling)
 *
 * Returns the element that restrains or dominates the input element according
 * to the reverse of the Five Elements Controlling Cycle:
 * - 목 (Wood) is controlled by 금 (Metal)
 * - 화 (Fire) is controlled by 수 (Water)
 * - 토 (Earth) is controlled by 목 (Wood)
 * - 금 (Metal) is controlled by 화 (Fire)
 * - 수 (Water) is controlled by 토 (Earth)
 *
 * @param el - The controlled Five Element ('목', '화', '토', '금', '수')
 * @returns The element that controls the input element
 *
 * @example
 * ```typescript
 * getControllerElement('목') // Returns: '금' (Metal controls Wood)
 * getControllerElement('화') // Returns: '수' (Water controls Fire)
 * ```
 */
export function getControllerElement(el: FiveElement): FiveElement {
  const cycle: Record<FiveElement, FiveElement> = {
    '목': '금',
    '화': '수',
    '토': '목',
    '금': '화',
    '수': '토',
  };
  return cycle[el] || '토';
}

/**
 * Gets the element that generates this element (역생 관계 / Reverse Generating)
 *
 * Returns the element that nourishes or produces the input element according
 * to the reverse of the Five Elements Generating Cycle:
 * - 목 (Wood) is generated by 수 (Water)
 * - 화 (Fire) is generated by 목 (Wood)
 * - 토 (Earth) is generated by 화 (Fire)
 * - 금 (Metal) is generated by 토 (Earth)
 * - 수 (Water) is generated by 금 (Metal)
 *
 * @param el - The generated Five Element ('목', '화', '토', '금', '수')
 * @returns The element that generates the input element
 *
 * @example
 * ```typescript
 * getGeneratorElement('목') // Returns: '수' (Water generates Wood)
 * getGeneratorElement('화') // Returns: '목' (Wood generates Fire)
 * ```
 */
export function getGeneratorElement(el: FiveElement): FiveElement {
  const cycle: Record<FiveElement, FiveElement> = {
    '목': '수',
    '화': '목',
    '토': '화',
    '금': '토',
    '수': '금',
  };
  return cycle[el] || '토';
}
