// src/lib/astrology/signCombinations.ts
//
// Static interpretation data for two-planet Sign × Sign combinations.
//
// Astrology's most diagnostic patterns are not single placements but pairs:
// Sun × Moon (identity × emotion), Venus × Mars (love × desire), and the
// Sun/Moon × Ascendant pairs (inner × outer). This file stores plain-language
// readings for each combination so the LLM layer or result pages can ground
// their prose without re-deriving the meaning.
//
// Phase 1: Sun × Moon only — 12 × 12 = 144 entries.
// Venus × Mars, Sun × Ascendant, Moon × Ascendant will follow in later PRs.
//
// Tone:
//   - LifeReport 6th-pass naturalization. Zero jargon.
//   - 2-3 short sentences per language.
//   - Concrete and warm, not poetic or abstract.

import type { ZodiacName } from './interpretations'

export type SignCombinationPair =
  | 'sun_moon'
  | 'venus_mars'
  | 'sun_asc'
  | 'moon_asc'

export interface SignCombination {
  pair: SignCombinationPair
  sign1: ZodiacName
  sign2: ZodiacName
  ko: string
  en: string
  keywords_ko: string[]
  keywords_en: string[]
}

// ============================================================
// Sun × Moon — identity × emotion
// sign1 = Sun sign, sign2 = Moon sign
// ============================================================

const SUN_MOON_COMBINATIONS: SignCombination[] = [
  // ---------- Sun in Aries ----------
  {
    pair: 'sun_moon',
    sign1: 'Aries', sign2: 'Aries',
    ko: '의지와 감정이 한 방향으로 달리는 결이에요. 망설임이 적고, 원하는 게 분명하면 그대로 움직여요.',
    en: 'Will and feeling pull in the same direction. Little hesitation, and once the want is clear the move follows.',
    keywords_ko: ['단호함', '즉결', '뜨거운 추진력'],
    keywords_en: ['decisiveness', 'immediacy', 'hot drive'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Aries', sign2: 'Taurus',
    ko: '앞으로 나가려는 의지에 안정 본능이 닻처럼 달려 있어요. 뛰쳐나가다가도 내면이 편한 자리를 자꾸 찾게 돼요.',
    en: 'A forward-pushing will anchored by a body that wants comfort. The drive starts fast, then circles back to what feels settled.',
    keywords_ko: ['추진과 안정', '속도와 무게', '닻 달린 열정'],
    keywords_en: ['drive and anchor', 'speed with weight', 'grounded heat'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Aries', sign2: 'Gemini',
    ko: '의지가 빠르고 감정도 가벼워서 한 곳에 오래 머물지 않아요. 호기심과 행동력이 같은 박자로 움직여요.',
    en: 'Both the will and the mood are quick, so nothing stays in one place for long. Curiosity and action share the same tempo.',
    keywords_ko: ['민첩함', '호기심', '경쾌한 행동'],
    keywords_en: ['agility', 'curiosity', 'light action'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Aries', sign2: 'Cancer',
    ko: '겉으로는 대담하지만 마음 안쪽은 부드럽고 보호받고 싶어요. 행동은 빠른데 감정 회복엔 시간이 필요해요.',
    en: 'Bold on the outside, soft and protective on the inside. The action is fast, but the feelings need more time to recover.',
    keywords_ko: ['겉바속촉', '돌봄 욕구', '뜨거운 마음'],
    keywords_en: ['tough outside soft inside', 'need for care', 'warm core'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Aries', sign2: 'Leo',
    ko: '자기 표현이 시원하고 감정도 당당해요. 좋아하는 일에 빠지면 망설임 없이 전부를 보여줘요.',
    en: 'Self-expression runs bright and the heart is proud. When something matters, all of it shows up without hesitation.',
    keywords_ko: ['당당함', '뜨거운 자기 표현', '거침없는 활력'],
    keywords_en: ['confidence', 'bright expression', 'unguarded vitality'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Aries', sign2: 'Virgo',
    ko: '뛰어들기 좋아하지만 내면은 꼼꼼하고 정돈을 좋아해요. 행동 뒤에 늘 점검과 다듬기가 따라와요.',
    en: 'Likes to jump in, but the inner self quietly checks and tidies up. After every move there is a small review and edit.',
    keywords_ko: ['추진과 점검', '실속 있는 열정', '다듬는 손'],
    keywords_en: ['drive with review', 'practical heat', 'editing instinct'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Aries', sign2: 'Libra',
    ko: '자기 의지는 분명한데, 감정은 상대와의 균형을 신경 써요. 혼자 달리다가도 누구 한 명은 꼭 옆에 두고 싶어해요.',
    en: 'The will is clear, but the heart keeps weighing the other person. Even when running alone, it wants someone close by.',
    keywords_ko: ['독립과 관계', '균형 감각', '함께 가는 추진'],
    keywords_en: ['solo with company', 'balance instinct', 'shared momentum'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Aries', sign2: 'Scorpio',
    ko: '겉의 추진력 아래 깊고 강한 감정이 흘러요. 한번 꽂히면 끝까지 가는 집요함이 있어요.',
    en: 'Underneath the forward energy runs a deep, intense current. Once something hooks the heart, it holds on all the way.',
    keywords_ko: ['깊은 집중', '끝까지', '강한 욕망'],
    keywords_en: ['deep focus', 'all the way', 'strong want'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Aries', sign2: 'Sagittarius',
    ko: '의지도 감정도 멀리 보는 결이에요. 새 길, 새 풍경에 반응이 빠르고 답답한 자리를 못 견뎌요.',
    en: 'Both the will and the mood look toward the horizon. New paths and wider views light it up fast, and tight spaces are hard.',
    keywords_ko: ['모험심', '확장 감각', '시원함'],
    keywords_en: ['adventure', 'expansive mood', 'open air'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Aries', sign2: 'Capricorn',
    ko: '뜨거운 추진력 위에 차분한 자제가 얹혀 있어요. 즉흥적으로 보여도 결국엔 끝을 보는 사람이에요.',
    en: 'Hot drive paired with a quiet, steady restraint. It can look impulsive, but the finish line is always in mind.',
    keywords_ko: ['추진과 절제', '결과 중심', '뜨거운 책임감'],
    keywords_en: ['drive with restraint', 'result-driven', 'committed heat'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Aries', sign2: 'Aquarius',
    ko: '내 길을 가는 의지가 분명하고, 감정도 한 발 떨어져 자기 색을 지켜요. 휩쓸리는 걸 가장 싫어해요.',
    en: 'A clear "my own path" will, with a mood that keeps its own color from a small distance. Being swept along is the worst feeling.',
    keywords_ko: ['독립성', '자기 색', '거리감'],
    keywords_en: ['independence', 'own color', 'distance'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Aries', sign2: 'Pisces',
    ko: '행동은 빠른데 마음은 잘 흔들리고 잘 스며들어요. 바깥은 단단해 보여도 안쪽은 여리고 공감이 깊어요.',
    en: 'Quick to act, but easily moved and easily soaked. Solid-looking on the outside, soft and empathic underneath.',
    keywords_ko: ['외강내유', '공감과 추진', '여린 용기'],
    keywords_en: ['tough action soft heart', 'empathic drive', 'tender courage'],
  },

  // ---------- Sun in Taurus ----------
  {
    pair: 'sun_moon',
    sign1: 'Taurus', sign2: 'Aries',
    ko: '겉은 차분한데 안에는 의외의 추진력이 살아 있어요. 평소엔 느긋해도 결정적일 땐 단호하게 움직여요.',
    en: 'Calm on the surface, with a surprising push hidden underneath. Usually unhurried, but decisive when it counts.',
    keywords_ko: ['차분한 추진', '느긋한 결단', '숨은 힘'],
    keywords_en: ['quiet drive', 'unhurried decision', 'hidden force'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Taurus', sign2: 'Taurus',
    ko: '안정과 감각이 두 겹으로 깔린 결이에요. 좋아하는 것이 분명하고, 바꿔야 할 이유가 분명할 때만 바꿔요.',
    en: 'Stability and sensuality run in a double layer. The likes are clear, and change happens only when the reason is clear too.',
    keywords_ko: ['안정감', '확고한 취향', '느린 변화'],
    keywords_en: ['stability', 'firm taste', 'slow change'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Taurus', sign2: 'Gemini',
    ko: '본바탕은 차분한데 내면은 호기심이 많고 가벼워요. 한 자리에 머물면서도 생각은 자주 떠다녀요.',
    en: 'A calm base with a curious, lighter inner mood. The body stays put, while the mind keeps wandering.',
    keywords_ko: ['차분한 호기심', '머물며 노는 생각', '안정 속 다양함'],
    keywords_en: ['settled curiosity', 'wandering thought', 'variety within stability'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Taurus', sign2: 'Cancer',
    ko: '안정과 돌봄이 자연스럽게 어울리는 결이에요. 좋은 공간, 따뜻한 사람을 만들고 지키는 데 마음을 다해요.',
    en: 'Stability and care fit together naturally. Making and protecting a warm space and people gets full attention.',
    keywords_ko: ['따뜻한 안정', '돌봄', '집의 감각'],
    keywords_en: ['warm stability', 'nurturing', 'sense of home'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Taurus', sign2: 'Leo',
    ko: '평소엔 조용해 보이지만 좋아하는 자리에선 환하게 표현해요. 자존심과 안정 욕구가 같은 무게로 작동해요.',
    en: 'Quiet most of the time, but bright in places that matter. Pride and a need for stability weigh about the same.',
    keywords_ko: ['은은한 자존심', '따뜻한 무대', '풍요로움'],
    keywords_en: ['quiet pride', 'warm stage', 'abundance'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Taurus', sign2: 'Virgo',
    ko: '차분하게 쌓고, 차분하게 다듬는 결이에요. 큰 소리 없이 결과를 만드는 사람에 가까워요.',
    en: 'Build quietly, refine quietly. The kind of person who gets to the result without making noise.',
    keywords_ko: ['실속', '꾸준한 다듬기', '조용한 성취'],
    keywords_en: ['substance', 'steady refining', 'quiet achievement'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Taurus', sign2: 'Libra',
    ko: '취향과 균형 감각이 강하고, 사람과 공간을 보기 좋게 만드는 일에 끌려요. 마음이 편할 때 가장 자기다워요.',
    en: 'Strong taste and a sense of balance, drawn to making people and spaces look right. Most at home when the heart is at ease.',
    keywords_ko: ['아름다움', '균형', '편안함'],
    keywords_en: ['beauty', 'balance', 'ease'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Taurus', sign2: 'Scorpio',
    ko: '겉으론 안정적인데 속엔 깊은 욕망과 집착이 흘러요. 좋아하는 것은 끝까지 지키고 끝까지 파고들어요.',
    en: 'Steady outside, with deep desire and intensity running underneath. What it loves, it holds on to all the way.',
    keywords_ko: ['깊은 애착', '집요함', '강한 보존'],
    keywords_en: ['deep attachment', 'tenacity', 'strong holding'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Taurus', sign2: 'Sagittarius',
    ko: '뿌리는 안정인데 마음은 멀리 보고 싶어해요. 일상은 단단하게 두면서 가끔 큰 풍경에 나가는 게 좋아요.',
    en: 'Rooted at the base, but the heart wants the horizon. The everyday stays solid, with occasional trips into bigger views.',
    keywords_ko: ['안정과 모험', '뿌리와 풍경', '여유로운 호기심'],
    keywords_en: ['roots and travel', 'base and horizon', 'easy curiosity'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Taurus', sign2: 'Capricorn',
    ko: '안정과 책임이 단단하게 결합된 결이에요. 시간이 걸려도 무너지지 않는 구조를 만들어요.',
    en: 'Stability and responsibility lock together tightly. It takes time, but what gets built does not fall.',
    keywords_ko: ['단단함', '책임감', '오래 가는 구조'],
    keywords_en: ['solidity', 'responsibility', 'lasting structure'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Taurus', sign2: 'Aquarius',
    ko: '겉은 보수적인데 안엔 자기만의 시각이 분명해요. 일상은 안정적으로, 생각은 자유롭게 두는 결이에요.',
    en: 'Conservative on the outside, with a distinct inner viewpoint. Routine stays steady while thinking stays free.',
    keywords_ko: ['안정 속 독창성', '자기 관점', '느린 변화'],
    keywords_en: ['original within stable', 'own view', 'slow change'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Taurus', sign2: 'Pisces',
    ko: '안정적 토양에 감성의 물이 스며드는 결이에요. 겉으론 단단하지만 내면은 따뜻하고 공감 어린 결.',
    en: 'Stable earth with a layer of soft emotional water beneath. Solid on the surface, warm and empathic within.',
    keywords_ko: ['안정과 공감', '내면의 부드러움', '실용적 감수성'],
    keywords_en: ['stable empathy', 'soft interior', 'practical sensitivity'],
  },

  // ---------- Sun in Gemini ----------
  {
    pair: 'sun_moon',
    sign1: 'Gemini', sign2: 'Aries',
    ko: '말과 생각이 빠른데, 감정도 즉시 반응해요. 흥미가 생기면 곧장 시도하는 결이에요.',
    en: 'Quick mind and speech, with feelings that respond just as fast. Interest turns into trying almost instantly.',
    keywords_ko: ['민첩한 호기심', '즉각 시도', '경쾌함'],
    keywords_en: ['quick curiosity', 'fast trial', 'lightness'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Gemini', sign2: 'Taurus',
    ko: '머리는 가볍게 움직이는데 마음은 안정된 자리를 좋아해요. 다양함을 즐기되 결국 편한 곳으로 돌아와요.',
    en: 'The mind moves lightly, but the heart prefers a settled spot. Variety is welcome, yet the comfortable place always wins.',
    keywords_ko: ['가벼운 사고와 깊은 휴식', '안정된 호기심', '취향의 닻'],
    keywords_en: ['light mind, settled rest', 'grounded curiosity', 'taste as anchor'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Gemini', sign2: 'Gemini',
    ko: '호기심과 다양성이 두 겹으로 깔린 결이에요. 한 가지에 묶이는 걸 가장 싫어하고, 늘 새 정보를 찾아요.',
    en: 'Curiosity and variety in a double layer. Being tied to one thing is the worst, and new information is always pulling.',
    keywords_ko: ['다재다능', '경쾌함', '정보의 흐름'],
    keywords_en: ['versatility', 'lightness', 'flow of information'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Gemini', sign2: 'Cancer',
    ko: '말은 가볍지만 마음은 깊고 잘 흔들려요. 사람들과 잘 어울리면서도, 진짜 편한 사람은 따로 둬요.',
    en: 'Talk runs light, but the heart runs deep and moves easily. Sociable on the surface, with a separate inner circle that feels safe.',
    keywords_ko: ['겉밝안깊', '친밀의 거리', '말과 마음의 차이'],
    keywords_en: ['light outside, deep inside', 'closeness with distance', 'gap of word and heart'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Gemini', sign2: 'Leo',
    ko: '재치와 자기 표현이 자연스럽게 어울리는 결이에요. 사람들 사이에서 환해지고 이야기로 자기를 보여줘요.',
    en: 'Wit and self-expression sit easily together. The light goes up around people, and stories carry the self forward.',
    keywords_ko: ['재치', '환한 표현', '말의 무대'],
    keywords_en: ['wit', 'bright expression', 'stage of words'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Gemini', sign2: 'Virgo',
    ko: '머리가 빠르고 내면도 분석적이에요. 정보를 모아 정리하는 일에 자연스럽게 끌려요.',
    en: 'A fast mind paired with an analytical inner mood. Gathering information and arranging it comes naturally.',
    keywords_ko: ['분석', '정리', '예리한 관찰'],
    keywords_en: ['analysis', 'tidying', 'sharp observation'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Gemini', sign2: 'Libra',
    ko: '말과 균형 감각이 잘 맞아 사람들 사이에서 편해요. 분위기를 부드럽게 만드는 결이 자연스러워요.',
    en: 'Conversation and balance fit, so being among people feels easy. Smoothing the room comes without effort.',
    keywords_ko: ['사교성', '부드러운 분위기', '말의 균형'],
    keywords_en: ['sociability', 'smooth mood', 'balanced talk'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Gemini', sign2: 'Scorpio',
    ko: '겉은 가볍게 보여도 속은 한 주제를 깊게 파고들어요. 알게 된 것은 쉽게 흘려보내지 않아요.',
    en: 'Light on the surface, with a deep dive into one subject underneath. What it learns is held tightly.',
    keywords_ko: ['표면의 가벼움, 내면의 집중', '파고드는 호기심', '비밀의 깊이'],
    keywords_en: ['light surface, deep focus', 'digging curiosity', 'private depth'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Gemini', sign2: 'Sagittarius',
    ko: '호기심과 모험심이 같은 방향으로 흘러요. 정보든 풍경이든 새로움이 곧 에너지가 돼요.',
    en: 'Curiosity and adventure flow the same way. New information or new scenery becomes energy almost at once.',
    keywords_ko: ['확장된 호기심', '여행', '의미를 찾는 정보'],
    keywords_en: ['expanded curiosity', 'travel', 'meaning in information'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Gemini', sign2: 'Capricorn',
    ko: '생각은 자유로운데 내면은 책임감이 강해요. 가볍게 말해도 일은 끝까지 챙기는 사람이에요.',
    en: 'Free thinking with a responsible inner core. The talk may sound light, but the work gets finished.',
    keywords_ko: ['가벼운 표현, 단단한 책임', '실용적 사고', '약속을 지킴'],
    keywords_en: ['light talk, solid follow-through', 'practical thought', 'keeps promises'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Gemini', sign2: 'Aquarius',
    ko: '생각과 감정 모두 자유롭고 자기 색이 분명해요. 새 아이디어를 가지고 무언가 만들어보는 결을 좋아해요.',
    en: 'Both thought and feeling run free, with a clear own color. Building something new from a fresh idea feels right.',
    keywords_ko: ['자유로운 사고', '독창성', '아이디어'],
    keywords_en: ['free thinking', 'originality', 'idea play'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Gemini', sign2: 'Pisces',
    ko: '말은 명료한데 마음은 자주 흐릿하고 잘 스며들어요. 분위기에 따라 색이 자주 바뀌는 결.',
    en: 'Clear speech with a mood that often softens and seeps. The color shifts with the room.',
    keywords_ko: ['감수성', '분위기에 민감', '말과 꿈의 사이'],
    keywords_en: ['sensitivity', 'mood-responsive', 'between word and dream'],
  },

  // ---------- Sun in Cancer ----------
  {
    pair: 'sun_moon',
    sign1: 'Cancer', sign2: 'Aries',
    ko: '돌봄의 본성을 가지면서도 자기 자리를 지키는 의지가 분명해요. 가족·가까운 사람 일에 가장 빨리 움직여요.',
    en: 'A caring nature paired with a clear will to protect its own. Moves fastest when family or close ones are involved.',
    keywords_ko: ['보호 본능', '결단력', '돌봄의 행동'],
    keywords_en: ['protective instinct', 'decisiveness', 'caring action'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Cancer', sign2: 'Taurus',
    ko: '따뜻함과 안정감이 자연스럽게 어울리는 결이에요. 익숙하고 편안한 자리에서 가장 자기다워요.',
    en: 'Warmth and stability fit together easily. Most itself in familiar, comfortable settings.',
    keywords_ko: ['편안함', '따뜻함', '익숙함'],
    keywords_en: ['comfort', 'warmth', 'familiarity'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Cancer', sign2: 'Gemini',
    ko: '마음은 따뜻한데 생각은 빠르고 가벼워요. 사람을 챙기면서도 가볍게 말 거는 결이에요.',
    en: 'A warm heart with a quick, light mind. Cares about people, but checks in with a casual touch.',
    keywords_ko: ['따뜻한 사교', '잔잔한 말', '챙기는 호기심'],
    keywords_en: ['warm sociability', 'gentle talk', 'caring curiosity'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Cancer', sign2: 'Cancer',
    ko: '감정과 돌봄이 두 겹으로 깔린 결이에요. 사람들의 분위기에 매우 민감하고, 안전한 자리를 무엇보다 중요하게 여겨요.',
    en: 'Feeling and care in a double layer. Very tuned to the mood of others, with safety valued above almost anything.',
    keywords_ko: ['깊은 감수성', '돌봄', '안전감'],
    keywords_en: ['deep sensitivity', 'nurturing', 'sense of safety'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Cancer', sign2: 'Leo',
    ko: '따뜻함 위에 환한 자기 표현이 얹혀 있어요. 사랑하는 사람을 마음껏 빛내고 싶어해요.',
    en: 'Warmth underneath, bright self-expression on top. Wants to light up the people it loves.',
    keywords_ko: ['따뜻한 자존심', '돌봄의 빛', '환한 애정'],
    keywords_en: ['warm pride', 'caring light', 'bright affection'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Cancer', sign2: 'Virgo',
    ko: '돌봄을 구체적인 행동으로 옮기는 결이에요. 작은 도움과 정돈이 곧 애정의 표현이 돼요.',
    en: 'Care translated into specific small actions. Tidying and small helps become the language of affection.',
    keywords_ko: ['세심한 돌봄', '실용적 애정', '챙김의 손'],
    keywords_en: ['careful nurturing', 'practical affection', 'helping hand'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Cancer', sign2: 'Libra',
    ko: '돌봄과 균형이 어울리는 결이에요. 갈등을 부드럽게 풀어주고 사람 사이를 잘 이어요.',
    en: 'Care meets balance. Smooths conflict gently and stitches people together with ease.',
    keywords_ko: ['중재', '부드러움', '관계의 다리'],
    keywords_en: ['mediation', 'softness', 'bridge between people'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Cancer', sign2: 'Scorpio',
    ko: '감정의 두께가 두 겹으로 강한 결이에요. 사랑도 신뢰도 한번 형성되면 깊고 오래 가요.',
    en: 'Emotion doubled in thickness. Love and trust, once formed, run deep and last.',
    keywords_ko: ['깊은 정', '강한 신뢰', '오래 가는 마음'],
    keywords_en: ['deep bond', 'strong trust', 'lasting heart'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Cancer', sign2: 'Sagittarius',
    ko: '돌봄과 자유로움이 같이 있어요. 따뜻한 자리를 가지면서도 가끔은 큰 풍경에 나가야 숨이 트여요.',
    en: 'Care and freedom share the space. Wants a warm home, but also needs occasional trips into wider views to breathe.',
    keywords_ko: ['집과 여행', '따뜻한 자유', '시야의 환기'],
    keywords_en: ['home and travel', 'warm freedom', 'wider breath'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Cancer', sign2: 'Capricorn',
    ko: '따뜻한 본성과 단단한 책임이 같이 있어요. 가족·소속을 지키는 일에 깊이 헌신하는 결이에요.',
    en: 'A warm nature paired with solid responsibility. Deeply committed to protecting family and belonging.',
    keywords_ko: ['헌신', '책임감 있는 돌봄', '내·외부의 균형'],
    keywords_en: ['devotion', 'responsible care', 'balance inside and out'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Cancer', sign2: 'Aquarius',
    ko: '따뜻한 마음에 한 발 떨어진 관점이 같이 있어요. 사람은 챙기되 휘둘리지 않으려고 해요.',
    en: 'A warm heart with a slight inner distance. Cares for people, but tries not to get swept up.',
    keywords_ko: ['거리감 있는 돌봄', '독립적 애정', '관점 유지'],
    keywords_en: ['care with space', 'independent affection', 'kept perspective'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Cancer', sign2: 'Pisces',
    ko: '감정과 공감이 두 겹으로 깊은 결이에요. 사람과 분위기에 자연스럽게 녹아들고 잘 흔들려요.',
    en: 'Feeling and empathy in a deep double layer. Easily blends into people and atmosphere, easily moved.',
    keywords_ko: ['깊은 공감', '감수성', '스며드는 마음'],
    keywords_en: ['deep empathy', 'sensitivity', 'merging heart'],
  },

  // ---------- Sun in Leo ----------
  {
    pair: 'sun_moon',
    sign1: 'Leo', sign2: 'Aries',
    ko: '자기 표현과 의지가 두 겹으로 환해요. 좋아하는 일에 망설임 없이 자기를 던지는 결이에요.',
    en: 'Self-expression and will both turned up bright. Throws itself in without hesitation when something matters.',
    keywords_ko: ['뜨거운 자기 표현', '용기', '거침없는 빛'],
    keywords_en: ['bold expression', 'courage', 'unguarded brightness'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Leo', sign2: 'Taurus',
    ko: '환한 자존심에 안정과 풍요로움이 더해진 결이에요. 좋아하는 것을 오래 즐기고 싶어해요.',
    en: 'A bright pride with added stability and abundance. Wants to enjoy the things it loves for a long time.',
    keywords_ko: ['풍요로움', '따뜻한 자존심', '오래 가는 즐거움'],
    keywords_en: ['abundance', 'warm pride', 'lasting enjoyment'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Leo', sign2: 'Gemini',
    ko: '환한 표현에 재치와 호기심이 더해져요. 사람들 사이에서 자연스럽게 무대를 만드는 결이에요.',
    en: 'Bright expression with added wit and curiosity. Builds a small stage among people without trying.',
    keywords_ko: ['재치 있는 무대', '환한 사교', '이야기로 빛남'],
    keywords_en: ['witty stage', 'bright sociability', 'shining through stories'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Leo', sign2: 'Cancer',
    ko: '환한 빛 아래 따뜻한 돌봄이 흐르는 결이에요. 사랑하는 사람을 빛나게 해주는 일에 마음을 다해요.',
    en: 'Warm care running under the bright light. Puts heart into making the people it loves shine.',
    keywords_ko: ['빛나는 애정', '돌봄의 빛', '따뜻한 환함'],
    keywords_en: ['shining affection', 'caring light', 'warm brightness'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Leo', sign2: 'Leo',
    ko: '자기 표현과 자존심이 두 겹으로 환한 결이에요. 무대가 분명할 때 가장 자기다워요.',
    en: 'Self-expression and pride doubled into a bright signal. Most itself when there is a clear stage.',
    keywords_ko: ['무대 본능', '환한 자기', '큰 마음'],
    keywords_en: ['stage instinct', 'radiant self', 'big heart'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Leo', sign2: 'Virgo',
    ko: '환한 표현 뒤에 꼼꼼한 점검이 자리해요. 보여주기 전에 한번 더 다듬어두는 결이에요.',
    en: 'Quiet attention to detail behind the bright expression. Trims and polishes once more before showing.',
    keywords_ko: ['다듬어진 표현', '실속 있는 빛', '준비된 무대'],
    keywords_en: ['polished expression', 'substantial light', 'prepared stage'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Leo', sign2: 'Libra',
    ko: '환함과 균형이 자연스럽게 어울려요. 사람들 사이에서 보기 좋고, 갈등도 매끄럽게 풀어요.',
    en: 'Brightness and balance fit easily. Looks right among people and smooths conflict gracefully.',
    keywords_ko: ['우아함', '환한 관계', '보기 좋은 빛'],
    keywords_en: ['grace', 'bright relations', 'good-looking light'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Leo', sign2: 'Scorpio',
    ko: '환한 자기 표현 아래 강한 감정이 흘러요. 좋아하는 것에 전부를 거는 결이에요.',
    en: 'Strong feeling running under the bright expression. Goes all in on what it loves.',
    keywords_ko: ['전부를 거는 마음', '뜨거운 집중', '깊은 환함'],
    keywords_en: ['all-in heart', 'intense focus', 'deep brightness'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Leo', sign2: 'Sagittarius',
    ko: '환함과 모험심이 같이 가는 결이에요. 큰 풍경에서 자기를 표현하는 일에 자연스럽게 끌려요.',
    en: 'Brightness and adventure run together. Drawn to expressing the self in wider scenes.',
    keywords_ko: ['넓은 무대', '환한 모험', '시원한 자기'],
    keywords_en: ['big stage', 'bright adventure', 'expansive self'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Leo', sign2: 'Capricorn',
    ko: '환한 자존심과 단단한 책임이 같이 있어요. 빛을 내되 결과로 증명하는 결.',
    en: 'Bright pride and solid responsibility together. Shines, but proves it with results.',
    keywords_ko: ['결과로 빛남', '책임감 있는 자존심', '단단한 표현'],
    keywords_en: ['result-backed shine', 'responsible pride', 'solid expression'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Leo', sign2: 'Aquarius',
    ko: '환한 자기 표현에 독자적 관점이 더해진 결이에요. 빛을 내되 흐름에 휩쓸리진 않아요.',
    en: 'Bright expression with an added independent view. Shines, but never carried by the current.',
    keywords_ko: ['독창적 빛', '자기 색', '자유로운 무대'],
    keywords_en: ['original light', 'own color', 'free stage'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Leo', sign2: 'Pisces',
    ko: '환한 표현 아래 부드럽고 감성적인 마음이 흘러요. 무대 위에서도 분위기에 자연스럽게 녹아들어요.',
    en: 'A soft, emotional current under the bright expression. Even on stage, blends into the mood.',
    keywords_ko: ['감성적 빛', '부드러운 무대', '공감 어린 환함'],
    keywords_en: ['emotional light', 'soft stage', 'empathic brightness'],
  },

  // ---------- Sun in Virgo ----------
  {
    pair: 'sun_moon',
    sign1: 'Virgo', sign2: 'Aries',
    ko: '꼼꼼한 본성에 의외의 추진력이 깔린 결이에요. 정리해두면 단번에 움직이는 사람이에요.',
    en: 'A careful base with a surprising forward push underneath. Once things are tidied, the move is decisive.',
    keywords_ko: ['단호한 정돈', '실속 있는 추진', '준비된 행동'],
    keywords_en: ['decisive tidying', 'practical drive', 'prepared action'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Virgo', sign2: 'Taurus',
    ko: '실용적이고 차분한 결이 두 겹으로 깔려 있어요. 작고 단단한 결과를 꾸준히 쌓는 사람이에요.',
    en: 'A practical, calm base in a double layer. Builds small, solid results steadily over time.',
    keywords_ko: ['실속', '꾸준함', '단단한 일상'],
    keywords_en: ['substance', 'steadiness', 'solid everyday'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Virgo', sign2: 'Gemini',
    ko: '분석과 호기심이 같은 방향으로 흘러요. 정보를 자세히 보고 정리하는 일에 자연스럽게 끌려요.',
    en: 'Analysis and curiosity flow the same way. Drawn to looking closely at information and arranging it.',
    keywords_ko: ['예리한 관찰', '분석', '정보 정리'],
    keywords_en: ['sharp observation', 'analysis', 'tidy information'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Virgo', sign2: 'Cancer',
    ko: '꼼꼼함과 돌봄이 어울리는 결이에요. 작은 챙김으로 사람을 편안하게 만드는 사람이에요.',
    en: 'Care and detail fit together. Small acts of attention make people comfortable.',
    keywords_ko: ['세심한 챙김', '돌봄의 손', '편안함을 만드는 사람'],
    keywords_en: ['careful attention', 'helping hand', 'comfort-maker'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Virgo', sign2: 'Leo',
    ko: '꼼꼼한 본성 위에 환한 자존심이 얹혀 있어요. 잘 다듬은 결과를 떳떳하게 보여주는 결이에요.',
    en: 'Bright pride on top of a careful base. Shows polished work openly, with quiet confidence.',
    keywords_ko: ['다듬어진 자부심', '실속 있는 빛', '준비된 무대'],
    keywords_en: ['polished pride', 'substantial light', 'prepared stage'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Virgo', sign2: 'Virgo',
    ko: '분석과 정돈이 두 겹으로 강한 결이에요. 작은 차이를 보는 눈이 매우 예민해요.',
    en: 'Analysis and order in a double layer. The eye for small differences is very fine.',
    keywords_ko: ['예민한 관찰', '꼼꼼함', '정돈 본능'],
    keywords_en: ['fine observation', 'meticulousness', 'order instinct'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Virgo', sign2: 'Libra',
    ko: '실용성과 균형이 같이 있어요. 사람과 일을 보기 좋고 쓸모 있게 정돈하는 결이에요.',
    en: 'Practicality and balance together. Arranges people and tasks to look right and work well.',
    keywords_ko: ['균형 잡힌 정돈', '쓸모 있는 아름다움', '관계의 정리'],
    keywords_en: ['balanced order', 'useful beauty', 'relational tidying'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Virgo', sign2: 'Scorpio',
    ko: '분석과 깊이 있는 감정이 같이 가는 결이에요. 한번 파고들면 끝까지 들여다보는 사람이에요.',
    en: 'Analysis paired with deep emotion. Once it digs in, it looks all the way down.',
    keywords_ko: ['깊은 분석', '집중', '본질 추구'],
    keywords_en: ['deep analysis', 'focus', 'getting to the root'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Virgo', sign2: 'Sagittarius',
    ko: '꼼꼼한 손에 큰 시야가 더해진 결이에요. 작은 일을 살피면서도 의미와 큰 그림을 잊지 않아요.',
    en: 'A careful hand with a wider view added. Looks at small things while keeping meaning and the big picture in mind.',
    keywords_ko: ['디테일과 의미', '큰 그림', '실용적 비전'],
    keywords_en: ['detail and meaning', 'big picture', 'practical vision'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Virgo', sign2: 'Capricorn',
    ko: '실용성과 책임감이 두 겹으로 단단한 결이에요. 시간을 들여 단단한 구조를 만들어요.',
    en: 'Practicality and responsibility in a solid double layer. Builds a sturdy structure over time.',
    keywords_ko: ['끈기', '책임감', '오래 가는 결과'],
    keywords_en: ['perseverance', 'responsibility', 'lasting result'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Virgo', sign2: 'Aquarius',
    ko: '꼼꼼함에 독자적 관점이 더해진 결이에요. 시스템을 분석하고 새로 짜는 일을 좋아해요.',
    en: 'Careful detail with an independent view. Enjoys analyzing systems and rebuilding them differently.',
    keywords_ko: ['시스템 사고', '독창성', '분석적 자유'],
    keywords_en: ['systems thinking', 'originality', 'analytic freedom'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Virgo', sign2: 'Pisces',
    ko: '분석과 감수성이 같이 있는 결이에요. 작은 디테일을 챙기면서도 사람의 분위기를 부드럽게 읽어요.',
    en: 'Analysis and sensitivity together. Takes care of fine detail while reading the mood softly.',
    keywords_ko: ['디테일과 공감', '부드러운 정돈', '섬세한 감수성'],
    keywords_en: ['detail with empathy', 'soft tidying', 'delicate sensitivity'],
  },

  // ---------- Sun in Libra ----------
  {
    pair: 'sun_moon',
    sign1: 'Libra', sign2: 'Aries',
    ko: '균형 감각에 의외의 추진력이 살아 있어요. 평소엔 부드럽지만 자기 자리를 지킬 땐 단호해요.',
    en: 'Balance with a hidden forward push. Usually gentle, decisive when defending its place.',
    keywords_ko: ['부드러움과 결단', '관계 속 자기 자리', '균형 잡힌 용기'],
    keywords_en: ['gentleness and decision', 'self in relation', 'balanced courage'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Libra', sign2: 'Taurus',
    ko: '균형 감각과 안정된 취향이 같이 있어요. 보기 좋고 편안한 자리를 만드는 일에 자연스럽게 끌려요.',
    en: 'Balance and settled taste together. Drawn to making spaces that look right and feel easy.',
    keywords_ko: ['편안한 아름다움', '안정된 취향', '여유로운 균형'],
    keywords_en: ['easy beauty', 'settled taste', 'comfortable balance'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Libra', sign2: 'Gemini',
    ko: '관계와 사고가 가볍고 부드러운 결이에요. 사람들 사이의 분위기를 자연스럽게 읽고 풀어줘요.',
    en: 'Light, smooth relations and thinking. Reads the mood among people and eases it without effort.',
    keywords_ko: ['사교성', '부드러운 사고', '관계의 흐름'],
    keywords_en: ['sociability', 'smooth thinking', 'flow in relations'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Libra', sign2: 'Cancer',
    ko: '관계의 균형에 따뜻한 돌봄이 더해진 결이에요. 사람 사이를 부드럽게 잇는 일에 마음을 다해요.',
    en: 'Relational balance with warm care added. Puts heart into gently connecting people.',
    keywords_ko: ['따뜻한 균형', '관계의 다리', '돌봄의 사교'],
    keywords_en: ['warm balance', 'bridge between people', 'caring sociability'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Libra', sign2: 'Leo',
    ko: '균형 감각에 환한 자기 표현이 더해진 결이에요. 사람들 사이에서 보기 좋게 빛나는 결.',
    en: 'Balance plus bright self-expression. Shines well in company.',
    keywords_ko: ['우아한 무대', '관계 속 빛', '보기 좋은 자기'],
    keywords_en: ['graceful stage', 'shine in company', 'well-presented self'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Libra', sign2: 'Virgo',
    ko: '균형과 실용성이 같이 가는 결이에요. 보기 좋은 것을 쓸모 있게 정돈하는 일에 끌려요.',
    en: 'Balance and practicality together. Drawn to arranging good-looking things so they actually work.',
    keywords_ko: ['실용적 미감', '정돈된 균형', '쓸모 있는 아름다움'],
    keywords_en: ['practical aesthetic', 'ordered balance', 'useful beauty'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Libra', sign2: 'Libra',
    ko: '균형 감각이 두 겹으로 강한 결이에요. 관계와 분위기를 매끄럽게 만드는 데 매우 능숙해요.',
    en: 'Balance doubled. Very skilled at smoothing both relations and atmosphere.',
    keywords_ko: ['우아함', '관계의 흐름', '깊은 균형 감각'],
    keywords_en: ['grace', 'relational flow', 'deep balance'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Libra', sign2: 'Scorpio',
    ko: '겉은 부드러운데 속은 깊고 진지해요. 관계도 좋아하지만 한 사람에게 진심을 다하는 결이에요.',
    en: 'Soft on the outside, deep and serious within. Likes relationships, but pours everything into one.',
    keywords_ko: ['부드러운 깊이', '진심의 관계', '겉유내강'],
    keywords_en: ['soft depth', 'sincere relation', 'gentle outside, strong inside'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Libra', sign2: 'Sagittarius',
    ko: '균형 감각에 자유로움이 더해진 결이에요. 관계를 즐기면서도 넓은 풍경을 잊지 않아요.',
    en: 'Balance with added freedom. Enjoys relationships while keeping the wider view in sight.',
    keywords_ko: ['관계와 자유', '시원한 사교', '넓은 균형'],
    keywords_en: ['relations and freedom', 'open sociability', 'wide balance'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Libra', sign2: 'Capricorn',
    ko: '관계의 균형에 책임감이 더해진 결이에요. 부드러운 표현 뒤에 약속을 끝까지 지키는 사람이에요.',
    en: 'Relational balance with added responsibility. Behind the soft tone is someone who keeps promises all the way.',
    keywords_ko: ['책임감 있는 관계', '단단한 부드러움', '약속을 지킴'],
    keywords_en: ['responsible relation', 'solid softness', 'keeps promises'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Libra', sign2: 'Aquarius',
    ko: '균형 감각에 독자적 관점이 더해진 결이에요. 사람들 사이에 어울리면서도 자기 색을 분명히 지켜요.',
    en: 'Balance with an independent view. Fits in among people while keeping its own color clear.',
    keywords_ko: ['자유로운 사교', '자기 색', '여유로운 균형'],
    keywords_en: ['free sociability', 'own color', 'easy balance'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Libra', sign2: 'Pisces',
    ko: '관계의 균형과 깊은 공감이 같이 있어요. 분위기를 부드럽게 만들고 사람의 마음에 자연스럽게 닿아요.',
    en: 'Balance and deep empathy together. Softens the room and reaches the heart of others naturally.',
    keywords_ko: ['공감하는 균형', '부드러운 사람', '분위기의 결'],
    keywords_en: ['empathic balance', 'gentle person', 'sense of mood'],
  },

  // ---------- Sun in Scorpio ----------
  {
    pair: 'sun_moon',
    sign1: 'Scorpio', sign2: 'Aries',
    ko: '깊은 본성에 즉결의 의지가 더해진 결이에요. 마음에 꽂힌 일에 전부를 거는 사람이에요.',
    en: 'Deep nature with a decisive will added. Goes all in on whatever has hooked the heart.',
    keywords_ko: ['뜨거운 집중', '깊은 추진', '강한 의지'],
    keywords_en: ['intense focus', 'deep drive', 'strong will'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Scorpio', sign2: 'Taurus',
    ko: '깊고 강한 마음에 안정된 본능이 더해진 결이에요. 좋아하는 사람과 자리를 끝까지 지켜요.',
    en: 'Deep intensity with steady instincts. Holds on to its people and places all the way.',
    keywords_ko: ['끝까지 지키는 마음', '강한 충성심', '단단한 욕망'],
    keywords_en: ['unwavering loyalty', 'firm holding', 'solid desire'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Scorpio', sign2: 'Gemini',
    ko: '겉은 가볍게 말하지만 속은 한 주제를 깊게 파고들어요. 가까운 사람에게만 진짜 생각을 보여줘요.',
    en: 'Talks lightly on the outside, digs into one subject inside. Shows the real thoughts only to a chosen few.',
    keywords_ko: ['깊은 비밀', '가벼운 표면', '진짜 사람과의 거리'],
    keywords_en: ['inner secret', 'light surface', 'closeness for the chosen'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Scorpio', sign2: 'Cancer',
    ko: '감정의 깊이가 두 겹으로 흐르는 결이에요. 한번 정이 들면 잘 떼어지지 않아요.',
    en: 'Emotional depth in a double layer. Once attached, hard to let go.',
    keywords_ko: ['깊은 정', '강한 애착', '오래 가는 마음'],
    keywords_en: ['deep bond', 'strong attachment', 'long-held heart'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Scorpio', sign2: 'Leo',
    ko: '깊은 본성에 환한 자존심이 더해진 결이에요. 평소엔 조용해도 자기 자리를 분명히 지켜요.',
    en: 'Depth with added bright pride. Quiet most of the time, but very clear about its own place.',
    keywords_ko: ['조용한 자존심', '깊은 빛', '단호한 자기'],
    keywords_en: ['quiet pride', 'deep light', 'firm self'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Scorpio', sign2: 'Virgo',
    ko: '깊이와 분석이 같이 가는 결이에요. 한번 들여다보면 본질까지 파헤치는 사람이에요.',
    en: 'Depth and analysis together. Once it looks, it goes all the way down to the essence.',
    keywords_ko: ['예리함', '본질 추구', '깊은 분석'],
    keywords_en: ['sharpness', 'getting to the root', 'deep analysis'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Scorpio', sign2: 'Libra',
    ko: '깊은 마음에 균형 감각이 더해진 결이에요. 강한 감정을 우아하게 풀어내는 결이에요.',
    en: 'Depth paired with balance. Carries strong feeling with grace.',
    keywords_ko: ['우아한 깊이', '균형 잡힌 강도', '품격'],
    keywords_en: ['graceful depth', 'balanced intensity', 'quiet dignity'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Scorpio', sign2: 'Scorpio',
    ko: '깊이와 강도가 두 겹으로 흐르는 결이에요. 한번 꽂히면 끝까지, 본질까지 파고들어요.',
    en: 'Depth and intensity in a double layer. Once committed, it goes all the way and to the bone.',
    keywords_ko: ['전부를 거는 마음', '강한 집중', '깊은 변용'],
    keywords_en: ['all-in heart', 'strong focus', 'deep transformation'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Scorpio', sign2: 'Sagittarius',
    ko: '깊은 본성에 의미를 찾는 욕구가 더해진 결이에요. 사소한 일에 만족하지 못해요.',
    en: 'Depth with a hunger for meaning added. Small things rarely satisfy.',
    keywords_ko: ['진실 추구', '의미 있는 깊이', '큰 시야'],
    keywords_en: ['truth-seeking', 'meaningful depth', 'wider view'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Scorpio', sign2: 'Capricorn',
    ko: '깊이와 책임감이 두 겹으로 단단한 결이에요. 시간을 들여 진짜 가치 있는 것을 만드는 사람이에요.',
    en: 'Depth and responsibility in a solid double layer. Builds something truly valuable over time.',
    keywords_ko: ['단단한 깊이', '책임감 있는 강도', '진짜 결과'],
    keywords_en: ['solid depth', 'responsible intensity', 'real result'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Scorpio', sign2: 'Aquarius',
    ko: '깊은 본성에 독자적 관점이 더해진 결이에요. 흐름에 휩쓸리지 않고 본질을 자기 식으로 봐요.',
    en: 'Depth with an independent view. Reads the essence its own way, never carried by the crowd.',
    keywords_ko: ['독자적 통찰', '거리감 있는 깊이', '자기 시각'],
    keywords_en: ['independent insight', 'depth with distance', 'own lens'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Scorpio', sign2: 'Pisces',
    ko: '깊이와 공감이 같이 흐르는 결이에요. 말하지 않은 마음까지 자연스럽게 읽어요.',
    en: 'Depth and empathy flowing together. Reads the unspoken naturally.',
    keywords_ko: ['깊은 공감', '말 없는 이해', '강한 감수성'],
    keywords_en: ['deep empathy', 'unspoken understanding', 'strong sensitivity'],
  },

  // ---------- Sun in Sagittarius ----------
  {
    pair: 'sun_moon',
    sign1: 'Sagittarius', sign2: 'Aries',
    ko: '자유와 추진력이 같은 방향으로 흐르는 결이에요. 새 길이 보이면 망설임 없이 나서는 사람이에요.',
    en: 'Freedom and drive flow the same way. Steps onto a new path without hesitation when it appears.',
    keywords_ko: ['모험심', '거침없는 시도', '시원한 자유'],
    keywords_en: ['adventure', 'unhesitating try', 'open freedom'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Sagittarius', sign2: 'Taurus',
    ko: '자유로운 본성에 안정된 닻이 같이 있어요. 멀리 떠나도 돌아올 자리는 분명히 가지고 있어요.',
    en: 'A free nature with a steady anchor. Travels far, but always keeps a clear place to return to.',
    keywords_ko: ['뿌리 있는 여행', '안정된 모험', '돌아올 자리'],
    keywords_en: ['rooted travel', 'grounded adventure', 'home to return to'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Sagittarius', sign2: 'Gemini',
    ko: '호기심과 모험심이 두 겹으로 강한 결이에요. 새로운 것 앞에서 가장 환해져요.',
    en: 'Curiosity and adventure doubled. Brightest when faced with the new.',
    keywords_ko: ['넓은 호기심', '경쾌한 모험', '여행과 정보'],
    keywords_en: ['wide curiosity', 'light adventure', 'travel and information'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Sagittarius', sign2: 'Cancer',
    ko: '자유로움에 따뜻한 마음이 같이 있어요. 여행을 좋아하면서도 사랑하는 사람을 늘 챙겨요.',
    en: 'Freedom paired with a warm heart. Loves traveling, while always looking after the people it loves.',
    keywords_ko: ['따뜻한 자유', '돌봄과 모험', '집과 길'],
    keywords_en: ['warm freedom', 'care and adventure', 'home and road'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Sagittarius', sign2: 'Leo',
    ko: '자유와 환한 자기 표현이 같이 가는 결이에요. 큰 풍경에서 가장 자기다워져요.',
    en: 'Freedom and bright expression together. Most itself in wider scenes.',
    keywords_ko: ['넓은 무대', '환한 자유', '시원한 자기'],
    keywords_en: ['big stage', 'bright freedom', 'expansive self'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Sagittarius', sign2: 'Virgo',
    ko: '큰 시야 아래 꼼꼼한 손이 자리해요. 자유롭게 움직이면서도 디테일을 잊지 않아요.',
    en: 'A careful hand under a wide view. Moves freely, but does not forget the detail.',
    keywords_ko: ['큰 그림과 디테일', '실용적 비전', '준비된 자유'],
    keywords_en: ['big picture and detail', 'practical vision', 'prepared freedom'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Sagittarius', sign2: 'Libra',
    ko: '자유로움과 균형 감각이 같이 있어요. 새 풍경을 즐기면서도 사람들과의 흐름을 매끄럽게 유지해요.',
    en: 'Freedom and balance together. Enjoys new scenery while keeping smooth flow with people.',
    keywords_ko: ['시원한 사교', '관계 속 자유', '넓은 균형'],
    keywords_en: ['open sociability', 'free in relation', 'wide balance'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Sagittarius', sign2: 'Scorpio',
    ko: '큰 시야에 깊은 마음이 더해진 결이에요. 의미 있는 일 앞에서는 끝까지 파고들어요.',
    en: 'Wide view with depth added. Goes all the way when the thing matters.',
    keywords_ko: ['의미 있는 깊이', '진실 추구', '뜨거운 집중'],
    keywords_en: ['meaningful depth', 'truth-seeking', 'intense focus'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Sagittarius', sign2: 'Sagittarius',
    ko: '자유와 모험심이 두 겹으로 흐르는 결이에요. 한곳에 묶이는 것을 가장 답답해해요.',
    en: 'Freedom and adventure doubled. Being tied to one place feels the most suffocating.',
    keywords_ko: ['모험심', '큰 시야', '시원함'],
    keywords_en: ['adventure', 'wide view', 'openness'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Sagittarius', sign2: 'Capricorn',
    ko: '큰 시야와 단단한 책임이 같이 있어요. 자유롭게 움직이면서도 끝을 보는 결이에요.',
    en: 'A wide view with solid responsibility. Moves freely, yet always sees through to the finish.',
    keywords_ko: ['책임감 있는 모험', '큰 그림의 끝맺음', '단단한 자유'],
    keywords_en: ['responsible adventure', 'finished big picture', 'solid freedom'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Sagittarius', sign2: 'Aquarius',
    ko: '자유와 독자적 관점이 같이 흐르는 결이에요. 다양한 시각을 즐기면서도 자기 색을 잃지 않아요.',
    en: 'Freedom and an independent view together. Enjoys many lenses without losing its own color.',
    keywords_ko: ['넓은 시각', '자유로운 사고', '자기 관점'],
    keywords_en: ['wide perspective', 'free thinking', 'own view'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Sagittarius', sign2: 'Pisces',
    ko: '큰 시야와 깊은 공감이 같이 있어요. 의미와 감정을 동시에 좇는 결이에요.',
    en: 'A wide view paired with deep empathy. Chases meaning and feeling at the same time.',
    keywords_ko: ['의미와 감정', '공감하는 비전', '부드러운 모험'],
    keywords_en: ['meaning and feeling', 'empathic vision', 'gentle adventure'],
  },

  // ---------- Sun in Capricorn ----------
  {
    pair: 'sun_moon',
    sign1: 'Capricorn', sign2: 'Aries',
    ko: '단단한 책임감에 즉결의 의지가 더해진 결이에요. 차분하지만 결정적인 순간엔 빠르게 움직여요.',
    en: 'Solid responsibility with decisive will added. Calm overall, fast at the moments that count.',
    keywords_ko: ['책임감 있는 추진', '결정적 행동', '단단한 의지'],
    keywords_en: ['responsible drive', 'key-moment action', 'solid will'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Capricorn', sign2: 'Taurus',
    ko: '단단함과 안정이 두 겹으로 깔린 결이에요. 시간이 걸려도 흔들리지 않는 결과를 만들어요.',
    en: 'Solidity and stability in a double layer. Builds results that do not waver, even if it takes time.',
    keywords_ko: ['단단함', '꾸준함', '오래 가는 가치'],
    keywords_en: ['solidity', 'steadiness', 'lasting value'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Capricorn', sign2: 'Gemini',
    ko: '책임감에 가벼운 사고가 더해진 결이에요. 일은 단단히 챙기면서 말은 부드럽게 해요.',
    en: 'Responsibility with a lighter mind added. Holds the work firmly while speaking softly.',
    keywords_ko: ['단단한 일, 가벼운 말', '실용적 사고', '책임감 있는 호기심'],
    keywords_en: ['solid work, light talk', 'practical thought', 'responsible curiosity'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Capricorn', sign2: 'Cancer',
    ko: '단단한 외면과 따뜻한 마음이 함께 있는 결이에요. 책임지는 자리에서 진심으로 사람을 챙겨요.',
    en: 'A solid outside with a warm heart inside. Cares for people sincerely from a responsible position.',
    keywords_ko: ['책임감 있는 돌봄', '따뜻한 단단함', '믿음직한 마음'],
    keywords_en: ['responsible care', 'warm solidity', 'reliable heart'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Capricorn', sign2: 'Leo',
    ko: '책임감에 환한 자존심이 더해진 결이에요. 결과로 자기를 분명히 보여주는 결.',
    en: 'Responsibility with bright pride added. Lets results speak for itself.',
    keywords_ko: ['결과로 빛남', '단단한 자존심', '책임감 있는 표현'],
    keywords_en: ['result-backed shine', 'solid pride', 'responsible expression'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Capricorn', sign2: 'Virgo',
    ko: '단단함과 실용성이 두 겹으로 강한 결이에요. 작은 일도 정확하게 마무리하는 사람이에요.',
    en: 'Solidity and practicality in a double layer. Finishes even small things accurately.',
    keywords_ko: ['정확성', '실속', '오래 가는 결과'],
    keywords_en: ['precision', 'substance', 'lasting result'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Capricorn', sign2: 'Libra',
    ko: '책임감에 균형 감각이 더해진 결이에요. 단단하게 일하면서도 사람을 부드럽게 대해요.',
    en: 'Responsibility with added balance. Works solidly while staying gentle with people.',
    keywords_ko: ['책임감 있는 관계', '단단한 부드러움', '신뢰의 흐름'],
    keywords_en: ['responsible relation', 'solid softness', 'trust in motion'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Capricorn', sign2: 'Scorpio',
    ko: '단단함에 깊은 집중이 더해진 결이에요. 시간을 들여 진짜 본질을 만드는 사람이에요.',
    en: 'Solidity with deep focus added. Builds the real thing over time.',
    keywords_ko: ['깊은 끈기', '본질적 결과', '강한 집중'],
    keywords_en: ['deep perseverance', 'essential result', 'strong focus'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Capricorn', sign2: 'Sagittarius',
    ko: '책임감에 큰 시야가 더해진 결이에요. 단단하게 일하면서도 멀리 보는 결이에요.',
    en: 'Responsibility with a wide view added. Works solidly while keeping the horizon in mind.',
    keywords_ko: ['큰 그림의 책임', '책임감 있는 비전', '단단한 자유'],
    keywords_en: ['big-picture responsibility', 'responsible vision', 'solid freedom'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Capricorn', sign2: 'Capricorn',
    ko: '책임감과 끈기가 두 겹으로 강한 결이에요. 시간이 들수록 단단해지는 사람이에요.',
    en: 'Responsibility and perseverance doubled. Gets sturdier the longer it goes.',
    keywords_ko: ['끈기', '책임감', '오래 가는 구조'],
    keywords_en: ['perseverance', 'responsibility', 'enduring structure'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Capricorn', sign2: 'Aquarius',
    ko: '책임감에 독자적 관점이 더해진 결이에요. 단단한 일을 자기 식으로 다시 짜는 결.',
    en: 'Responsibility with an independent view added. Rebuilds solid work in its own way.',
    keywords_ko: ['단단한 독창성', '실용적 자유', '책임감 있는 관점'],
    keywords_en: ['solid originality', 'practical freedom', 'responsible view'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Capricorn', sign2: 'Pisces',
    ko: '단단한 외면과 부드러운 마음이 같이 있는 결이에요. 책임을 다하면서도 사람을 깊게 이해해요.',
    en: 'A solid outside with a soft heart inside. Fulfills duty while understanding people deeply.',
    keywords_ko: ['책임감 있는 공감', '단단한 부드러움', '믿음직한 감수성'],
    keywords_en: ['responsible empathy', 'solid softness', 'reliable sensitivity'],
  },

  // ---------- Sun in Aquarius ----------
  {
    pair: 'sun_moon',
    sign1: 'Aquarius', sign2: 'Aries',
    ko: '자기 색이 분명한 본성에 즉결의 의지가 더해진 결이에요. 자기 길을 가는 데 망설임이 없어요.',
    en: 'A distinct own color with a decisive will added. No hesitation in walking the own path.',
    keywords_ko: ['독립성', '자기 길', '거침없는 자유'],
    keywords_en: ['independence', 'own path', 'unguarded freedom'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Aquarius', sign2: 'Taurus',
    ko: '독창성에 안정된 본능이 더해진 결이에요. 새로운 생각을 가지면서도 일상은 단단하게 둬요.',
    en: 'Originality with steady instincts added. Holds new ideas while keeping the everyday solid.',
    keywords_ko: ['안정된 독창성', '실용적 자유', '단단한 자기 색'],
    keywords_en: ['stable originality', 'practical freedom', 'solid own color'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Aquarius', sign2: 'Gemini',
    ko: '독자적 사고와 호기심이 두 겹으로 강한 결이에요. 새로운 아이디어를 가지고 노는 일을 즐겨요.',
    en: 'Independent thinking and curiosity doubled. Enjoys playing with new ideas.',
    keywords_ko: ['자유로운 사고', '아이디어', '경쾌한 자유'],
    keywords_en: ['free thinking', 'idea play', 'light freedom'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Aquarius', sign2: 'Cancer',
    ko: '거리감 있는 사고에 따뜻한 마음이 같이 있는 결이에요. 사람을 챙기되 자기 자리를 분명히 지켜요.',
    en: 'A view-from-distance mind paired with a warm heart. Cares for people while keeping its own space.',
    keywords_ko: ['거리감 있는 돌봄', '따뜻한 자유', '자기 자리'],
    keywords_en: ['caring with distance', 'warm freedom', 'kept space'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Aquarius', sign2: 'Leo',
    ko: '자기 색에 환한 자존심이 더해진 결이에요. 흐름에 휩쓸리지 않고 자기 식으로 빛나요.',
    en: 'Own color with bright pride added. Shines its own way, never carried by the current.',
    keywords_ko: ['독창적 빛', '자기 식의 자존심', '자유로운 무대'],
    keywords_en: ['original light', 'own-style pride', 'free stage'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Aquarius', sign2: 'Virgo',
    ko: '독자적 사고에 분석적 손이 더해진 결이에요. 시스템을 자기 식으로 짜고 정돈하는 결.',
    en: 'Independent thinking with an analytical hand. Builds and tidies systems its own way.',
    keywords_ko: ['시스템 사고', '실용적 독창성', '분석적 자유'],
    keywords_en: ['systems thinking', 'practical originality', 'analytic freedom'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Aquarius', sign2: 'Libra',
    ko: '자기 색에 균형 감각이 더해진 결이에요. 사람들과 어울리면서도 자기 시각을 분명히 유지해요.',
    en: 'Own color with balance added. Mixes with people while keeping a clear own view.',
    keywords_ko: ['균형 있는 자유', '자기 시각', '여유로운 사교'],
    keywords_en: ['balanced freedom', 'own view', 'easy sociability'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Aquarius', sign2: 'Scorpio',
    ko: '거리감 있는 사고에 깊은 집중이 더해진 결이에요. 자기 식으로 본질을 파고드는 결.',
    en: 'A distanced view with deep focus added. Digs into the essence in its own way.',
    keywords_ko: ['독자적 통찰', '깊은 자유', '본질 추구'],
    keywords_en: ['independent insight', 'deep freedom', 'getting to the root'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Aquarius', sign2: 'Sagittarius',
    ko: '자기 색과 큰 시야가 같이 흐르는 결이에요. 어디에서도 자기 자리를 만들 수 있어요.',
    en: 'Own color and a wide view flowing together. Can build its own place anywhere.',
    keywords_ko: ['넓은 자유', '자기 식 비전', '넉넉한 거리감'],
    keywords_en: ['wide freedom', 'own-style vision', 'easy distance'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Aquarius', sign2: 'Capricorn',
    ko: '독자적 사고에 책임감이 더해진 결이에요. 자기 식의 일을 끝까지 책임지는 사람이에요.',
    en: 'Independent thinking with responsibility added. Owns its own-way work all the way through.',
    keywords_ko: ['책임감 있는 독창성', '단단한 자유', '약속을 지킴'],
    keywords_en: ['responsible originality', 'solid freedom', 'keeps promises'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Aquarius', sign2: 'Aquarius',
    ko: '자기 색과 독자성이 두 겹으로 강한 결이에요. 흐름에 휩쓸리는 것을 가장 싫어해요.',
    en: 'Own color and independence doubled. Being swept along is the worst.',
    keywords_ko: ['독립성', '자기 시각', '자유로운 사고'],
    keywords_en: ['independence', 'own view', 'free thinking'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Aquarius', sign2: 'Pisces',
    ko: '거리감 있는 사고에 깊은 공감이 더해진 결이에요. 자기 식으로 보면서도 사람의 마음을 부드럽게 읽어요.',
    en: 'A distanced view with deep empathy added. Sees in its own way while reading hearts gently.',
    keywords_ko: ['자유로운 공감', '거리감과 부드러움', '자기 식의 감수성'],
    keywords_en: ['free empathy', 'distance with softness', 'own-style sensitivity'],
  },

  // ---------- Sun in Pisces ----------
  {
    pair: 'sun_moon',
    sign1: 'Pisces', sign2: 'Aries',
    ko: '부드러운 본성에 의외의 추진력이 살아 있어요. 평소엔 잔잔해도 보호할 사람이 있으면 단호해져요.',
    en: 'A soft nature with a surprising forward push. Usually quiet, decisive when someone to protect appears.',
    keywords_ko: ['부드러운 용기', '감성적 추진', '보호 본능'],
    keywords_en: ['gentle courage', 'emotional drive', 'protective instinct'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Pisces', sign2: 'Taurus',
    ko: '감수성과 안정된 본능이 같이 있는 결이에요. 부드러운 마음이지만 일상은 단단하게 잡아요.',
    en: 'Sensitivity with steady instincts. A soft heart, but the everyday stays solid.',
    keywords_ko: ['부드러운 안정', '실용적 감수성', '편안한 마음'],
    keywords_en: ['soft stability', 'practical sensitivity', 'easy heart'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Pisces', sign2: 'Gemini',
    ko: '감수성에 가벼운 사고가 더해진 결이에요. 분위기를 빠르게 읽고 가볍게 풀어줘요.',
    en: 'Sensitivity with a lighter mind added. Reads the mood quickly and eases it without weight.',
    keywords_ko: ['민감한 사교', '가벼운 공감', '분위기 읽기'],
    keywords_en: ['sensitive sociability', 'light empathy', 'reading the room'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Pisces', sign2: 'Cancer',
    ko: '공감과 돌봄이 두 겹으로 흐르는 결이에요. 사람과 분위기에 자연스럽게 녹아들어요.',
    en: 'Empathy and care doubled. Blends into people and atmosphere without trying.',
    keywords_ko: ['깊은 공감', '돌봄', '스며드는 마음'],
    keywords_en: ['deep empathy', 'nurturing', 'merging heart'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Pisces', sign2: 'Leo',
    ko: '부드러운 본성에 환한 표현이 더해진 결이에요. 감성적이지만 사람들 앞에서는 빛을 내는 결.',
    en: 'A soft nature with bright expression added. Emotional inside, lights up in front of people.',
    keywords_ko: ['감성적 빛', '부드러운 무대', '공감 어린 환함'],
    keywords_en: ['emotional shine', 'soft stage', 'empathic brightness'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Pisces', sign2: 'Virgo',
    ko: '감수성과 꼼꼼한 손이 같이 있는 결이에요. 분위기는 부드럽게, 일은 정확하게 처리해요.',
    en: 'Sensitivity paired with a careful hand. Soft with mood, precise with work.',
    keywords_ko: ['부드러운 정확성', '공감하는 정돈', '실용적 감수성'],
    keywords_en: ['soft precision', 'empathic order', 'practical sensitivity'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Pisces', sign2: 'Libra',
    ko: '공감과 균형 감각이 같이 흐르는 결이에요. 부드럽게 사람과 분위기를 이어주는 사람이에요.',
    en: 'Empathy and balance flowing together. Connects people and mood gently.',
    keywords_ko: ['부드러운 사교', '공감하는 균형', '관계의 결'],
    keywords_en: ['gentle sociability', 'empathic balance', 'sense of relation'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Pisces', sign2: 'Scorpio',
    ko: '공감과 깊은 감정이 두 겹으로 흐르는 결이에요. 말 없이도 사람의 진짜 마음을 알아채요.',
    en: 'Empathy and deep feeling doubled. Senses the real heart of others without words.',
    keywords_ko: ['깊은 공감', '말 없는 이해', '진심의 마음'],
    keywords_en: ['deep empathy', 'unspoken understanding', 'sincere heart'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Pisces', sign2: 'Sagittarius',
    ko: '감수성에 큰 시야가 더해진 결이에요. 의미를 좇으면서 사람을 따뜻하게 이해해요.',
    en: 'Sensitivity with a wide view added. Chases meaning while understanding people warmly.',
    keywords_ko: ['의미와 공감', '부드러운 비전', '따뜻한 시야'],
    keywords_en: ['meaning and empathy', 'gentle vision', 'warm horizon'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Pisces', sign2: 'Capricorn',
    ko: '부드러운 마음에 단단한 책임감이 더해진 결이에요. 감수성을 가지면서도 약속은 끝까지 지켜요.',
    en: 'A soft heart with solid responsibility added. Sensitive, yet keeps promises all the way.',
    keywords_ko: ['책임감 있는 감수성', '단단한 부드러움', '믿음직한 마음'],
    keywords_en: ['responsible sensitivity', 'solid softness', 'reliable heart'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Pisces', sign2: 'Aquarius',
    ko: '공감에 거리감 있는 사고가 같이 있는 결이에요. 따뜻하지만 휩쓸리지 않고 자기 시각을 지켜요.',
    en: 'Empathy with a distanced mind together. Warm, yet keeps its own view from being carried away.',
    keywords_ko: ['거리감 있는 공감', '자유로운 감수성', '자기 시각'],
    keywords_en: ['empathy with space', 'free sensitivity', 'own view'],
  },
  {
    pair: 'sun_moon',
    sign1: 'Pisces', sign2: 'Pisces',
    ko: '공감과 감수성이 두 겹으로 흐르는 결이에요. 사람과 세상에 자연스럽게 스며드는 결.',
    en: 'Empathy and sensitivity doubled. Seeps into people and the world without trying.',
    keywords_ko: ['깊은 공감', '스며드는 마음', '깊은 감수성'],
    keywords_en: ['deep empathy', 'merging heart', 'deep sensitivity'],
  },
]

// ============================================================
// Combined registry
// ============================================================

export const SIGN_COMBINATIONS: SignCombination[] = [
  ...SUN_MOON_COMBINATIONS,
  // Venus × Mars, Sun × Ascendant, Moon × Ascendant — to be added in later PRs
]

// ============================================================
// Lookup helpers
// ============================================================

export function findSignCombination(
  pair: SignCombinationPair,
  sign1: ZodiacName,
  sign2: ZodiacName,
): SignCombination | null {
  return (
    SIGN_COMBINATIONS.find(
      (entry) => entry.pair === pair && entry.sign1 === sign1 && entry.sign2 === sign2,
    ) ?? null
  )
}

export function listSignCombinationsByPair(pair: SignCombinationPair): SignCombination[] {
  return SIGN_COMBINATIONS.filter((entry) => entry.pair === pair)
}
