import { PDFDocument, rgb, StandardFonts } from "pdf-lib";

/**
 * 🎨 pdfTemplate.js
 * - 오행 스펙트럼 기반 포스터형 리포트 생성
 * - CombinedResult 기반 PDF 바이트 반환
 */
export async function generateFortunePdf(result) {
  const pdf = await PDFDocument.create();
  const page = pdf.addPage([595, 842]); // A4 세로
  const { saju, astrology, summary, interpretation } = result;
  const fiveElements = saju?.facts?.fiveElements ?? {};

  // 주요 오행 색상 추출
  const dominantEntry = Object.entries(fiveElements).sort((a, b) => b[1] - a[1])[0];
  const dominant = dominantEntry?.[0] ?? "Earth";
  const elementColors = {
    Wood: rgb(0.4, 0.8, 0.4),
    Fire: rgb(1.0, 0.4, 0.3),
    Earth: rgb(0.98, 0.85, 0.2),
    Metal: rgb(0.7, 0.75, 0.8),
    Water: rgb(0.3, 0.5, 0.9),
  };

  const bgColor = elementColors[dominant];
  page.drawRectangle({ x: 0, y: 0, width: 595, height: 842, color: bgColor });

  const titleFont = await pdf.embedFont(StandardFonts.HelveticaBold);
  const bodyFont = await pdf.embedFont(StandardFonts.Helvetica);

  // Title
  const title = "Destiny Map Report";
  page.drawText(title, {
    x: 50,
    y: 800,
    size: 26,
    font: titleFont,
    color: rgb(1, 1, 1),
  });

  // Sub info
  const sub = `Dominant Element: ${dominant}\n${summary ?? ""}`;
  page.drawText(sub, {
    x: 50,
    y: 770,
    size: 12,
    font: bodyFont,
    color: rgb(1, 1, 1),
    lineHeight: 14,
  });

  // Decorative aura circle
  page.drawEllipse({
    x: 297.5,
    y: 480,
    xScale: 160,
    yScale: 160,
    color: rgb(1, 1, 1),
    opacity: 0.06,
  });

  const text =
    interpretation?.slice(0, 1500) ??
    "운세 해석 내용이 없습니다. computeDestinyMap() 결과의 interpretation을 연결하세요.";

  // Body
  page.drawText(text, {
    x: 50,
    y: 720 - 180,
    size: 11,
    font: bodyFont,
    color: rgb(1, 1, 1),
    lineHeight: 13,
    maxWidth: 480,
  });

  // Footer
  const footer = `Generated by DestinyMap Unified Engine • ${new Date().toLocaleString()}`;
  page.drawText(footer, {
    x: 50,
    y: 30,
    size: 9,
    font: bodyFont,
    color: rgb(1, 1, 1),
    opacity: 0.7,
  });

  const pdfBytes = await pdf.save();
  return pdfBytes;
}