import { PersonaArchetype } from './types';

export const PERSONA_ARCHETYPES: Record<string, PersonaArchetype> = {
  RVLA: {
    code: 'RVLA',
    name: 'Starforge Architect',
    summary: 'Radiant energy, visionary thinking, logical decisions, and structured rhythms. You rally people around blueprints for the future.',
    strengths: ['Strategic clarity', 'High agency', 'Systems thinking', 'Charismatic direction'],
    cautions: ['Can steamroll quieter voices', 'Impatient with slower pacing'],
    idealRoles: ['Founder/CEO', 'Product strategist', 'Innovation lead', 'Systems architect'],
    growth: ['Schedule listening time', 'Ship small iterations before the grand plan'],
    compatibilityHint: 'Pairs well with grounded builders (GSLA, GSHA) who stabilize delivery.',
  },
  RVLF: {
    code: 'RVLF',
    name: 'Catalyst Inventor',
    summary: 'Radiant, visionary, analytical, and fluid. You light sparks, prototype boldly, and adapt fast.',
    strengths: ['Rapid ideation', 'Pattern spotting', 'Courageous experimentation'],
    cautions: ['May leave projects half-built', 'Can ignore constraints'],
    idealRoles: ['R&D lead', 'Creative technologist', 'Venture builder', 'Early PM/PO'],
    growth: ['Finish cycles before pivoting', 'Invite execution partners early'],
    compatibilityHint: 'Anchors (RSLA, GSLA) give you landing gear; you give them lift.',
  },
  RVHA: {
    code: 'RVHA',
    name: 'Alliance Strategist',
    summary: 'Radiant, visionary, empathic, and structured. You mobilize people with a clear mission and care for morale.',
    strengths: ['Narrative leadership', 'Stakeholder alignment', 'Long-horizon planning'],
    cautions: ['Can overfunction to protect others', 'Risk of decision fatigue'],
    idealRoles: ['Chief of staff', 'Community strategist', 'Org designer', 'Program director'],
    growth: ['Delegate emotional labor', 'Protect recovery time after launches'],
    compatibilityHint: 'Grounded analysts (GVLA) sharpen your plans; you keep them people-centered.',
  },
  RVHF: {
    code: 'RVHF',
    name: 'Empathic Pioneer',
    summary: 'Radiant, visionary, empathic, and fluid. You explore emerging spaces and bring people along through story and vibe.',
    strengths: ['Storytelling', 'Trend sensing', 'Community ignition'],
    cautions: ['May avoid hard trade-offs', 'Easily overstretched'],
    idealRoles: ['Creator/evangelist', 'Design research', 'Brand/community lead'],
    growth: ['Define “done” for each season', 'Set boundaries on availability'],
    compatibilityHint: 'Structured partners (RVHA, RSHA) anchor your momentum.',
  },
  RSLA: {
    code: 'RSLA',
    name: 'Command Organizer',
    summary: 'Radiant, structured, logical, and anchored. You drive execution, set order, and deliver reliably.',
    strengths: ['Operational rigor', 'Decisive calls', 'Clear accountability'],
    cautions: ['Can feel rigid', 'Risk of overlooking subtle risks'],
    idealRoles: ['COO/ops lead', 'Delivery manager', 'Program lead', 'PM'],
    growth: ['Leave space for exploration', 'Invite dissent before locking plans'],
    compatibilityHint: 'Visionary catalysts (RVLF) extend your horizon; you convert their ideas to roadmaps.',
  },
  RSLF: {
    code: 'RSLF',
    name: 'Tactical Improviser',
    summary: 'Radiant, structured, logical, and fluid. You enjoy live problem-solving and adjusting tactics on the fly.',
    strengths: ['On-the-spot decisions', 'Crisis navigation', 'Resourcefulness'],
    cautions: ['May under-document', 'Can over-index on short-term wins'],
    idealRoles: ['Operations firefighter', 'Live ops', 'Sales engineering', 'Incident commander'],
    growth: ['Retro regularly to codify playbooks', 'Balance speed with debt paydown'],
    compatibilityHint: 'Anchors (RSLA, GSLA) help you sustain; you help them respond.',
  },
  RSHA: {
    code: 'RSHA',
    name: 'Connector Steward',
    summary: 'Radiant, structured, empathic, and anchored. You create orderly, caring environments where teams can thrive.',
    strengths: ['People ops', 'Ritual building', 'Conflict mediation with structure'],
    cautions: ['Can over-schedule', 'Might absorb too much emotional load'],
    idealRoles: ['People lead', 'Project/program manager', 'Customer success leader'],
    growth: ['Set limits on caretaking', 'Allow experiments that may be messy first'],
    compatibilityHint: 'Visionary partners (RVHA, GVHF) stretch creativity; you keep delivery humane.',
  },
  RSHF: {
    code: 'RSHF',
    name: 'Warm Facilitator',
    summary: 'Radiant, structured, empathic, and fluid. You host spaces, adapt formats, and keep humans engaged.',
    strengths: ['Facilitation', 'On-the-fly adjustments', 'Inclusive energy'],
    cautions: ['Scope creep', 'Can defer hard calls'],
    idealRoles: ['Workshop lead', 'Community ops', 'Education/design ops'],
    growth: ['Define non-negotiables before sessions', 'Practice concise decisions'],
    compatibilityHint: 'Logical anchors (RSLA, GVLA) bring crisp edges to your flow.',
  },
  GVLA: {
    code: 'GVLA',
    name: 'Quiet Architect',
    summary: 'Grounded, visionary, logical, and anchored. You design deep systems and think several moves ahead.',
    strengths: ['Systems mapping', 'Risk modeling', 'Long-term coherence'],
    cautions: ['Can stay in analysis too long', 'May resist quick pivots'],
    idealRoles: ['Staff engineer', 'Enterprise architect', 'Research strategist'],
    growth: ['Ship incremental proofs', 'Surface plans for feedback early'],
    compatibilityHint: 'Radiant catalysts (RVLF) bring you bold problems; you make them real.',
  },
  GVLF: {
    code: 'GVLF',
    name: 'Analyst Explorer',
    summary: 'Grounded, visionary, logical, and fluid. You prototype ideas, learn fast, and refine through evidence.',
    strengths: ['Hypothesis-driven building', 'Calm experimentation', 'Deep focus'],
    cautions: ['May avoid spotlight', 'Context switching drains energy'],
    idealRoles: ['Data/product analytics', 'ML research', 'Skunkworks engineer'],
    growth: ['Share drafts before perfect', 'Co-create with storytellers to gain buy-in'],
    compatibilityHint: 'Radiant storytellers (RVHF) amplify your insights.',
  },
  GVHA: {
    code: 'GVHA',
    name: 'Insightful Counselor',
    summary: 'Grounded, visionary, empathic, and anchored. You listen deeply and guide with pattern-based insight.',
    strengths: ['Pattern recognition', 'Calm presence', 'Trusted advisorship'],
    cautions: ['May hesitate to assert direction', 'Energy can dip in loud rooms'],
    idealRoles: ['Coach/therapist', 'UX research', 'Strategy advisor', 'Staff PM'],
    growth: ['Name decisions explicitly', 'Pair with doers to accelerate action'],
    compatibilityHint: 'Radiant organizers (RSHA) help you operationalize care.',
  },
  GVHF: {
    code: 'GVHF',
    name: 'Soul Guide',
    summary: 'Grounded, visionary, empathic, and fluid. You explore meaning, help others transform, and move at a human pace.',
    strengths: ['Depth of insight', 'High empathy', 'Gentle experimentation'],
    cautions: ['Can drift without anchors', 'May avoid conflict'],
    idealRoles: ['Counselor/coach', 'Facilitator', 'Creative director', 'Research lead'],
    growth: ['Set timeboxes for decisions', 'Use light structure to sustain momentum'],
    compatibilityHint: 'Anchored partners (GVHA, GSHA) give you stability; you offer depth.',
  },
  GSLA: {
    code: 'GSLA',
    name: 'System Guardian',
    summary: 'Grounded, structured, logical, anchored. You keep operations tight and risk low.',
    strengths: ['Reliability', 'Compliance mindset', 'Process excellence'],
    cautions: ['May resist change', 'Can over-control'],
    idealRoles: ['Security/infra lead', 'Finance ops', 'QA/automation', 'Governance'],
    growth: ['Leave room for innovation', 'Iterate processes with users'],
    compatibilityHint: 'Visionaries (RVLA, GVLA) set bold direction; you ensure it is safe and stable.',
  },
  GSLF: {
    code: 'GSLF',
    name: 'Pragmatic Solver',
    summary: 'Grounded, structured, logical, and fluid. You fix what is broken and adapt procedures when reality shifts.',
    strengths: ['Hands-on fixes', 'Calm under pressure', 'Resourceful troubleshooting'],
    cautions: ['May under-communicate', 'Patience with ambiguity varies'],
    idealRoles: ['SRE/DevOps', 'Field engineering', 'Ops analyst', 'Support engineering'],
    growth: ['Document learnings', 'Share context early to align stakeholders'],
    compatibilityHint: 'Storytellers (RVHF) help broadcast your wins; anchors (GSLA) keep you aligned.',
  },
  GSHA: {
    code: 'GSHA',
    name: 'Anchor Mentor',
    summary: 'Grounded, structured, empathic, anchored. You create stable, caring systems for people to grow.',
    strengths: ['Mentorship', 'Policy with heart', 'Predictable delivery'],
    cautions: ['Can become gatekeeper', 'Change adoption may feel slow'],
    idealRoles: ['People ops/HRBP', 'Education ops', 'Customer success strategy'],
    growth: ['Pilot changes with small cohorts', 'Invite challenging feedback regularly'],
    compatibilityHint: 'Radiant catalysts (RVHF, RVLF) stretch possibilities; you turn them into sustainable practice.',
  },
  GSHF: {
    code: 'GSHF',
    name: 'Hearth Mediator',
    summary: 'Grounded, structured, empathic, and fluid. You calm conflicts, adapt plans, and keep teams feeling safe.',
    strengths: ['Conflict resolution', 'Empathic process tweaks', 'Steady facilitation'],
    cautions: ['May absorb stress silently', 'Can delay firm decisions'],
    idealRoles: ['Mediation/ombuds', 'Support lead', 'Team operations', 'Service design'],
    growth: ['State boundaries explicitly', 'Escalate when patterns repeat'],
    compatibilityHint: 'Logical partners (GSLA, GVLA) help with crisp decisions; you protect the human fabric.',
  },
};
