import { PersonaArchetype } from './types';

export const PERSONA_ARCHETYPES: Record<string, PersonaArchetype> = {
  RVLA: {
    code: 'RVLA',
    name: 'Starforge Architect',
    summary: 'You are a charismatic visionary who draws blueprints for the future and rallies people around them. With a rare combination of big-picture thinking and logical precision, you excel at designing complex systems and leading teams toward ambitious goals. Your mind always holds a clear picture of where things should be in 3-5 years, and you have the drive to systematically get there. People feel reassured by your confident presence and naturally follow your lead.',
    strengths: ['Strategic clarity - seeing the core truth even in complex situations', 'High agency - turning thoughts into action with decisive energy', 'Systems thinking - creating order from chaos', 'Charismatic direction - inspiring and motivating through shared vision'],
    cautions: ['May miss details or emotional nuances - small signals can get lost when focused on the big picture', 'Impatience with pacing - not everyone moves as fast as you do'],
    idealRoles: ['Founder/CEO', 'Product strategist', 'Innovation lead', 'Systems architect'],
    growth: ['Schedule weekly listening sessions - try asking "What do you think?" first', 'Ship small iterations before the grand plan - quick experiments teach more than perfect blueprints'],
    compatibilityHint: 'Pairs well with grounded builders (GSLA, GSHA) who stabilize delivery. They handle the details while you set the direction.',
  },
  RVLF: {
    code: 'RVLF',
    name: 'Catalyst Inventor',
    summary: 'You are a creative innovator who discovers new possibilities and experiments rapidly. You read patterns quickly and turn ideas into reality with remarkable speed, adapting fluidly to change. Your brain is like an idea factory that never stops. "What if we tried this?" is your constant refrain. You see things the world isn\'t ready for yet, and you have the courage to try them anyway.',
    strengths: ['Rapid ideation - turning thoughts into tangible prototypes instantly', 'Pattern spotting - finding connections others miss', 'Courageous experimentation - treating failures as data, not defeats', 'Adaptive flexibility - pivoting without hesitation'],
    cautions: ['May leave projects half-built - new ideas can derail current work', 'Can ignore constraints - budgets, timelines, and resources have limits'],
    idealRoles: ['R&D lead', 'Creative technologist', 'Venture builder', 'Early PM/PO'],
    growth: ['Finish cycles before pivoting - remember "Done is better than perfect"', 'Invite execution partners early - you need people who can make your ideas real'],
    compatibilityHint: 'Anchors (RSLA, GSLA) give you landing gear; you give them lift. When you spark the fire, they keep it burning.',
  },
  RVHA: {
    code: 'RVHA',
    name: 'Alliance Strategist',
    summary: 'You are a storyteller who moves hearts and a strategist who boosts team morale. You rally people around a clear mission and make everyone feel valued. You excel at explaining "why" and making people feel part of something bigger. When you enter a room, the atmosphere shifts, and scattered opinions start converging toward a shared direction.',
    strengths: ['Inspiring communication - turning complex visions into stories everyone understands', 'Stakeholder alignment - weaving different perspectives into one', 'Long-term strategic planning - seeing how today\'s small actions matter tomorrow', 'Team culture and morale management - creating environments where people want to give their best'],
    cautions: ['May burn out caring for others - your battery needs recharging too', 'Risk of decision fatigue from seeking consensus everywhere - sometimes leaders must decide alone'],
    idealRoles: ['Chief of staff', 'Community strategist', 'Org culture designer', 'Program director'],
    growth: ['Delegate some emotional caretaking to others - you don\'t have to carry everything alone', 'Protect recovery time after major launches - rest is also strategy'],
    compatibilityHint: 'Analytical partners (GVLA) add evidence to your vision. When you say "why," they design the "how."',
  },
  RVHF: {
    code: 'RVHF',
    name: 'Empathic Pioneer',
    summary: 'You are a captivating trailblazer who senses new trends and draws people in through story and vibe. You have a natural gift for building and energizing communities. Where you are, something new and exciting always seems to happen. People gather around you and naturally catch your enthusiasm. You have an antenna that discovers trends before they even have names.',
    strengths: ['Magnetic storytelling - making ordinary things sound extraordinary', 'Intuition for reading the zeitgeist - sensing what\'s coming next', 'Ability to spark communities - connecting and mobilizing people', 'Free thinking and creativity - not bound by existing frameworks'],
    cautions: ['Tendency to postpone hard choices - avoiding decisions can mean missing opportunities', 'Risk of spreading energy too thin - you don\'t have to attend every party'],
    idealRoles: ['Content creator', 'Brand strategist', 'Community lead', 'Design researcher'],
    growth: ['Set clear completion criteria for each season - define what "done" looks like upfront', 'Establish boundaries on where to invest energy - strategic "no" is essential'],
    compatibilityHint: 'Structured partners (RVHA, RSHA) make your energy sustainable. When you set the direction, they draw the roadmap.',
  },
  RSLA: {
    code: 'RSLA',
    name: 'Command Organizer',
    summary: 'You are a reliable leader who establishes order in chaos and drives your team toward goals. With clear accountability and efficient process design, you complete any project. "That\'s impossible" means nothing to you. Find a way, or make one. Your team knows that when you\'re involved, the project will definitely get done.',
    strengths: ['Unwavering execution - once planned, always delivered', 'Swift and clear decision-making - no hesitation when it counts', 'Clear distribution of roles and responsibilities - everyone knows exactly what to do', 'Building efficient operational systems - automating and optimizing repetitive work'],
    cautions: ['May come across as inflexible - you might resist plan changes', 'Risk of missing subtle warning signs - focusing on numbers might mean missing mood shifts'],
    idealRoles: ['COO/Ops lead', 'Project manager', 'Delivery lead', 'Product manager'],
    growth: ['Leave room for exploration and experimentation in plans - reserve 10% for "adventure budget"', 'Actively seek opposing views before finalizing decisions - make a habit of asking "why not?"'],
    compatibilityHint: 'Visionary ideators (RVLF) open new possibilities, and you make them real. When their "crazy ideas" meet your execution power, innovation happens.',
  },
  RSLF: {
    code: 'RSLF',
    name: 'Tactical Improviser',
    summary: 'You are a master of real-time problem-solving who calmly finds solutions even in unexpected situations. With quick judgment and resource utilization, you turn crises into opportunities. While others panic, you\'re already implementing the solution. Your motto isn\'t "it\'ll work out somehow" but "I\'ll make it work somehow."',
    strengths: ['Split-second judgment and response - quick reflexes that shine in crisis', 'Cool-headedness under pressure - mental fortitude that doesn\'t waver', 'Maximizing limited resources - making the best out of what\'s available', 'Field-centered pragmatic thinking - valuing what actually works over theory'],
    cautions: ['May neglect documentation - your know-how only in your head is a waste', 'Risk of focusing on short-term wins over long-term - today\'s fix could be tomorrow\'s problem'],
    idealRoles: ['Incident commander', 'Sales engineer', 'Live operations', 'Field manager'],
    growth: ['Regularly document solutions and build playbooks - invest 5 minutes to leave notes', 'Find the balance between speed and quality - find the sweet spot between "fast" and "right"'],
    compatibilityHint: 'Systematic planners (RSLA, GSLA) turn your quick fixes into sustainable systems. When you put out fires, they build fire prevention systems.',
  },
  RSHA: {
    code: 'RSHA',
    name: 'Connector Steward',
    summary: 'You are a caring manager who creates environments where people can perform at their best. Combining structure with warmth, you help teams grow in stability. People on your team feel "I can grow here." There are rules and processes, but everyone knows they exist to serve people.',
    strengths: ['People-centered operational design - making systems serve humans', 'Building team culture and rituals - creating environments of belonging and purpose', 'Structural conflict resolution - separating emotions from facts to find solutions', 'Stable and predictable leadership - an environment where team members feel secure'],
    cautions: ['May lose flexibility trying to plan everything - sometimes spontaneity is okay', 'Risk of taking on too much emotional burden - you deserve care too'],
    idealRoles: ['People manager', 'Project/program manager', 'Customer success lead', 'HR business partner'],
    growth: ['Set healthy boundaries on caretaking - saying "no" is also care', 'Allow experiments to start imperfect - 80% is a fine starting point'],
    compatibilityHint: 'Creative visionaries (RVHA, GVHF) bring new ideas, and you turn them into actionable plans. When they dream, you design it into reality.',
  },
  RSHF: {
    code: 'RSHF',
    name: 'Warm Facilitator',
    summary: 'You are a born facilitator who energizes any gathering and gets everyone participating. You flexibly adjust formats based on the situation and create an inclusive atmosphere. Your meetings are never boring. Even quiet people speak up, and time flies by. You have the magic that makes people think "I hope that person facilitates again."',
    strengths: ['Natural facilitation - creating atmospheres where anyone can speak comfortably', 'Improvised adjustments - flexibly adapting when things don\'t go as expected', 'Warm inclusive energy - involving everyone without leaving anyone out', 'Ability to draw participation - turning bystanders into participants'],
    cautions: ['Tendency for scope to keep expanding - beware the temptation of "should we try this too?"', 'May want to postpone difficult decisions - sometimes there\'s no answer that makes everyone happy'],
    idealRoles: ['Workshop facilitator', 'Community operations', 'Learning designer', 'Event planner'],
    growth: ['Define non-negotiable core goals before sessions - set 3 "must-dos for today"', 'Practice quick and clear decisions - try training yourself to decide in 5 seconds'],
    compatibilityHint: 'Logical analysts (RSLA, GVLA) add clear frames to your flexibility. When you create the atmosphere, they provide the structure.',
  },
  GVLA: {
    code: 'GVLA',
    name: 'Quiet Architect',
    summary: 'You are a deep-thinking strategist who sees structures beneath the surface and thinks several moves ahead. You excel at understanding complex systems and creating designs that stand the test of time. What you design still works 10 years later. When others ask "why so complex?", time proves "glad we did it that way."',
    strengths: ['Grasping the essence of complex systems - finding root causes even in chaos', 'Long-term risk prediction and prevention - stopping problems today that would explode in 3 years', 'Consistent architecture design - structures that scale over time', 'Deep analysis and insight - seeing what others can\'t'],
    cautions: ['May stay too long in analysis phase - waiting for perfect design might mean missing opportunities', 'May feel resistance to sudden changes - sometimes you need to start in an imperfect state'],
    idealRoles: ['Senior/staff engineer', 'Enterprise architect', 'Research strategist', 'Technical advisor'],
    growth: ['Validate and ship in small increments even if imperfect - start with MVP', 'Get early feedback to adjust direction - check in before going too far alone'],
    compatibilityHint: 'Energetic experimenters (RVLF) bring challenging problems, and you create solid solutions. When their speed meets your depth, the best results emerge.',
  },
  GVLF: {
    code: 'GVLF',
    name: 'Analyst Explorer',
    summary: 'You are an analytical explorer who calmly builds hypotheses and improves through evidence. With deep focus, you solve complex problems and discover insights from data. Your workspace is quiet, but innovation is born within it. Your single comment "Wait, this number looks weird" often prevents major mistakes.',
    strengths: ['Systematic hypothesis-based experimentation - decisions based on evidence, not guesses', 'Deep immersion without distraction - concentration that digs into complex problems', 'Finding patterns in data - reading stories hidden between numbers', 'Calm and objective analysis - judgment not swayed by emotions'],
    cautions: ['May not get recognized for contributions by avoiding the spotlight - sharing your work matters', 'Frequent context switching drains energy significantly - protect your deep work time'],
    idealRoles: ['Data analyst', 'ML engineer', 'Product analyst', 'R&D developer'],
    growth: ['Share drafts before they\'re perfect - show it at 50%', 'Partner with storytellers to amplify impact - let your discoveries reach the world'],
    compatibilityHint: 'Expressive communicators (RVHF) share your discoveries with the world. When you find the truth, they turn it into stories.',
  },
  GVHA: {
    code: 'GVHA',
    name: 'Insightful Counselor',
    summary: 'You are a trusted advisor who listens deeply, reads patterns, and points to what matters. With your calm presence, you guide people to find their own answers. People who talk with you say "I already knew this, but thanks to you I realized it." You have a special ability to help people find answers rather than giving them.',
    strengths: ['Deep listening and empathy - reading true intentions beyond words', 'Pattern recognition in complex situations - finding the root of recurring problems', 'Calm reassuring presence - people feel secure when you\'re around', 'Insightful questions and advice - one word that changes thinking'],
    cautions: ['May hesitate to give clear direction - sometimes direct answers are needed', 'Energy drains quickly in loud, fast environments - secure recovery time'],
    idealRoles: ['Coach/mentor', 'UX researcher', 'Strategy consultant', 'Senior product manager'],
    growth: ['State decisions and directions explicitly beyond advice - try saying "My view is this"', 'Partner with action-oriented people to turn insights into reality - translate insight into action'],
    compatibilityHint: 'Execution-oriented organizers (RSHA) turn your insights into concrete processes. When you find the "why," they execute the "how."',
  },
  GVHF: {
    code: 'GVHF',
    name: 'Soul Guide',
    summary: 'You are a deep guide who explores the meaning of life and helps others transform from within. Moving at a human pace, you lead genuine growth. Time with you feels like "healing." In a fast-moving world, you\'re the one who asks "Wait, what really matters?"',
    strengths: ['Deep insight that pierces to essence - seeing what\'s real beyond the surface', 'Sensitivity that reads others\' emotions subtly - sensing without words', 'Soft but meaningful experimentation - small changes leading to big growth', 'Authentic connection - building relationships without masks'],
    cautions: ['May lose direction without clear structure - sometimes a map is needed', 'May want to avoid conflict or confrontation - healthy tension is also part of growth'],
    idealRoles: ['Life coach', 'Facilitator', 'Creative director', 'Research lead'],
    growth: ['Set timeboxes for decisions to avoid postponing - declare "I\'ll decide by this week"', 'Use light structure and routines to maintain momentum - small habits create big change'],
    compatibilityHint: 'Structured partners (GVHA, GSHA) provide stability, while you add depth and meaning. When they create the frame, you breathe soul into it.',
  },
  GSLA: {
    code: 'GSLA',
    name: 'System Guardian',
    summary: 'You are a trustworthy sentinel who protects organizational stability and consistency. With meticulous process management and risk prevention, you keep systems running smoothly. Systems you manage don\'t break at 3 AM. "Already checked that" is your default mode. Thanks to you, others can relax and focus on creative work.',
    strengths: ['Unwavering reliability - promises kept without exception', 'Thorough adherence to rules and procedures - consistency without exceptions', 'Process optimization and quality management - reducing waste and raising quality', 'Ability to prevent risks proactively - stopping problems before they explode'],
    cautions: ['May have resistance to change - new things can sometimes be good', 'May try to control too much - you can\'t manage everything'],
    idealRoles: ['Security/infra lead', 'Finance operations', 'QA/test lead', 'Governance'],
    growth: ['Allow small innovation experiments in proven areas - try new things in safe zones', 'Improve processes together with users - rules exist to serve people'],
    compatibilityHint: 'Big-picture visionaries (RVLA, GVLA) set the direction, and you make it safe and real. When they decide where to go, you make the path safe.',
  },
  GSLF: {
    code: 'GSLF',
    name: 'Pragmatic Solver',
    summary: 'You are a practical craftsman who quietly rolls up your sleeves and fixes problems when they arise. You know field reality better than anyone and adapt flexibly to situations. While others debate theory in meeting rooms, you\'re already fixing the problem. "Actions over words" is your philosophy. When people ask "How did you fix it already?", you just shrug.',
    strengths: ['Hands-on problem solving - practice over theory', 'Calm under pressure - true worth emerges in crisis', 'Producing best results with limited resources - making the most of what\'s available', 'Field-centered pragmatic judgment - focusing on what actually works'],
    cautions: ['May neglect communication or documentation - share your know-how', 'Patience with ambiguity may vary - sometimes waiting is also needed'],
    idealRoles: ['SRE/DevOps engineer', 'Field tech support', 'Operations analyst', 'Support engineer'],
    growth: ['Consistently document solutions and learnings - your future self will thank you', 'Share context with stakeholders early - let them know why you did it this way'],
    compatibilityHint: 'Storytellers (RVHF) broadcast your achievements, and systematic partners (GSLA) turn them into sustainable systems. When you solve problems, they turn them into processes.',
  },
  GSHA: {
    code: 'GSHA',
    name: 'Anchor Mentor',
    summary: 'You are a warm foundation who creates environments where people can grow with stability. With predictable support and genuine care, you draw out team members\' potential. Your team members say "working under this person helps you grow." You don\'t just assign tasks—you explain why they matter and how to do them better.',
    strengths: ['Authentic mentorship - genuinely rooting for growth', 'People-focused policies and systems - making rules serve humans', 'Stable predictable support - someone you can always rely on', 'Long-term talent development - seeing people\'s growth over short-term results'],
    cautions: ['Pace of change may feel slow - sometimes rapid change is needed', 'May unconsciously play gatekeeper - stay open to new people and ideas'],
    idealRoles: ['HR business partner', 'Education/onboarding', 'Customer success strategist', 'Team lead'],
    growth: ['Test new approaches with small groups first - experiment safely', 'Regularly ask for challenging feedback - "What could I do better?"'],
    compatibilityHint: 'Innovative ideators (RVHF, RVLF) suggest new possibilities, and you turn them into sustainable practices. When they propose change, you help it take root.',
  },
  GSHF: {
    code: 'GSHF',
    name: 'Hearth Mediator',
    summary: 'You are a master of harmony who softly resolves conflicts and creates spaces where everyone feels safe. With subtle empathy, you maintain team balance. When you\'re there, the team atmosphere changes. Even tense meetings start to loosen when you enter. People feel they can say what they really think around you.',
    strengths: ['Reading and resolving the essence of conflict - finding the real cause of fights', 'Empathy-based process adjustment - finding ways that work for everyone', 'Stable consistent facilitation - providing predictable stability', 'Presence that creates psychological safety - people feel comfortable speaking around you'],
    cautions: ['May get exhausted absorbing others\' stress - protect your own peace too', 'May want to delay difficult decisions - sometimes disappointing someone is necessary'],
    idealRoles: ['Internal mediator', 'Support lead', 'Team operations', 'Service designer'],
    growth: ['Communicate your limits clearly - have courage to say "up to here"', 'Actively escalate recurring problems - change structures instead of mediating every time'],
    compatibilityHint: 'Logical analysts (GSLA, GVLA) handle objective decisions while you handle people-centered execution. When they decide "what," you create "how together."',
  },
};

export const PERSONA_ARCHETYPES_KO: Record<string, PersonaArchetype> = {
  RVLA: {
    code: 'RVLA',
    name: '별을 빚는 설계자',
    summary: '당신은 미래의 청사진을 그리며 사람들을 하나로 모으는 카리스마 있는 비전가입니다. 큰 그림을 보는 능력과 논리적 분석력을 겸비하여, 복잡한 시스템을 설계하고 팀을 이끄는 데 탁월합니다. 당신의 머릿속에는 항상 3년, 5년 후의 그림이 선명하게 그려져 있으며, 그 비전을 향해 체계적으로 나아가는 힘이 있습니다. 사람들은 당신의 확신에 찬 모습에서 안정감을 느끼고, 자연스럽게 따르게 됩니다.',
    strengths: ['전략적 사고와 명확한 방향 제시 - 복잡한 상황에서도 핵심을 꿰뚫어 봄', '높은 추진력과 실행력 - 생각을 행동으로 빠르게 옮기는 결단력', '복잡한 시스템을 구조화하는 능력 - 혼란 속에서 질서를 만들어냄', '사람들에게 영감을 주는 리더십 - 비전을 공유하고 동기부여하는 힘'],
    cautions: ['세부사항이나 감정적 뉘앙스를 놓칠 수 있음 - 큰 그림에 집중하다 작은 신호를 무시할 수 있어요', '속도에 대한 조급함으로 팀원들이 지칠 수 있음 - 모두가 당신만큼 빠르게 움직이지는 않아요'],
    idealRoles: ['창업자/CEO', '제품 전략가', '기술 리더', '시스템 아키텍트'],
    growth: ['일주일에 한 번 팀원들의 의견을 경청하는 시간 갖기 - "어떻게 생각해?"라고 먼저 물어보세요', '큰 계획을 작은 단계로 나누어 검증하기 - 완벽한 계획보다 빠른 실험이 더 많은 것을 가르쳐줍니다'],
    compatibilityHint: '꼼꼼한 실행가(GSLA, GSHA)와 협력하면 당신의 비전이 현실이 됩니다. 그들이 디테일을 챙기는 동안 당신은 방향을 잡으세요.',
  },
  RVLF: {
    code: 'RVLF',
    name: '불꽃의 발명가',
    summary: '당신은 새로운 가능성을 발견하고 빠르게 실험하는 창의적인 혁신가입니다. 패턴을 읽고 아이디어를 현실로 만드는 속도가 빠르며, 변화에 유연하게 적응합니다. 당신의 뇌는 마치 아이디어 공장처럼 쉬지 않고 돌아갑니다. "만약 이렇게 하면 어떨까?"라는 질문이 끊이지 않죠. 세상이 아직 준비되지 않은 것들을 먼저 보는 눈이 있으며, 그것을 빠르게 시도해보는 용기가 있습니다.',
    strengths: ['번뜩이는 아이디어와 빠른 프로토타이핑 - 생각을 즉시 실체로 만드는 능력', '숨겨진 패턴과 기회 포착 - 남들이 못 보는 연결고리를 발견함', '실패를 두려워하지 않는 실험 정신 - 실패는 데이터일 뿐이라는 마인드셋', '변화에 빠르게 적응하는 유연성 - 피봇을 두려워하지 않음'],
    cautions: ['프로젝트를 끝까지 마무리하기 어려울 수 있음 - 새로운 아이디어가 현재 작업을 방해할 수 있어요', '현실적 제약을 과소평가할 수 있음 - 예산, 시간, 인력의 한계를 고려하세요'],
    idealRoles: ['R&D 리더', '크리에이티브 테크놀로지스트', '스타트업 빌더', '초기 단계 PM'],
    growth: ['하나의 프로젝트를 완료한 후 다음으로 넘어가기 - "Done is better than perfect"를 기억하세요', '실행력 있는 파트너와 초기부터 협업하기 - 당신의 아이디어를 현실로 만들어줄 사람이 필요해요'],
    compatibilityHint: '안정적인 실행가(RSLA, GSLA)가 당신의 아이디어에 날개를 달아줍니다. 당신이 불꽃을 일으키면, 그들이 불을 지펴줄 거예요.',
  },
  RVHA: {
    code: 'RVHA',
    name: '비전의 연결자',
    summary: '당신은 사람들의 마음을 움직이는 스토리텔러이자 팀의 사기를 높이는 전략가입니다. 명확한 미션으로 사람들을 결집시키고, 모두가 가치 있다고 느끼게 만드는 능력이 있습니다. 당신은 "왜"를 설명하는 데 탁월하며, 사람들이 더 큰 목적의 일부라고 느끼게 만듭니다. 회의실에 들어가면 분위기가 바뀌고, 흩어진 의견들이 하나의 방향으로 모이기 시작합니다.',
    strengths: ['영감을 주는 커뮤니케이션 - 복잡한 비전을 누구나 이해하는 이야기로 바꿈', '다양한 이해관계자 조율 - 서로 다른 관점을 하나로 엮는 능력', '장기적 관점의 전략 수립 - 오늘의 작은 행동이 내일 어떤 의미인지 봄', '팀 문화와 사기 관리 - 사람들이 최선을 다하고 싶게 만드는 환경 조성'],
    cautions: ['다른 사람을 돌보느라 자신을 소진시킬 수 있음 - 당신의 배터리도 충전이 필요해요', '모든 결정에서 합의를 구하려다 지칠 수 있음 - 때로는 리더로서 단독 결정도 필요합니다'],
    idealRoles: ['최고 전략 책임자', '커뮤니티 매니저', '조직 문화 설계자', '프로그램 디렉터'],
    growth: ['감정적 돌봄의 일부를 다른 사람에게 위임하기 - 모든 걸 혼자 짊어지지 마세요', '중요한 프로젝트 후 충분한 회복 시간 확보하기 - 쉬는 것도 전략입니다'],
    compatibilityHint: '분석적인 파트너(GVLA)가 당신의 비전에 근거를 더해줍니다. 당신이 "왜"를 말하면, 그들이 "어떻게"를 설계해줄 거예요.',
  },
  RVHF: {
    code: 'RVHF',
    name: '영감의 탐험가',
    summary: '당신은 새로운 트렌드를 감지하고 사람들을 이야기와 분위기로 사로잡는 매력적인 개척자입니다. 공동체를 만들고 활기를 불어넣는 데 천부적인 재능이 있습니다. 당신이 있는 곳에는 항상 무언가 새롭고 신나는 일이 일어납니다. 사람들은 당신 주변에 모여들고, 당신의 열정에 자연스럽게 감염됩니다. 아직 이름도 없는 트렌드를 먼저 발견하는 안테나가 있죠.',
    strengths: ['사람을 끌어당기는 스토리텔링 - 평범한 것도 특별하게 들리게 만듦', '시대의 흐름을 읽는 직관 - 다음에 올 것을 먼저 감지함', '커뮤니티에 불꽃을 지피는 능력 - 사람들을 연결하고 움직이게 함', '자유로운 발상과 창의성 - 기존의 틀에 얽매이지 않음'],
    cautions: ['어려운 선택을 미루는 경향이 있음 - 결정을 피하면 기회도 사라질 수 있어요', '너무 많은 것에 관여하여 에너지가 분산될 수 있음 - 모든 파티에 갈 필요는 없습니다'],
    idealRoles: ['콘텐츠 크리에이터', '브랜드 전략가', '커뮤니티 리더', '디자인 리서처'],
    growth: ['각 시즌마다 명확한 완료 기준 정하기 - "끝"이 언제인지 미리 정해두세요', '에너지를 쏟을 곳과 아닐 곳의 경계 설정하기 - 전략적인 "아니오"가 필요합니다'],
    compatibilityHint: '체계적인 파트너(RVHA, RSHA)가 당신의 에너지를 지속 가능하게 만들어줍니다. 당신이 방향을 제시하면, 그들이 로드맵을 그려줄 거예요.',
  },
  RSLA: {
    code: 'RSLA',
    name: '철벽의 지휘관',
    summary: '당신은 혼란 속에서도 질서를 세우고 팀을 목표로 이끄는 신뢰할 수 있는 리더입니다. 명확한 책임 분배와 효율적인 프로세스 설계로 어떤 프로젝트도 완수해냅니다. 당신 앞에서 "그건 불가능해"라는 말은 의미가 없습니다. 방법을 찾거나, 방법을 만들거나. 팀원들은 당신이 있으면 프로젝트가 반드시 끝난다는 것을 압니다.',
    strengths: ['흔들림 없는 실행력 - 계획을 세우면 반드시 실행하는 추진력', '신속하고 명확한 의사결정 - 필요한 순간에 망설이지 않음', '책임과 역할의 명확한 분배 - 누가 무엇을 해야 하는지 명확하게 정리', '효율적인 운영 시스템 구축 - 반복되는 일을 자동화하고 최적화'],
    cautions: ['유연성이 부족해 보일 수 있음 - 계획 변경에 대한 저항감이 있을 수 있어요', '미묘한 위험 신호를 놓칠 수 있음 - 숫자에 집중하다 분위기의 변화를 놓칠 수 있어요'],
    idealRoles: ['COO/운영 총괄', '프로젝트 매니저', '딜리버리 리더', '프로덕트 매니저'],
    growth: ['계획에 탐색과 실험의 여지를 남기기 - 10%의 "모험 예산"을 확보해보세요', '결정 전 반대 의견을 적극적으로 구하기 - "왜 안 될까?"를 물어보는 습관'],
    compatibilityHint: '비전형 아이디어맨(RVLF)이 새로운 가능성을 열어주고, 당신이 실현시킵니다. 그들의 "미친 아이디어"가 당신의 실행력을 만나면 혁신이 됩니다.',
  },
  RSLF: {
    code: 'RSLF',
    name: '현장의 해결사',
    summary: '당신은 예상치 못한 상황에서도 침착하게 해결책을 찾는 실시간 문제 해결의 달인입니다. 빠른 판단력과 자원 활용 능력으로 위기를 기회로 바꿉니다. 다른 사람들이 당황할 때, 당신은 이미 해결책을 실행하고 있습니다. "어떻게든 된다"가 아니라 "어떻게든 만든다"가 당신의 모토죠.',
    strengths: ['순간적인 판단력과 대응력 - 위기 상황에서 빛나는 순발력', '위기 상황에서의 냉철함 - 압박 속에서도 흔들리지 않는 멘탈', '제한된 자원을 최대한 활용하는 능력 - 있는 것으로 최선을 만들어냄', '현장 중심의 실용적 사고 - 이론보다 실제로 작동하는 것을 중시'],
    cautions: ['문서화나 기록을 소홀히 할 수 있음 - 당신의 노하우가 당신 머릿속에만 있으면 아까워요', '장기적 관점보다 단기 성과에 집중할 수 있음 - 오늘의 해결책이 내일의 문제가 될 수 있어요'],
    idealRoles: ['사고 대응 리더', '세일즈 엔지니어', '라이브 운영 담당', '현장 관리자'],
    growth: ['해결 과정을 정기적으로 기록하고 플레이북으로 만들기 - 5분만 투자해서 메모를 남기세요', '속도와 품질의 균형 찾기 - "빠르게"와 "제대로" 사이의 최적점을 찾으세요'],
    compatibilityHint: '체계적인 플래너(RSLA, GSLA)와 함께하면 순간의 해결책이 지속 가능한 시스템이 됩니다. 당신이 불을 끄면, 그들이 방화 시스템을 만들어요.',
  },
  RSHA: {
    code: 'RSHA',
    name: '따뜻한 조직가',
    summary: '당신은 사람들이 최고의 성과를 낼 수 있는 환경을 만드는 배려심 깊은 관리자입니다. 체계와 따뜻함을 동시에 갖추어, 팀이 안정감 속에서 성장하도록 돕습니다. 당신의 팀에서 일하는 사람들은 "여기서 일하면 성장할 수 있다"고 느낍니다. 규칙과 프로세스가 있지만, 그것이 사람을 위해 존재한다는 걸 모두가 알기 때문이죠.',
    strengths: ['사람 중심의 운영 설계 - 시스템이 사람을 섬기도록 만듦', '팀 문화와 의식 구축 - 소속감과 목적을 느끼게 하는 환경 조성', '갈등의 구조적 해결 - 감정과 사실을 분리해서 해결책을 찾음', '안정적이고 예측 가능한 리더십 - 팀원들이 안심하고 일할 수 있는 환경'],
    cautions: ['모든 것을 계획하려다 유연성을 잃을 수 있음 - 때로는 즉흥적인 것도 괜찮아요', '다른 사람의 감정적 부담을 과하게 떠안을 수 있음 - 당신도 보살핌을 받을 자격이 있어요'],
    idealRoles: ['피플 매니저', '프로젝트/프로그램 매니저', '고객 성공 리더', 'HR 비즈니스 파트너'],
    growth: ['돌봄에도 건강한 경계 설정하기 - "아니오"라고 말하는 것도 돌봄입니다', '완벽하지 않아도 시작하는 실험 허용하기 - 80%에서 시작해도 괜찮아요'],
    compatibilityHint: '창의적인 비전가(RVHA, GVHF)가 새로운 아이디어를, 당신이 실현 가능한 계획으로 바꿔줍니다. 그들이 꿈을 꾸면, 당신이 그것을 현실로 설계해요.',
  },
  RSHF: {
    code: 'RSHF',
    name: '장을 여는 진행자',
    summary: '당신은 어떤 모임이든 활기차게 만들고 모든 사람이 참여하게 하는 타고난 퍼실리테이터입니다. 상황에 따라 유연하게 형식을 조절하며, 포용적인 분위기를 만듭니다. 당신이 진행하는 회의는 지루하지 않습니다. 조용한 사람도 말하게 되고, 시간이 어떻게 갔는지 모르게 되죠. 사람들이 "또 저 사람이 진행하면 좋겠다"고 생각하게 만드는 능력이 있어요.',
    strengths: ['자연스러운 퍼실리테이션 - 누구나 편하게 말할 수 있는 분위기 조성', '상황에 맞는 즉흥적 조정 - 예상과 다르게 흘러가도 유연하게 대응', '모두를 포용하는 따뜻한 에너지 - 소외되는 사람 없이 모두를 참여시킴', '참여를 이끌어내는 능력 - 방관자를 참여자로 만드는 마법'],
    cautions: ['범위가 계속 확대되는 경향이 있음 - "이것도 해볼까?"의 유혹을 조심하세요', '어려운 결정을 미루고 싶어할 수 있음 - 모두가 행복한 답은 없을 때도 있어요'],
    idealRoles: ['워크숍 퍼실리테이터', '커뮤니티 운영자', '교육 설계자', '이벤트 기획자'],
    growth: ['세션 전 양보할 수 없는 핵심 목표 정하기 - "오늘 반드시 해야 할 것" 3개 정하기', '빠르고 명확한 결정 연습하기 - 5초 안에 결정하는 훈련을 해보세요'],
    compatibilityHint: '논리적인 분석가(RSLA, GVLA)가 당신의 유연함에 명확한 프레임을 더해줍니다. 당신이 분위기를 만들면, 그들이 구조를 잡아줘요.',
  },
  GVLA: {
    code: 'GVLA',
    name: '심연의 설계자',
    summary: '당신은 표면 아래의 구조를 꿰뚫어 보고 몇 수 앞을 내다보는 깊은 사고의 전략가입니다. 복잡한 시스템을 이해하고 장기적으로 견고한 설계를 만드는 데 탁월합니다. 당신이 설계한 것은 10년이 지나도 작동합니다. 다른 사람들이 "왜 이렇게 복잡하게?"라고 물을 때, 시간이 지나면 "그때 그렇게 해두길 잘했다"고 말하게 되죠.',
    strengths: ['복잡한 시스템의 본질 파악 - 혼란 속에서도 근본 원인을 찾아냄', '장기적 리스크 예측과 대비 - 3년 후에 터질 문제를 오늘 방지함', '일관성 있는 아키텍처 설계 - 시간이 지나도 확장 가능한 구조', '깊이 있는 분석과 통찰 - 남들이 보지 못하는 것을 봄'],
    cautions: ['분석 단계에서 너무 오래 머물 수 있음 - 완벽한 설계를 기다리다 기회를 놓칠 수 있어요', '급격한 변화에 저항감을 느낄 수 있음 - 가끔은 불완전한 상태로 출발해야 할 때도 있어요'],
    idealRoles: ['시니어/스태프 엔지니어', '엔터프라이즈 아키텍트', '리서치 전략가', '기술 자문'],
    growth: ['완벽하지 않아도 작은 단위로 검증하고 배포하기 - MVP부터 시작해보세요', '초기에 피드백을 받아 방향 조정하기 - 혼자 너무 멀리 가기 전에 체크인하세요'],
    compatibilityHint: '에너지 넘치는 실험가(RVLF)가 도전적인 문제를 가져오고, 당신이 견고한 해결책을 만듭니다. 그들의 속도와 당신의 깊이가 만나면 최고의 결과가 나와요.',
  },
  GVLF: {
    code: 'GVLF',
    name: '고요한 탐구자',
    summary: '당신은 차분하게 가설을 세우고 증거를 통해 개선해나가는 분석적인 탐험가입니다. 깊은 집중력으로 복잡한 문제를 풀어내고, 데이터에서 인사이트를 발견합니다. 당신의 작업 공간은 고요하지만, 그 안에서 혁신이 태어납니다. "잠깐, 이 숫자가 이상해"라는 당신의 한마디가 큰 실수를 막을 때가 많죠.',
    strengths: ['가설 기반의 체계적 실험 - 추측이 아닌 증거로 결정을 내림', '방해받지 않는 깊은 몰입 - 복잡한 문제에 깊이 파고드는 집중력', '데이터에서 패턴 발견 - 숫자 사이에 숨겨진 이야기를 읽어냄', '차분하고 객관적인 분석 - 감정에 휘둘리지 않는 판단력'],
    cautions: ['주목받는 것을 피하여 공로를 인정받지 못할 수 있음 - 당신의 기여를 알리는 것도 중요해요', '잦은 맥락 전환이 에너지를 크게 소모함 - 딥워크 시간을 보호하세요'],
    idealRoles: ['데이터 분석가', '머신러닝 엔지니어', '제품 분석가', '연구 개발자'],
    growth: ['완벽하기 전에 초안을 공유하여 피드백 받기 - 50%에서 한 번 보여주세요', '스토리텔링에 능한 사람과 협력하여 영향력 확대하기 - 발견한 것을 세상에 알리세요'],
    compatibilityHint: '표현력 있는 커뮤니케이터(RVHF)가 당신의 발견을 세상에 알려줍니다. 당신이 진실을 찾으면, 그들이 그것을 이야기로 만들어요.',
  },
  GVHA: {
    code: 'GVHA',
    name: '지혜로운 안내자',
    summary: '당신은 깊이 경청하고 패턴을 읽어 핵심을 짚어주는 신뢰받는 조언자입니다. 차분한 존재감으로 사람들이 스스로 답을 찾도록 이끄는 능력이 있습니다. 당신과 대화를 나눈 사람들은 "내가 원래 알고 있었는데 당신 덕분에 깨달았다"고 말합니다. 답을 주는 게 아니라 답을 찾게 해주는 특별한 능력이 있어요.',
    strengths: ['깊이 있는 경청과 공감 - 말 너머의 진짜 의도를 읽어냄', '복잡한 상황에서 패턴 인식 - 반복되는 문제의 근본을 찾아냄', '신뢰를 주는 차분한 존재감 - 당신이 있으면 안심이 됨', '통찰력 있는 질문과 조언 - 한 마디가 생각을 바꿔놓음'],
    cautions: ['명확한 방향 제시를 주저할 수 있음 - 때로는 직접적인 답이 필요할 때도 있어요', '시끄럽고 빠른 환경에서 에너지가 빨리 소진됨 - 회복 시간을 확보하세요'],
    idealRoles: ['코치/멘토', 'UX 리서처', '전략 컨설턴트', '시니어 프로덕트 매니저'],
    growth: ['조언을 넘어 명확한 결정과 방향을 제시하기 - "제 생각은 이렇습니다"라고 말해보세요', '실행력 있는 파트너와 협업하여 아이디어를 현실로 - 통찰을 행동으로 옮기세요'],
    compatibilityHint: '실행력 있는 조직가(RSHA)가 당신의 통찰을 구체적인 프로세스로 만들어줍니다. 당신이 "왜"를 찾으면, 그들이 "어떻게"를 실행해요.',
  },
  GVHF: {
    code: 'GVHF',
    name: '영혼의 길잡이',
    summary: '당신은 삶의 의미를 탐구하고 사람들의 내면 변화를 돕는 깊이 있는 안내자입니다. 서두르지 않는 인간적인 속도로 진정한 성장을 이끌어냅니다. 당신과 함께한 시간은 "치유"처럼 느껴집니다. 빠르게 돌아가는 세상에서 당신은 "잠깐, 정말 중요한 게 뭐지?"를 묻게 만드는 존재예요.',
    strengths: ['본질을 꿰뚫는 깊은 통찰 - 표면 너머의 진짜를 봄', '타인의 감정을 섬세하게 읽는 공감력 - 말하지 않아도 알아차림', '부드럽지만 의미 있는 실험 - 작은 변화가 큰 성장으로', '진정성 있는 연결 - 가면 없는 관계를 만듦'],
    cautions: ['명확한 구조 없이 방향을 잃을 수 있음 - 가끔은 지도가 필요해요', '갈등이나 대립을 피하려 할 수 있음 - 건강한 긴장도 성장의 일부입니다'],
    idealRoles: ['라이프 코치', '퍼실리테이터', '크리에이티브 디렉터', '연구 리더'],
    growth: ['결정에 타임박스를 정해 미루지 않기 - "이번 주까지 결정하겠다" 선언하기', '가벼운 구조와 루틴으로 모멘텀 유지하기 - 작은 습관이 큰 변화를 만들어요'],
    compatibilityHint: '체계적인 파트너(GVHA, GSHA)가 안정적인 토대를, 당신이 깊이와 의미를 더합니다. 그들이 틀을 만들면, 당신이 영혼을 불어넣어요.',
  },
  GSLA: {
    code: 'GSLA',
    name: '시스템의 수호자',
    summary: '당신은 조직의 안정성과 일관성을 지키는 믿음직한 파수꾼입니다. 꼼꼼한 프로세스 관리와 리스크 예방으로 시스템이 흔들림 없이 돌아가게 합니다. 당신이 관리하는 시스템은 새벽 3시에도 문제가 생기지 않습니다. "그건 이미 확인했어요"가 당신의 기본 모드죠. 덕분에 다른 사람들은 안심하고 창의적인 일에 집중할 수 있습니다.',
    strengths: ['흔들림 없는 신뢰성 - 약속한 것은 반드시 지킴', '규정과 절차의 철저한 준수 - 예외 없는 일관성', '프로세스 최적화와 품질 관리 - 낭비를 줄이고 품질을 높임', '리스크를 미리 차단하는 능력 - 문제가 터지기 전에 막음'],
    cautions: ['변화에 대한 저항감이 있을 수 있음 - 새로운 것도 때로는 좋을 수 있어요', '너무 많은 것을 통제하려 할 수 있음 - 모든 것을 관리할 수는 없어요'],
    idealRoles: ['보안/인프라 리더', '재무 운영 담당', 'QA/테스트 리더', '거버넌스 담당'],
    growth: ['검증된 영역에서 작은 혁신 실험 허용하기 - 안전한 곳에서 새로운 것을 시도해보세요', '사용자와 함께 프로세스를 개선하기 - 규칙은 사람을 위해 존재합니다'],
    compatibilityHint: '큰 그림을 그리는 비전가(RVLA, GVLA)가 방향을 정하면, 당신이 안전하게 실현시킵니다. 그들이 어디로 갈지 정하면, 당신이 그 길을 안전하게 만들어요.',
  },
  GSLF: {
    code: 'GSLF',
    name: '묵묵한 해결사',
    summary: '당신은 문제가 생기면 조용히 손을 걷어붙이고 해결하는 실용적인 장인입니다. 현장의 현실을 누구보다 잘 알고, 상황에 맞게 유연하게 대응합니다. 회의실에서 이론을 논하는 동안, 당신은 이미 문제를 고치고 있습니다. "말보다 행동"이 당신의 철학이에요. 사람들이 "어떻게 벌써 고쳤어?"라고 물을 때, 당신은 그냥 어깨를 으쓱합니다.',
    strengths: ['직접 손으로 문제를 해결하는 능력 - 이론보다 실전', '압박 속에서도 흔들리지 않는 침착함 - 위기에서 진가가 드러남', '제한된 자원으로 최선의 결과 도출 - 있는 것으로 최고를 만듦', '현장 중심의 실용적 판단 - 실제로 작동하는 것에 집중'],
    cautions: ['소통이나 문서화를 소홀히 할 수 있음 - 당신의 노하우를 나누세요', '모호한 상황에서 인내심이 떨어질 수 있음 - 때로는 기다림도 필요해요'],
    idealRoles: ['SRE/DevOps 엔지니어', '현장 기술 지원', '운영 분석가', '기술 지원 엔지니어'],
    growth: ['해결 과정과 배움을 꾸준히 기록하기 - 미래의 당신이 고마워할 거예요', '이해관계자에게 맥락을 먼저 공유하기 - 왜 이렇게 했는지 알려주세요'],
    compatibilityHint: '스토리텔러(RVHF)가 당신의 성과를 알리고, 체계적인 파트너(GSLA)가 지속 가능한 시스템으로 만듭니다. 당신이 문제를 풀면, 그들이 그것을 프로세스로 만들어요.',
  },
  GSHA: {
    code: 'GSHA',
    name: '든든한 멘토',
    summary: '당신은 사람들이 안정감 속에서 성장할 수 있는 환경을 만드는 따뜻한 기반입니다. 예측 가능한 지원과 진심 어린 관심으로 팀원들의 잠재력을 이끌어냅니다. 당신의 팀원들은 "이 사람 밑에서 일하면 성장한다"고 말합니다. 당신은 단순히 일을 시키지 않고, 왜 이 일이 중요한지, 어떻게 하면 더 잘할 수 있는지를 알려주니까요.',
    strengths: ['진정성 있는 멘토십 - 진심으로 성장을 응원함', '사람을 생각하는 정책과 시스템 - 규칙이 사람을 섬기도록 만듦', '안정적이고 예측 가능한 지원 - 언제든 의지할 수 있는 존재', '장기적 관점의 인재 육성 - 단기 성과보다 사람의 성장을 봄'],
    cautions: ['변화의 속도가 느리게 느껴질 수 있음 - 가끔은 빠른 변화도 필요해요', '무의식적으로 문지기 역할을 할 수 있음 - 새로운 사람과 아이디어에 열려있으세요'],
    idealRoles: ['HR 비즈니스 파트너', '교육/온보딩 담당', '고객 성공 전략가', '팀 리드'],
    growth: ['작은 그룹에서 새로운 방식을 먼저 시험하기 - 안전하게 실험해보세요', '도전적인 피드백을 정기적으로 요청하기 - "제가 뭘 더 잘할 수 있을까요?"'],
    compatibilityHint: '혁신적인 아이디어맨(RVHF, RVLF)이 새로운 가능성을, 당신이 지속 가능한 실천으로 바꿉니다. 그들이 변화를 제안하면, 당신이 그것을 뿌리내리게 해요.',
  },
  GSHF: {
    code: 'GSHF',
    name: '평화의 조율사',
    summary: '당신은 갈등을 부드럽게 해소하고 모두가 안전하다고 느끼는 공간을 만드는 조화의 마스터입니다. 섬세한 공감력으로 팀의 균형을 유지합니다. 당신이 있으면 팀의 분위기가 달라집니다. 긴장된 회의도 당신이 들어오면 조금씩 풀리기 시작하죠. 사람들은 당신 앞에서 진짜 속마음을 말할 수 있다고 느낍니다.',
    strengths: ['갈등의 본질을 읽고 해소하는 능력 - 싸움의 진짜 원인을 찾아냄', '공감에 기반한 프로세스 조정 - 모두가 편한 방법을 찾음', '안정적이고 일관된 퍼실리테이션 - 예측 가능한 안정감 제공', '심리적 안전감을 주는 존재감 - 당신이 있으면 말하기 편함'],
    cautions: ['다른 사람의 스트레스를 흡수하여 지칠 수 있음 - 당신의 평화도 지키세요', '어려운 결정을 미루려 할 수 있음 - 때로는 누군가를 실망시키는 것도 필요해요'],
    idealRoles: ['조직 내 중재자', '고객 지원 리더', '팀 운영 담당', '서비스 디자이너'],
    growth: ['자신의 한계를 명확히 전달하기 - "여기까지만"이라고 말할 용기를 가지세요', '반복되는 문제는 적극적으로 상위 보고하기 - 매번 중재하지 말고 구조를 바꾸세요'],
    compatibilityHint: '논리적인 분석가(GSLA, GVLA)가 객관적 판단을, 당신이 사람 중심의 실행을 담당합니다. 그들이 "무엇"을 정하면, 당신이 "어떻게 함께"를 만들어요.',
  },
};

export function getLocalizedArchetypes(locale: string): Record<string, PersonaArchetype> {
  return locale === 'ko' ? PERSONA_ARCHETYPES_KO : PERSONA_ARCHETYPES;
}
